/**
 * generated by Xtext 2.40.0
 */
package com.robenglander.libretto.spec.librettoSpec.util;

import com.robenglander.libretto.spec.librettoSpec.*;

import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;

import org.eclipse.emf.ecore.util.Switch;

/**
 * <!-- begin-user-doc -->
 * The <b>Switch</b> for the model's inheritance hierarchy.
 * It supports the call {@link #doSwitch(EObject) doSwitch(object)}
 * to invoke the <code>caseXXX</code> method for each class of the model,
 * starting with the actual class of the object
 * and proceeding up the inheritance hierarchy
 * until a non-null result is returned,
 * which is the result of the switch.
 * <!-- end-user-doc -->
 * @see com.robenglander.libretto.spec.librettoSpec.LibrettoSpecPackage
 * @generated
 */
public class LibrettoSpecSwitch<T> extends Switch<T>
{
  /**
   * The cached model package
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected static LibrettoSpecPackage modelPackage;

  /**
   * Creates an instance of the switch.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public LibrettoSpecSwitch()
  {
    if (modelPackage == null)
    {
      modelPackage = LibrettoSpecPackage.eINSTANCE;
    }
  }

  /**
   * Checks whether this is a switch for the given package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param ePackage the package in question.
   * @return whether this is a switch for the given package.
   * @generated
   */
  @Override
  protected boolean isSwitchFor(EPackage ePackage)
  {
    return ePackage == modelPackage;
  }

  /**
   * Calls <code>caseXXX</code> for each class of the model until one returns a non null result; it yields that result.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the first non-null result returned by a <code>caseXXX</code> call.
   * @generated
   */
  @Override
  protected T doSwitch(int classifierID, EObject theEObject)
  {
    switch (classifierID)
    {
      case LibrettoSpecPackage.SPEC:
      {
        Spec spec = (Spec)theEObject;
        T result = caseSpec(spec);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case LibrettoSpecPackage.SPEC_SECTION:
      {
        SpecSection specSection = (SpecSection)theEObject;
        T result = caseSpecSection(specSection);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case LibrettoSpecPackage.METADATA_FIELD:
      {
        MetadataField metadataField = (MetadataField)theEObject;
        T result = caseMetadataField(metadataField);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case LibrettoSpecPackage.DEPENDENCIES_SECTION_KEYWORD:
      {
        DependenciesSectionKeyword dependenciesSectionKeyword = (DependenciesSectionKeyword)theEObject;
        T result = caseDependenciesSectionKeyword(dependenciesSectionKeyword);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case LibrettoSpecPackage.DEPENDENCY_KEYWORD:
      {
        DependencyKeyword dependencyKeyword = (DependencyKeyword)theEObject;
        T result = caseDependencyKeyword(dependencyKeyword);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case LibrettoSpecPackage.DEPENDENCY_RECORD:
      {
        DependencyRecord dependencyRecord = (DependencyRecord)theEObject;
        T result = caseDependencyRecord(dependencyRecord);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case LibrettoSpecPackage.DEPENDENCY_RECORD_ITEM:
      {
        DependencyRecordItem dependencyRecordItem = (DependencyRecordItem)theEObject;
        T result = caseDependencyRecordItem(dependencyRecordItem);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case LibrettoSpecPackage.TARGET_SPEC_FIELD:
      {
        TargetSpecField targetSpecField = (TargetSpecField)theEObject;
        T result = caseTargetSpecField(targetSpecField);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case LibrettoSpecPackage.REFERENCE_RECORD:
      {
        ReferenceRecord referenceRecord = (ReferenceRecord)theEObject;
        T result = caseReferenceRecord(referenceRecord);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case LibrettoSpecPackage.REFERENCE_RECORD_ITEM:
      {
        ReferenceRecordItem referenceRecordItem = (ReferenceRecordItem)theEObject;
        T result = caseReferenceRecordItem(referenceRecordItem);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case LibrettoSpecPackage.TITLE_FIELD:
      {
        TitleField titleField = (TitleField)theEObject;
        T result = caseTitleField(titleField);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case LibrettoSpecPackage.TYPE_FIELD:
      {
        TypeField typeField = (TypeField)theEObject;
        T result = caseTypeField(typeField);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case LibrettoSpecPackage.CITATION_FIELD:
      {
        CitationField citationField = (CitationField)theEObject;
        T result = caseCitationField(citationField);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case LibrettoSpecPackage.LOCATOR_FIELD:
      {
        LocatorField locatorField = (LocatorField)theEObject;
        T result = caseLocatorField(locatorField);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case LibrettoSpecPackage.AUTHORITY_NOTES_FIELD:
      {
        AuthorityNotesField authorityNotesField = (AuthorityNotesField)theEObject;
        T result = caseAuthorityNotesField(authorityNotesField);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case LibrettoSpecPackage.METADATA_TEXT_FIELD:
      {
        MetadataTextField metadataTextField = (MetadataTextField)theEObject;
        T result = caseMetadataTextField(metadataTextField);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case LibrettoSpecPackage.PROSE_RECORD:
      {
        ProseRecord proseRecord = (ProseRecord)theEObject;
        T result = caseProseRecord(proseRecord);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case LibrettoSpecPackage.SECTION_CONTEXT_RECORD:
      {
        SectionContextRecord sectionContextRecord = (SectionContextRecord)theEObject;
        T result = caseSectionContextRecord(sectionContextRecord);
        if (result == null) result = caseProseRecord(sectionContextRecord);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case LibrettoSpecPackage.SECTION_CONTEXT_RECORD_ITEM:
      {
        SectionContextRecordItem sectionContextRecordItem = (SectionContextRecordItem)theEObject;
        T result = caseSectionContextRecordItem(sectionContextRecordItem);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case LibrettoSpecPackage.SUBSECTION_CONTEXT_RECORD:
      {
        SubsectionContextRecord subsectionContextRecord = (SubsectionContextRecord)theEObject;
        T result = caseSubsectionContextRecord(subsectionContextRecord);
        if (result == null) result = caseProseRecord(subsectionContextRecord);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case LibrettoSpecPackage.SUBSECTION_CONTEXT_RECORD_ITEM:
      {
        SubsectionContextRecordItem subsectionContextRecordItem = (SubsectionContextRecordItem)theEObject;
        T result = caseSubsectionContextRecordItem(subsectionContextRecordItem);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case LibrettoSpecPackage.OUT_OF_SCOPE_RECORD:
      {
        OutOfScopeRecord outOfScopeRecord = (OutOfScopeRecord)theEObject;
        T result = caseOutOfScopeRecord(outOfScopeRecord);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case LibrettoSpecPackage.OUT_OF_SCOPE_RECORD_ITEM:
      {
        OutOfScopeRecordItem outOfScopeRecordItem = (OutOfScopeRecordItem)theEObject;
        T result = caseOutOfScopeRecordItem(outOfScopeRecordItem);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case LibrettoSpecPackage.STATEMENT_FIELD:
      {
        StatementField statementField = (StatementField)theEObject;
        T result = caseStatementField(statementField);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case LibrettoSpecPackage.BEHAVIOR_RECORD:
      {
        BehaviorRecord behaviorRecord = (BehaviorRecord)theEObject;
        T result = caseBehaviorRecord(behaviorRecord);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case LibrettoSpecPackage.BEHAVIOR_RECORD_ITEM:
      {
        BehaviorRecordItem behaviorRecordItem = (BehaviorRecordItem)theEObject;
        T result = caseBehaviorRecordItem(behaviorRecordItem);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case LibrettoSpecPackage.ACTOR_FIELD:
      {
        ActorField actorField = (ActorField)theEObject;
        T result = caseActorField(actorField);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case LibrettoSpecPackage.ACTION_FIELD:
      {
        ActionField actionField = (ActionField)theEObject;
        T result = caseActionField(actionField);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case LibrettoSpecPackage.OBJECTS_FIELD:
      {
        ObjectsField objectsField = (ObjectsField)theEObject;
        T result = caseObjectsField(objectsField);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case LibrettoSpecPackage.READS_FIELD:
      {
        ReadsField readsField = (ReadsField)theEObject;
        T result = caseReadsField(readsField);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case LibrettoSpecPackage.WRITES_FIELD:
      {
        WritesField writesField = (WritesField)theEObject;
        T result = caseWritesField(writesField);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case LibrettoSpecPackage.CONDITIONS_FIELD:
      {
        ConditionsField conditionsField = (ConditionsField)theEObject;
        T result = caseConditionsField(conditionsField);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case LibrettoSpecPackage.OUTCOMES_FIELD:
      {
        OutcomesField outcomesField = (OutcomesField)theEObject;
        T result = caseOutcomesField(outcomesField);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case LibrettoSpecPackage.LABEL_FIELD:
      {
        LabelField labelField = (LabelField)theEObject;
        T result = caseLabelField(labelField);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case LibrettoSpecPackage.REFERENCES_FIELD:
      {
        ReferencesField referencesField = (ReferencesField)theEObject;
        T result = caseReferencesField(referencesField);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case LibrettoSpecPackage.DEPENDENCIES_FIELD:
      {
        DependenciesField dependenciesField = (DependenciesField)theEObject;
        T result = caseDependenciesField(dependenciesField);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case LibrettoSpecPackage.NOTES_FIELD:
      {
        NotesField notesField = (NotesField)theEObject;
        T result = caseNotesField(notesField);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case LibrettoSpecPackage.CONTEXT_FIELD:
      {
        ContextField contextField = (ContextField)theEObject;
        T result = caseContextField(contextField);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case LibrettoSpecPackage.OPERATION_SURFACE_RECORD:
      {
        OperationSurfaceRecord operationSurfaceRecord = (OperationSurfaceRecord)theEObject;
        T result = caseOperationSurfaceRecord(operationSurfaceRecord);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case LibrettoSpecPackage.OPERATION_SURFACE_RECORD_ITEM:
      {
        OperationSurfaceRecordItem operationSurfaceRecordItem = (OperationSurfaceRecordItem)theEObject;
        T result = caseOperationSurfaceRecordItem(operationSurfaceRecordItem);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case LibrettoSpecPackage.OPERATION_EXPRESSION_FIELD:
      {
        OperationExpressionField operationExpressionField = (OperationExpressionField)theEObject;
        T result = caseOperationExpressionField(operationExpressionField);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case LibrettoSpecPackage.OUTCOME_CLASS_FIELD:
      {
        OutcomeClassField outcomeClassField = (OutcomeClassField)theEObject;
        T result = caseOutcomeClassField(outcomeClassField);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case LibrettoSpecPackage.IMPLEMENTS_SURFACE_RECORD:
      {
        ImplementsSurfaceRecord implementsSurfaceRecord = (ImplementsSurfaceRecord)theEObject;
        T result = caseImplementsSurfaceRecord(implementsSurfaceRecord);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case LibrettoSpecPackage.IMPLEMENTS_SURFACE_RECORD_ITEM:
      {
        ImplementsSurfaceRecordItem implementsSurfaceRecordItem = (ImplementsSurfaceRecordItem)theEObject;
        T result = caseImplementsSurfaceRecordItem(implementsSurfaceRecordItem);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case LibrettoSpecPackage.IMPLEMENTS_SURFACE_TARGET_FIELD:
      {
        ImplementsSurfaceTargetField implementsSurfaceTargetField = (ImplementsSurfaceTargetField)theEObject;
        T result = caseImplementsSurfaceTargetField(implementsSurfaceTargetField);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case LibrettoSpecPackage.BOUNDARY_RECORD:
      {
        BoundaryRecord boundaryRecord = (BoundaryRecord)theEObject;
        T result = caseBoundaryRecord(boundaryRecord);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case LibrettoSpecPackage.BOUNDARY_RECORD_ITEM:
      {
        BoundaryRecordItem boundaryRecordItem = (BoundaryRecordItem)theEObject;
        T result = caseBoundaryRecordItem(boundaryRecordItem);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case LibrettoSpecPackage.BOUNDARY_SPEC_ID_FIELD:
      {
        BoundarySpecIdField boundarySpecIdField = (BoundarySpecIdField)theEObject;
        T result = caseBoundarySpecIdField(boundarySpecIdField);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case LibrettoSpecPackage.BOUNDARY_OPERATION_ID_FIELD:
      {
        BoundaryOperationIdField boundaryOperationIdField = (BoundaryOperationIdField)theEObject;
        T result = caseBoundaryOperationIdField(boundaryOperationIdField);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case LibrettoSpecPackage.BOUNDARY_PROFILE_ID_FIELD:
      {
        BoundaryProfileIdField boundaryProfileIdField = (BoundaryProfileIdField)theEObject;
        T result = caseBoundaryProfileIdField(boundaryProfileIdField);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case LibrettoSpecPackage.BOUNDARY_RAW_FIELD:
      {
        BoundaryRawField boundaryRawField = (BoundaryRawField)theEObject;
        T result = caseBoundaryRawField(boundaryRawField);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case LibrettoSpecPackage.ACCEPTANCE_TEST_RECORD:
      {
        AcceptanceTestRecord acceptanceTestRecord = (AcceptanceTestRecord)theEObject;
        T result = caseAcceptanceTestRecord(acceptanceTestRecord);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case LibrettoSpecPackage.ACCEPTANCE_TEST_RECORD_ITEM:
      {
        AcceptanceTestRecordItem acceptanceTestRecordItem = (AcceptanceTestRecordItem)theEObject;
        T result = caseAcceptanceTestRecordItem(acceptanceTestRecordItem);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case LibrettoSpecPackage.VALIDATES_FIELD:
      {
        ValidatesField validatesField = (ValidatesField)theEObject;
        T result = caseValidatesField(validatesField);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case LibrettoSpecPackage.PRECONDITIONS_FIELD:
      {
        PreconditionsField preconditionsField = (PreconditionsField)theEObject;
        T result = casePreconditionsField(preconditionsField);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case LibrettoSpecPackage.ACTIONS_FIELD:
      {
        ActionsField actionsField = (ActionsField)theEObject;
        T result = caseActionsField(actionsField);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case LibrettoSpecPackage.ASSERTIONS_FIELD:
      {
        AssertionsField assertionsField = (AssertionsField)theEObject;
        T result = caseAssertionsField(assertionsField);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case LibrettoSpecPackage.IMPLEMENTATION_DIRECTIVE_RECORD:
      {
        ImplementationDirectiveRecord implementationDirectiveRecord = (ImplementationDirectiveRecord)theEObject;
        T result = caseImplementationDirectiveRecord(implementationDirectiveRecord);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case LibrettoSpecPackage.IMPLEMENTATION_DIRECTIVE_RECORD_ITEM:
      {
        ImplementationDirectiveRecordItem implementationDirectiveRecordItem = (ImplementationDirectiveRecordItem)theEObject;
        T result = caseImplementationDirectiveRecordItem(implementationDirectiveRecordItem);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case LibrettoSpecPackage.APPLIES_TO_FIELD:
      {
        AppliesToField appliesToField = (AppliesToField)theEObject;
        T result = caseAppliesToField(appliesToField);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case LibrettoSpecPackage.STRENGTH_FIELD:
      {
        StrengthField strengthField = (StrengthField)theEObject;
        T result = caseStrengthField(strengthField);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case LibrettoSpecPackage.DIRECTIVE_FIELD:
      {
        DirectiveField directiveField = (DirectiveField)theEObject;
        T result = caseDirectiveField(directiveField);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case LibrettoSpecPackage.CATEGORY_FIELD:
      {
        CategoryField categoryField = (CategoryField)theEObject;
        T result = caseCategoryField(categoryField);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case LibrettoSpecPackage.CONSTRAINTS_FIELD:
      {
        ConstraintsField constraintsField = (ConstraintsField)theEObject;
        T result = caseConstraintsField(constraintsField);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case LibrettoSpecPackage.ALLOWED_FLEXIBILITY_FIELD:
      {
        AllowedFlexibilityField allowedFlexibilityField = (AllowedFlexibilityField)theEObject;
        T result = caseAllowedFlexibilityField(allowedFlexibilityField);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case LibrettoSpecPackage.RATIONALE_FIELD:
      {
        RationaleField rationaleField = (RationaleField)theEObject;
        T result = caseRationaleField(rationaleField);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case LibrettoSpecPackage.SOURCE_BLOCK:
      {
        SourceBlock sourceBlock = (SourceBlock)theEObject;
        T result = caseSourceBlock(sourceBlock);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case LibrettoSpecPackage.SOURCE_BLOCK_ITEM:
      {
        SourceBlockItem sourceBlockItem = (SourceBlockItem)theEObject;
        T result = caseSourceBlockItem(sourceBlockItem);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case LibrettoSpecPackage.SECTION_FIELD:
      {
        SectionField sectionField = (SectionField)theEObject;
        T result = caseSectionField(sectionField);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case LibrettoSpecPackage.SUBSECTION_FIELD:
      {
        SubsectionField subsectionField = (SubsectionField)theEObject;
        T result = caseSubsectionField(subsectionField);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case LibrettoSpecPackage.TEXT_FIELD:
      {
        TextField textField = (TextField)theEObject;
        T result = caseTextField(textField);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case LibrettoSpecPackage.IDENTIFIER_LIST:
      {
        IdentifierList identifierList = (IdentifierList)theEObject;
        T result = caseIdentifierList(identifierList);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case LibrettoSpecPackage.BEHAVIOR_ID_LIST:
      {
        BehaviorIdList behaviorIdList = (BehaviorIdList)theEObject;
        T result = caseBehaviorIdList(behaviorIdList);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case LibrettoSpecPackage.REFERENCE_ID_LIST:
      {
        ReferenceIdList referenceIdList = (ReferenceIdList)theEObject;
        T result = caseReferenceIdList(referenceIdList);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case LibrettoSpecPackage.TEXT_LIST:
      {
        TextList textList = (TextList)theEObject;
        T result = caseTextList(textList);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case LibrettoSpecPackage.TEXT_VALUE:
      {
        TextValue textValue = (TextValue)theEObject;
        T result = caseTextValue(textValue);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case LibrettoSpecPackage.IDENTIFIER_VALUE:
      {
        IdentifierValue identifierValue = (IdentifierValue)theEObject;
        T result = caseIdentifierValue(identifierValue);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case LibrettoSpecPackage.DOTTED_IDENTIFIER:
      {
        DottedIdentifier dottedIdentifier = (DottedIdentifier)theEObject;
        T result = caseDottedIdentifier(dottedIdentifier);
        if (result == null) result = caseIdentifierValue(dottedIdentifier);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case LibrettoSpecPackage.METADATA_SECTION:
      {
        MetadataSection metadataSection = (MetadataSection)theEObject;
        T result = caseMetadataSection(metadataSection);
        if (result == null) result = caseSpecSection(metadataSection);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case LibrettoSpecPackage.DEPENDENCIES_SECTION:
      {
        DependenciesSection dependenciesSection = (DependenciesSection)theEObject;
        T result = caseDependenciesSection(dependenciesSection);
        if (result == null) result = caseSpecSection(dependenciesSection);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case LibrettoSpecPackage.REFERENCES_SECTION:
      {
        ReferencesSection referencesSection = (ReferencesSection)theEObject;
        T result = caseReferencesSection(referencesSection);
        if (result == null) result = caseSpecSection(referencesSection);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case LibrettoSpecPackage.PROSE_SECTION:
      {
        ProseSection proseSection = (ProseSection)theEObject;
        T result = caseProseSection(proseSection);
        if (result == null) result = caseSpecSection(proseSection);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case LibrettoSpecPackage.OUT_OF_SCOPE_SECTION:
      {
        OutOfScopeSection outOfScopeSection = (OutOfScopeSection)theEObject;
        T result = caseOutOfScopeSection(outOfScopeSection);
        if (result == null) result = caseSpecSection(outOfScopeSection);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case LibrettoSpecPackage.OPERATION_SURFACE_SECTION:
      {
        OperationSurfaceSection operationSurfaceSection = (OperationSurfaceSection)theEObject;
        T result = caseOperationSurfaceSection(operationSurfaceSection);
        if (result == null) result = caseSpecSection(operationSurfaceSection);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case LibrettoSpecPackage.IMPLEMENTS_SURFACE_SECTION:
      {
        ImplementsSurfaceSection implementsSurfaceSection = (ImplementsSurfaceSection)theEObject;
        T result = caseImplementsSurfaceSection(implementsSurfaceSection);
        if (result == null) result = caseSpecSection(implementsSurfaceSection);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case LibrettoSpecPackage.BOUNDARY_EXPORTS_SECTION:
      {
        BoundaryExportsSection boundaryExportsSection = (BoundaryExportsSection)theEObject;
        T result = caseBoundaryExportsSection(boundaryExportsSection);
        if (result == null) result = caseSpecSection(boundaryExportsSection);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case LibrettoSpecPackage.BOUNDARY_IMPORTS_SECTION:
      {
        BoundaryImportsSection boundaryImportsSection = (BoundaryImportsSection)theEObject;
        T result = caseBoundaryImportsSection(boundaryImportsSection);
        if (result == null) result = caseSpecSection(boundaryImportsSection);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case LibrettoSpecPackage.BEHAVIORS_SECTION:
      {
        BehaviorsSection behaviorsSection = (BehaviorsSection)theEObject;
        T result = caseBehaviorsSection(behaviorsSection);
        if (result == null) result = caseSpecSection(behaviorsSection);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case LibrettoSpecPackage.ACCEPTANCE_TESTS_SECTION:
      {
        AcceptanceTestsSection acceptanceTestsSection = (AcceptanceTestsSection)theEObject;
        T result = caseAcceptanceTestsSection(acceptanceTestsSection);
        if (result == null) result = caseSpecSection(acceptanceTestsSection);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case LibrettoSpecPackage.IMPLEMENTATION_DIRECTIVES_SECTION:
      {
        ImplementationDirectivesSection implementationDirectivesSection = (ImplementationDirectivesSection)theEObject;
        T result = caseImplementationDirectivesSection(implementationDirectivesSection);
        if (result == null) result = caseSpecSection(implementationDirectivesSection);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      default: return defaultCase(theEObject);
    }
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Spec</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Spec</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseSpec(Spec object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Spec Section</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Spec Section</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseSpecSection(SpecSection object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Metadata Field</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Metadata Field</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseMetadataField(MetadataField object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Dependencies Section Keyword</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Dependencies Section Keyword</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseDependenciesSectionKeyword(DependenciesSectionKeyword object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Dependency Keyword</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Dependency Keyword</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseDependencyKeyword(DependencyKeyword object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Dependency Record</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Dependency Record</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseDependencyRecord(DependencyRecord object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Dependency Record Item</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Dependency Record Item</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseDependencyRecordItem(DependencyRecordItem object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Target Spec Field</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Target Spec Field</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseTargetSpecField(TargetSpecField object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Reference Record</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Reference Record</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseReferenceRecord(ReferenceRecord object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Reference Record Item</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Reference Record Item</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseReferenceRecordItem(ReferenceRecordItem object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Title Field</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Title Field</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseTitleField(TitleField object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Type Field</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Type Field</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseTypeField(TypeField object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Citation Field</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Citation Field</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseCitationField(CitationField object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Locator Field</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Locator Field</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseLocatorField(LocatorField object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Authority Notes Field</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Authority Notes Field</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseAuthorityNotesField(AuthorityNotesField object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Metadata Text Field</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Metadata Text Field</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseMetadataTextField(MetadataTextField object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Prose Record</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Prose Record</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseProseRecord(ProseRecord object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Section Context Record</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Section Context Record</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseSectionContextRecord(SectionContextRecord object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Section Context Record Item</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Section Context Record Item</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseSectionContextRecordItem(SectionContextRecordItem object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Subsection Context Record</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Subsection Context Record</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseSubsectionContextRecord(SubsectionContextRecord object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Subsection Context Record Item</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Subsection Context Record Item</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseSubsectionContextRecordItem(SubsectionContextRecordItem object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Out Of Scope Record</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Out Of Scope Record</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseOutOfScopeRecord(OutOfScopeRecord object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Out Of Scope Record Item</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Out Of Scope Record Item</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseOutOfScopeRecordItem(OutOfScopeRecordItem object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Statement Field</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Statement Field</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseStatementField(StatementField object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Behavior Record</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Behavior Record</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseBehaviorRecord(BehaviorRecord object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Behavior Record Item</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Behavior Record Item</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseBehaviorRecordItem(BehaviorRecordItem object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Actor Field</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Actor Field</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseActorField(ActorField object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Action Field</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Action Field</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseActionField(ActionField object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Objects Field</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Objects Field</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseObjectsField(ObjectsField object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Reads Field</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Reads Field</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseReadsField(ReadsField object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Writes Field</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Writes Field</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseWritesField(WritesField object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Conditions Field</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Conditions Field</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseConditionsField(ConditionsField object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Outcomes Field</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Outcomes Field</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseOutcomesField(OutcomesField object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Label Field</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Label Field</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseLabelField(LabelField object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>References Field</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>References Field</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseReferencesField(ReferencesField object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Dependencies Field</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Dependencies Field</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseDependenciesField(DependenciesField object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Notes Field</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Notes Field</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseNotesField(NotesField object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Context Field</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Context Field</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseContextField(ContextField object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Operation Surface Record</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Operation Surface Record</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseOperationSurfaceRecord(OperationSurfaceRecord object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Operation Surface Record Item</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Operation Surface Record Item</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseOperationSurfaceRecordItem(OperationSurfaceRecordItem object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Operation Expression Field</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Operation Expression Field</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseOperationExpressionField(OperationExpressionField object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Outcome Class Field</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Outcome Class Field</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseOutcomeClassField(OutcomeClassField object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Implements Surface Record</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Implements Surface Record</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseImplementsSurfaceRecord(ImplementsSurfaceRecord object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Implements Surface Record Item</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Implements Surface Record Item</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseImplementsSurfaceRecordItem(ImplementsSurfaceRecordItem object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Implements Surface Target Field</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Implements Surface Target Field</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseImplementsSurfaceTargetField(ImplementsSurfaceTargetField object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Boundary Record</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Boundary Record</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseBoundaryRecord(BoundaryRecord object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Boundary Record Item</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Boundary Record Item</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseBoundaryRecordItem(BoundaryRecordItem object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Boundary Spec Id Field</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Boundary Spec Id Field</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseBoundarySpecIdField(BoundarySpecIdField object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Boundary Operation Id Field</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Boundary Operation Id Field</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseBoundaryOperationIdField(BoundaryOperationIdField object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Boundary Profile Id Field</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Boundary Profile Id Field</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseBoundaryProfileIdField(BoundaryProfileIdField object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Boundary Raw Field</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Boundary Raw Field</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseBoundaryRawField(BoundaryRawField object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Acceptance Test Record</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Acceptance Test Record</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseAcceptanceTestRecord(AcceptanceTestRecord object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Acceptance Test Record Item</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Acceptance Test Record Item</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseAcceptanceTestRecordItem(AcceptanceTestRecordItem object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Validates Field</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Validates Field</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseValidatesField(ValidatesField object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Preconditions Field</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Preconditions Field</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T casePreconditionsField(PreconditionsField object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Actions Field</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Actions Field</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseActionsField(ActionsField object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Assertions Field</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Assertions Field</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseAssertionsField(AssertionsField object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Implementation Directive Record</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Implementation Directive Record</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseImplementationDirectiveRecord(ImplementationDirectiveRecord object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Implementation Directive Record Item</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Implementation Directive Record Item</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseImplementationDirectiveRecordItem(ImplementationDirectiveRecordItem object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Applies To Field</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Applies To Field</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseAppliesToField(AppliesToField object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Strength Field</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Strength Field</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseStrengthField(StrengthField object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Directive Field</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Directive Field</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseDirectiveField(DirectiveField object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Category Field</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Category Field</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseCategoryField(CategoryField object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Constraints Field</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Constraints Field</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseConstraintsField(ConstraintsField object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Allowed Flexibility Field</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Allowed Flexibility Field</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseAllowedFlexibilityField(AllowedFlexibilityField object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Rationale Field</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Rationale Field</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseRationaleField(RationaleField object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Source Block</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Source Block</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseSourceBlock(SourceBlock object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Source Block Item</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Source Block Item</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseSourceBlockItem(SourceBlockItem object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Section Field</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Section Field</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseSectionField(SectionField object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Subsection Field</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Subsection Field</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseSubsectionField(SubsectionField object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Text Field</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Text Field</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseTextField(TextField object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Identifier List</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Identifier List</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseIdentifierList(IdentifierList object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Behavior Id List</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Behavior Id List</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseBehaviorIdList(BehaviorIdList object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Reference Id List</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Reference Id List</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseReferenceIdList(ReferenceIdList object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Text List</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Text List</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseTextList(TextList object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Text Value</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Text Value</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseTextValue(TextValue object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Identifier Value</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Identifier Value</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseIdentifierValue(IdentifierValue object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Dotted Identifier</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Dotted Identifier</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseDottedIdentifier(DottedIdentifier object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Metadata Section</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Metadata Section</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseMetadataSection(MetadataSection object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Dependencies Section</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Dependencies Section</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseDependenciesSection(DependenciesSection object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>References Section</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>References Section</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseReferencesSection(ReferencesSection object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Prose Section</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Prose Section</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseProseSection(ProseSection object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Out Of Scope Section</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Out Of Scope Section</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseOutOfScopeSection(OutOfScopeSection object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Operation Surface Section</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Operation Surface Section</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseOperationSurfaceSection(OperationSurfaceSection object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Implements Surface Section</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Implements Surface Section</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseImplementsSurfaceSection(ImplementsSurfaceSection object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Boundary Exports Section</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Boundary Exports Section</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseBoundaryExportsSection(BoundaryExportsSection object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Boundary Imports Section</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Boundary Imports Section</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseBoundaryImportsSection(BoundaryImportsSection object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Behaviors Section</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Behaviors Section</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseBehaviorsSection(BehaviorsSection object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Acceptance Tests Section</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Acceptance Tests Section</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseAcceptanceTestsSection(AcceptanceTestsSection object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Implementation Directives Section</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Implementation Directives Section</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseImplementationDirectivesSection(ImplementationDirectivesSection object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>EObject</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch, but this is the last case anyway.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>EObject</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject)
   * @generated
   */
  @Override
  public T defaultCase(EObject object)
  {
    return null;
  }

} //LibrettoSpecSwitch
