/**
 * generated by Xtext 2.40.0
 */
package com.robenglander.libretto.spec.librettoSpec.impl;

import com.robenglander.libretto.spec.librettoSpec.ContextField;
import com.robenglander.libretto.spec.librettoSpec.DependencyRecordItem;
import com.robenglander.libretto.spec.librettoSpec.KindField;
import com.robenglander.libretto.spec.librettoSpec.LibrettoSpecPackage;
import com.robenglander.libretto.spec.librettoSpec.NotesField;
import com.robenglander.libretto.spec.librettoSpec.TargetSpecField;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Dependency Record Item</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link com.robenglander.libretto.spec.librettoSpec.impl.DependencyRecordItemImpl#getTargetSpec <em>Target Spec</em>}</li>
 *   <li>{@link com.robenglander.libretto.spec.librettoSpec.impl.DependencyRecordItemImpl#getKind <em>Kind</em>}</li>
 *   <li>{@link com.robenglander.libretto.spec.librettoSpec.impl.DependencyRecordItemImpl#getNotes <em>Notes</em>}</li>
 *   <li>{@link com.robenglander.libretto.spec.librettoSpec.impl.DependencyRecordItemImpl#getContext <em>Context</em>}</li>
 * </ul>
 *
 * @generated
 */
public class DependencyRecordItemImpl extends MinimalEObjectImpl.Container implements DependencyRecordItem
{
  /**
   * The cached value of the '{@link #getTargetSpec() <em>Target Spec</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTargetSpec()
   * @generated
   * @ordered
   */
  protected TargetSpecField targetSpec;

  /**
   * The cached value of the '{@link #getKind() <em>Kind</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getKind()
   * @generated
   * @ordered
   */
  protected KindField kind;

  /**
   * The cached value of the '{@link #getNotes() <em>Notes</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getNotes()
   * @generated
   * @ordered
   */
  protected NotesField notes;

  /**
   * The cached value of the '{@link #getContext() <em>Context</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getContext()
   * @generated
   * @ordered
   */
  protected ContextField context;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected DependencyRecordItemImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return LibrettoSpecPackage.Literals.DEPENDENCY_RECORD_ITEM;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public TargetSpecField getTargetSpec()
  {
    return targetSpec;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetTargetSpec(TargetSpecField newTargetSpec, NotificationChain msgs)
  {
    TargetSpecField oldTargetSpec = targetSpec;
    targetSpec = newTargetSpec;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, LibrettoSpecPackage.DEPENDENCY_RECORD_ITEM__TARGET_SPEC, oldTargetSpec, newTargetSpec);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setTargetSpec(TargetSpecField newTargetSpec)
  {
    if (newTargetSpec != targetSpec)
    {
      NotificationChain msgs = null;
      if (targetSpec != null)
        msgs = ((InternalEObject)targetSpec).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - LibrettoSpecPackage.DEPENDENCY_RECORD_ITEM__TARGET_SPEC, null, msgs);
      if (newTargetSpec != null)
        msgs = ((InternalEObject)newTargetSpec).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - LibrettoSpecPackage.DEPENDENCY_RECORD_ITEM__TARGET_SPEC, null, msgs);
      msgs = basicSetTargetSpec(newTargetSpec, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, LibrettoSpecPackage.DEPENDENCY_RECORD_ITEM__TARGET_SPEC, newTargetSpec, newTargetSpec));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public KindField getKind()
  {
    return kind;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetKind(KindField newKind, NotificationChain msgs)
  {
    KindField oldKind = kind;
    kind = newKind;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, LibrettoSpecPackage.DEPENDENCY_RECORD_ITEM__KIND, oldKind, newKind);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setKind(KindField newKind)
  {
    if (newKind != kind)
    {
      NotificationChain msgs = null;
      if (kind != null)
        msgs = ((InternalEObject)kind).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - LibrettoSpecPackage.DEPENDENCY_RECORD_ITEM__KIND, null, msgs);
      if (newKind != null)
        msgs = ((InternalEObject)newKind).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - LibrettoSpecPackage.DEPENDENCY_RECORD_ITEM__KIND, null, msgs);
      msgs = basicSetKind(newKind, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, LibrettoSpecPackage.DEPENDENCY_RECORD_ITEM__KIND, newKind, newKind));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotesField getNotes()
  {
    return notes;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetNotes(NotesField newNotes, NotificationChain msgs)
  {
    NotesField oldNotes = notes;
    notes = newNotes;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, LibrettoSpecPackage.DEPENDENCY_RECORD_ITEM__NOTES, oldNotes, newNotes);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setNotes(NotesField newNotes)
  {
    if (newNotes != notes)
    {
      NotificationChain msgs = null;
      if (notes != null)
        msgs = ((InternalEObject)notes).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - LibrettoSpecPackage.DEPENDENCY_RECORD_ITEM__NOTES, null, msgs);
      if (newNotes != null)
        msgs = ((InternalEObject)newNotes).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - LibrettoSpecPackage.DEPENDENCY_RECORD_ITEM__NOTES, null, msgs);
      msgs = basicSetNotes(newNotes, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, LibrettoSpecPackage.DEPENDENCY_RECORD_ITEM__NOTES, newNotes, newNotes));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public ContextField getContext()
  {
    return context;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetContext(ContextField newContext, NotificationChain msgs)
  {
    ContextField oldContext = context;
    context = newContext;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, LibrettoSpecPackage.DEPENDENCY_RECORD_ITEM__CONTEXT, oldContext, newContext);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setContext(ContextField newContext)
  {
    if (newContext != context)
    {
      NotificationChain msgs = null;
      if (context != null)
        msgs = ((InternalEObject)context).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - LibrettoSpecPackage.DEPENDENCY_RECORD_ITEM__CONTEXT, null, msgs);
      if (newContext != null)
        msgs = ((InternalEObject)newContext).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - LibrettoSpecPackage.DEPENDENCY_RECORD_ITEM__CONTEXT, null, msgs);
      msgs = basicSetContext(newContext, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, LibrettoSpecPackage.DEPENDENCY_RECORD_ITEM__CONTEXT, newContext, newContext));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case LibrettoSpecPackage.DEPENDENCY_RECORD_ITEM__TARGET_SPEC:
        return basicSetTargetSpec(null, msgs);
      case LibrettoSpecPackage.DEPENDENCY_RECORD_ITEM__KIND:
        return basicSetKind(null, msgs);
      case LibrettoSpecPackage.DEPENDENCY_RECORD_ITEM__NOTES:
        return basicSetNotes(null, msgs);
      case LibrettoSpecPackage.DEPENDENCY_RECORD_ITEM__CONTEXT:
        return basicSetContext(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case LibrettoSpecPackage.DEPENDENCY_RECORD_ITEM__TARGET_SPEC:
        return getTargetSpec();
      case LibrettoSpecPackage.DEPENDENCY_RECORD_ITEM__KIND:
        return getKind();
      case LibrettoSpecPackage.DEPENDENCY_RECORD_ITEM__NOTES:
        return getNotes();
      case LibrettoSpecPackage.DEPENDENCY_RECORD_ITEM__CONTEXT:
        return getContext();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case LibrettoSpecPackage.DEPENDENCY_RECORD_ITEM__TARGET_SPEC:
        setTargetSpec((TargetSpecField)newValue);
        return;
      case LibrettoSpecPackage.DEPENDENCY_RECORD_ITEM__KIND:
        setKind((KindField)newValue);
        return;
      case LibrettoSpecPackage.DEPENDENCY_RECORD_ITEM__NOTES:
        setNotes((NotesField)newValue);
        return;
      case LibrettoSpecPackage.DEPENDENCY_RECORD_ITEM__CONTEXT:
        setContext((ContextField)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case LibrettoSpecPackage.DEPENDENCY_RECORD_ITEM__TARGET_SPEC:
        setTargetSpec((TargetSpecField)null);
        return;
      case LibrettoSpecPackage.DEPENDENCY_RECORD_ITEM__KIND:
        setKind((KindField)null);
        return;
      case LibrettoSpecPackage.DEPENDENCY_RECORD_ITEM__NOTES:
        setNotes((NotesField)null);
        return;
      case LibrettoSpecPackage.DEPENDENCY_RECORD_ITEM__CONTEXT:
        setContext((ContextField)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case LibrettoSpecPackage.DEPENDENCY_RECORD_ITEM__TARGET_SPEC:
        return targetSpec != null;
      case LibrettoSpecPackage.DEPENDENCY_RECORD_ITEM__KIND:
        return kind != null;
      case LibrettoSpecPackage.DEPENDENCY_RECORD_ITEM__NOTES:
        return notes != null;
      case LibrettoSpecPackage.DEPENDENCY_RECORD_ITEM__CONTEXT:
        return context != null;
    }
    return super.eIsSet(featureID);
  }

} //DependencyRecordItemImpl
