/**
 * generated by Xtext 2.40.0
 */
package com.robenglander.libretto.spec.librettoSpec.impl;

import com.robenglander.libretto.spec.librettoSpec.AllowedFlexibilityField;
import com.robenglander.libretto.spec.librettoSpec.AppliesToField;
import com.robenglander.libretto.spec.librettoSpec.CategoryField;
import com.robenglander.libretto.spec.librettoSpec.ConstraintsField;
import com.robenglander.libretto.spec.librettoSpec.ContextField;
import com.robenglander.libretto.spec.librettoSpec.DirectiveField;
import com.robenglander.libretto.spec.librettoSpec.ImplementationDirectiveRecordItem;
import com.robenglander.libretto.spec.librettoSpec.LibrettoSpecPackage;
import com.robenglander.libretto.spec.librettoSpec.RationaleField;
import com.robenglander.libretto.spec.librettoSpec.ReferencesField;
import com.robenglander.libretto.spec.librettoSpec.SourceBlock;
import com.robenglander.libretto.spec.librettoSpec.StrengthField;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Implementation Directive Record Item</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link com.robenglander.libretto.spec.librettoSpec.impl.ImplementationDirectiveRecordItemImpl#getSource <em>Source</em>}</li>
 *   <li>{@link com.robenglander.libretto.spec.librettoSpec.impl.ImplementationDirectiveRecordItemImpl#getAppliesTo <em>Applies To</em>}</li>
 *   <li>{@link com.robenglander.libretto.spec.librettoSpec.impl.ImplementationDirectiveRecordItemImpl#getStrength <em>Strength</em>}</li>
 *   <li>{@link com.robenglander.libretto.spec.librettoSpec.impl.ImplementationDirectiveRecordItemImpl#getDirective <em>Directive</em>}</li>
 *   <li>{@link com.robenglander.libretto.spec.librettoSpec.impl.ImplementationDirectiveRecordItemImpl#getCategory <em>Category</em>}</li>
 *   <li>{@link com.robenglander.libretto.spec.librettoSpec.impl.ImplementationDirectiveRecordItemImpl#getConstraints <em>Constraints</em>}</li>
 *   <li>{@link com.robenglander.libretto.spec.librettoSpec.impl.ImplementationDirectiveRecordItemImpl#getAllowedFlexibility <em>Allowed Flexibility</em>}</li>
 *   <li>{@link com.robenglander.libretto.spec.librettoSpec.impl.ImplementationDirectiveRecordItemImpl#getReferences <em>References</em>}</li>
 *   <li>{@link com.robenglander.libretto.spec.librettoSpec.impl.ImplementationDirectiveRecordItemImpl#getRationale <em>Rationale</em>}</li>
 *   <li>{@link com.robenglander.libretto.spec.librettoSpec.impl.ImplementationDirectiveRecordItemImpl#getContext <em>Context</em>}</li>
 * </ul>
 *
 * @generated
 */
public class ImplementationDirectiveRecordItemImpl extends MinimalEObjectImpl.Container implements ImplementationDirectiveRecordItem
{
  /**
   * The cached value of the '{@link #getSource() <em>Source</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSource()
   * @generated
   * @ordered
   */
  protected SourceBlock source;

  /**
   * The cached value of the '{@link #getAppliesTo() <em>Applies To</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getAppliesTo()
   * @generated
   * @ordered
   */
  protected AppliesToField appliesTo;

  /**
   * The cached value of the '{@link #getStrength() <em>Strength</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getStrength()
   * @generated
   * @ordered
   */
  protected StrengthField strength;

  /**
   * The cached value of the '{@link #getDirective() <em>Directive</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDirective()
   * @generated
   * @ordered
   */
  protected DirectiveField directive;

  /**
   * The cached value of the '{@link #getCategory() <em>Category</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getCategory()
   * @generated
   * @ordered
   */
  protected CategoryField category;

  /**
   * The cached value of the '{@link #getConstraints() <em>Constraints</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getConstraints()
   * @generated
   * @ordered
   */
  protected ConstraintsField constraints;

  /**
   * The cached value of the '{@link #getAllowedFlexibility() <em>Allowed Flexibility</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getAllowedFlexibility()
   * @generated
   * @ordered
   */
  protected AllowedFlexibilityField allowedFlexibility;

  /**
   * The cached value of the '{@link #getReferences() <em>References</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getReferences()
   * @generated
   * @ordered
   */
  protected ReferencesField references;

  /**
   * The cached value of the '{@link #getRationale() <em>Rationale</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getRationale()
   * @generated
   * @ordered
   */
  protected RationaleField rationale;

  /**
   * The cached value of the '{@link #getContext() <em>Context</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getContext()
   * @generated
   * @ordered
   */
  protected ContextField context;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ImplementationDirectiveRecordItemImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return LibrettoSpecPackage.Literals.IMPLEMENTATION_DIRECTIVE_RECORD_ITEM;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public SourceBlock getSource()
  {
    return source;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetSource(SourceBlock newSource, NotificationChain msgs)
  {
    SourceBlock oldSource = source;
    source = newSource;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, LibrettoSpecPackage.IMPLEMENTATION_DIRECTIVE_RECORD_ITEM__SOURCE, oldSource, newSource);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setSource(SourceBlock newSource)
  {
    if (newSource != source)
    {
      NotificationChain msgs = null;
      if (source != null)
        msgs = ((InternalEObject)source).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - LibrettoSpecPackage.IMPLEMENTATION_DIRECTIVE_RECORD_ITEM__SOURCE, null, msgs);
      if (newSource != null)
        msgs = ((InternalEObject)newSource).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - LibrettoSpecPackage.IMPLEMENTATION_DIRECTIVE_RECORD_ITEM__SOURCE, null, msgs);
      msgs = basicSetSource(newSource, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, LibrettoSpecPackage.IMPLEMENTATION_DIRECTIVE_RECORD_ITEM__SOURCE, newSource, newSource));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public AppliesToField getAppliesTo()
  {
    return appliesTo;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetAppliesTo(AppliesToField newAppliesTo, NotificationChain msgs)
  {
    AppliesToField oldAppliesTo = appliesTo;
    appliesTo = newAppliesTo;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, LibrettoSpecPackage.IMPLEMENTATION_DIRECTIVE_RECORD_ITEM__APPLIES_TO, oldAppliesTo, newAppliesTo);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setAppliesTo(AppliesToField newAppliesTo)
  {
    if (newAppliesTo != appliesTo)
    {
      NotificationChain msgs = null;
      if (appliesTo != null)
        msgs = ((InternalEObject)appliesTo).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - LibrettoSpecPackage.IMPLEMENTATION_DIRECTIVE_RECORD_ITEM__APPLIES_TO, null, msgs);
      if (newAppliesTo != null)
        msgs = ((InternalEObject)newAppliesTo).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - LibrettoSpecPackage.IMPLEMENTATION_DIRECTIVE_RECORD_ITEM__APPLIES_TO, null, msgs);
      msgs = basicSetAppliesTo(newAppliesTo, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, LibrettoSpecPackage.IMPLEMENTATION_DIRECTIVE_RECORD_ITEM__APPLIES_TO, newAppliesTo, newAppliesTo));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public StrengthField getStrength()
  {
    return strength;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetStrength(StrengthField newStrength, NotificationChain msgs)
  {
    StrengthField oldStrength = strength;
    strength = newStrength;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, LibrettoSpecPackage.IMPLEMENTATION_DIRECTIVE_RECORD_ITEM__STRENGTH, oldStrength, newStrength);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setStrength(StrengthField newStrength)
  {
    if (newStrength != strength)
    {
      NotificationChain msgs = null;
      if (strength != null)
        msgs = ((InternalEObject)strength).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - LibrettoSpecPackage.IMPLEMENTATION_DIRECTIVE_RECORD_ITEM__STRENGTH, null, msgs);
      if (newStrength != null)
        msgs = ((InternalEObject)newStrength).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - LibrettoSpecPackage.IMPLEMENTATION_DIRECTIVE_RECORD_ITEM__STRENGTH, null, msgs);
      msgs = basicSetStrength(newStrength, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, LibrettoSpecPackage.IMPLEMENTATION_DIRECTIVE_RECORD_ITEM__STRENGTH, newStrength, newStrength));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public DirectiveField getDirective()
  {
    return directive;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetDirective(DirectiveField newDirective, NotificationChain msgs)
  {
    DirectiveField oldDirective = directive;
    directive = newDirective;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, LibrettoSpecPackage.IMPLEMENTATION_DIRECTIVE_RECORD_ITEM__DIRECTIVE, oldDirective, newDirective);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setDirective(DirectiveField newDirective)
  {
    if (newDirective != directive)
    {
      NotificationChain msgs = null;
      if (directive != null)
        msgs = ((InternalEObject)directive).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - LibrettoSpecPackage.IMPLEMENTATION_DIRECTIVE_RECORD_ITEM__DIRECTIVE, null, msgs);
      if (newDirective != null)
        msgs = ((InternalEObject)newDirective).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - LibrettoSpecPackage.IMPLEMENTATION_DIRECTIVE_RECORD_ITEM__DIRECTIVE, null, msgs);
      msgs = basicSetDirective(newDirective, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, LibrettoSpecPackage.IMPLEMENTATION_DIRECTIVE_RECORD_ITEM__DIRECTIVE, newDirective, newDirective));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public CategoryField getCategory()
  {
    return category;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetCategory(CategoryField newCategory, NotificationChain msgs)
  {
    CategoryField oldCategory = category;
    category = newCategory;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, LibrettoSpecPackage.IMPLEMENTATION_DIRECTIVE_RECORD_ITEM__CATEGORY, oldCategory, newCategory);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setCategory(CategoryField newCategory)
  {
    if (newCategory != category)
    {
      NotificationChain msgs = null;
      if (category != null)
        msgs = ((InternalEObject)category).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - LibrettoSpecPackage.IMPLEMENTATION_DIRECTIVE_RECORD_ITEM__CATEGORY, null, msgs);
      if (newCategory != null)
        msgs = ((InternalEObject)newCategory).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - LibrettoSpecPackage.IMPLEMENTATION_DIRECTIVE_RECORD_ITEM__CATEGORY, null, msgs);
      msgs = basicSetCategory(newCategory, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, LibrettoSpecPackage.IMPLEMENTATION_DIRECTIVE_RECORD_ITEM__CATEGORY, newCategory, newCategory));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public ConstraintsField getConstraints()
  {
    return constraints;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetConstraints(ConstraintsField newConstraints, NotificationChain msgs)
  {
    ConstraintsField oldConstraints = constraints;
    constraints = newConstraints;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, LibrettoSpecPackage.IMPLEMENTATION_DIRECTIVE_RECORD_ITEM__CONSTRAINTS, oldConstraints, newConstraints);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setConstraints(ConstraintsField newConstraints)
  {
    if (newConstraints != constraints)
    {
      NotificationChain msgs = null;
      if (constraints != null)
        msgs = ((InternalEObject)constraints).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - LibrettoSpecPackage.IMPLEMENTATION_DIRECTIVE_RECORD_ITEM__CONSTRAINTS, null, msgs);
      if (newConstraints != null)
        msgs = ((InternalEObject)newConstraints).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - LibrettoSpecPackage.IMPLEMENTATION_DIRECTIVE_RECORD_ITEM__CONSTRAINTS, null, msgs);
      msgs = basicSetConstraints(newConstraints, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, LibrettoSpecPackage.IMPLEMENTATION_DIRECTIVE_RECORD_ITEM__CONSTRAINTS, newConstraints, newConstraints));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public AllowedFlexibilityField getAllowedFlexibility()
  {
    return allowedFlexibility;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetAllowedFlexibility(AllowedFlexibilityField newAllowedFlexibility, NotificationChain msgs)
  {
    AllowedFlexibilityField oldAllowedFlexibility = allowedFlexibility;
    allowedFlexibility = newAllowedFlexibility;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, LibrettoSpecPackage.IMPLEMENTATION_DIRECTIVE_RECORD_ITEM__ALLOWED_FLEXIBILITY, oldAllowedFlexibility, newAllowedFlexibility);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setAllowedFlexibility(AllowedFlexibilityField newAllowedFlexibility)
  {
    if (newAllowedFlexibility != allowedFlexibility)
    {
      NotificationChain msgs = null;
      if (allowedFlexibility != null)
        msgs = ((InternalEObject)allowedFlexibility).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - LibrettoSpecPackage.IMPLEMENTATION_DIRECTIVE_RECORD_ITEM__ALLOWED_FLEXIBILITY, null, msgs);
      if (newAllowedFlexibility != null)
        msgs = ((InternalEObject)newAllowedFlexibility).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - LibrettoSpecPackage.IMPLEMENTATION_DIRECTIVE_RECORD_ITEM__ALLOWED_FLEXIBILITY, null, msgs);
      msgs = basicSetAllowedFlexibility(newAllowedFlexibility, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, LibrettoSpecPackage.IMPLEMENTATION_DIRECTIVE_RECORD_ITEM__ALLOWED_FLEXIBILITY, newAllowedFlexibility, newAllowedFlexibility));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public ReferencesField getReferences()
  {
    return references;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetReferences(ReferencesField newReferences, NotificationChain msgs)
  {
    ReferencesField oldReferences = references;
    references = newReferences;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, LibrettoSpecPackage.IMPLEMENTATION_DIRECTIVE_RECORD_ITEM__REFERENCES, oldReferences, newReferences);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setReferences(ReferencesField newReferences)
  {
    if (newReferences != references)
    {
      NotificationChain msgs = null;
      if (references != null)
        msgs = ((InternalEObject)references).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - LibrettoSpecPackage.IMPLEMENTATION_DIRECTIVE_RECORD_ITEM__REFERENCES, null, msgs);
      if (newReferences != null)
        msgs = ((InternalEObject)newReferences).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - LibrettoSpecPackage.IMPLEMENTATION_DIRECTIVE_RECORD_ITEM__REFERENCES, null, msgs);
      msgs = basicSetReferences(newReferences, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, LibrettoSpecPackage.IMPLEMENTATION_DIRECTIVE_RECORD_ITEM__REFERENCES, newReferences, newReferences));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public RationaleField getRationale()
  {
    return rationale;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetRationale(RationaleField newRationale, NotificationChain msgs)
  {
    RationaleField oldRationale = rationale;
    rationale = newRationale;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, LibrettoSpecPackage.IMPLEMENTATION_DIRECTIVE_RECORD_ITEM__RATIONALE, oldRationale, newRationale);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setRationale(RationaleField newRationale)
  {
    if (newRationale != rationale)
    {
      NotificationChain msgs = null;
      if (rationale != null)
        msgs = ((InternalEObject)rationale).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - LibrettoSpecPackage.IMPLEMENTATION_DIRECTIVE_RECORD_ITEM__RATIONALE, null, msgs);
      if (newRationale != null)
        msgs = ((InternalEObject)newRationale).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - LibrettoSpecPackage.IMPLEMENTATION_DIRECTIVE_RECORD_ITEM__RATIONALE, null, msgs);
      msgs = basicSetRationale(newRationale, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, LibrettoSpecPackage.IMPLEMENTATION_DIRECTIVE_RECORD_ITEM__RATIONALE, newRationale, newRationale));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public ContextField getContext()
  {
    return context;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetContext(ContextField newContext, NotificationChain msgs)
  {
    ContextField oldContext = context;
    context = newContext;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, LibrettoSpecPackage.IMPLEMENTATION_DIRECTIVE_RECORD_ITEM__CONTEXT, oldContext, newContext);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setContext(ContextField newContext)
  {
    if (newContext != context)
    {
      NotificationChain msgs = null;
      if (context != null)
        msgs = ((InternalEObject)context).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - LibrettoSpecPackage.IMPLEMENTATION_DIRECTIVE_RECORD_ITEM__CONTEXT, null, msgs);
      if (newContext != null)
        msgs = ((InternalEObject)newContext).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - LibrettoSpecPackage.IMPLEMENTATION_DIRECTIVE_RECORD_ITEM__CONTEXT, null, msgs);
      msgs = basicSetContext(newContext, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, LibrettoSpecPackage.IMPLEMENTATION_DIRECTIVE_RECORD_ITEM__CONTEXT, newContext, newContext));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case LibrettoSpecPackage.IMPLEMENTATION_DIRECTIVE_RECORD_ITEM__SOURCE:
        return basicSetSource(null, msgs);
      case LibrettoSpecPackage.IMPLEMENTATION_DIRECTIVE_RECORD_ITEM__APPLIES_TO:
        return basicSetAppliesTo(null, msgs);
      case LibrettoSpecPackage.IMPLEMENTATION_DIRECTIVE_RECORD_ITEM__STRENGTH:
        return basicSetStrength(null, msgs);
      case LibrettoSpecPackage.IMPLEMENTATION_DIRECTIVE_RECORD_ITEM__DIRECTIVE:
        return basicSetDirective(null, msgs);
      case LibrettoSpecPackage.IMPLEMENTATION_DIRECTIVE_RECORD_ITEM__CATEGORY:
        return basicSetCategory(null, msgs);
      case LibrettoSpecPackage.IMPLEMENTATION_DIRECTIVE_RECORD_ITEM__CONSTRAINTS:
        return basicSetConstraints(null, msgs);
      case LibrettoSpecPackage.IMPLEMENTATION_DIRECTIVE_RECORD_ITEM__ALLOWED_FLEXIBILITY:
        return basicSetAllowedFlexibility(null, msgs);
      case LibrettoSpecPackage.IMPLEMENTATION_DIRECTIVE_RECORD_ITEM__REFERENCES:
        return basicSetReferences(null, msgs);
      case LibrettoSpecPackage.IMPLEMENTATION_DIRECTIVE_RECORD_ITEM__RATIONALE:
        return basicSetRationale(null, msgs);
      case LibrettoSpecPackage.IMPLEMENTATION_DIRECTIVE_RECORD_ITEM__CONTEXT:
        return basicSetContext(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case LibrettoSpecPackage.IMPLEMENTATION_DIRECTIVE_RECORD_ITEM__SOURCE:
        return getSource();
      case LibrettoSpecPackage.IMPLEMENTATION_DIRECTIVE_RECORD_ITEM__APPLIES_TO:
        return getAppliesTo();
      case LibrettoSpecPackage.IMPLEMENTATION_DIRECTIVE_RECORD_ITEM__STRENGTH:
        return getStrength();
      case LibrettoSpecPackage.IMPLEMENTATION_DIRECTIVE_RECORD_ITEM__DIRECTIVE:
        return getDirective();
      case LibrettoSpecPackage.IMPLEMENTATION_DIRECTIVE_RECORD_ITEM__CATEGORY:
        return getCategory();
      case LibrettoSpecPackage.IMPLEMENTATION_DIRECTIVE_RECORD_ITEM__CONSTRAINTS:
        return getConstraints();
      case LibrettoSpecPackage.IMPLEMENTATION_DIRECTIVE_RECORD_ITEM__ALLOWED_FLEXIBILITY:
        return getAllowedFlexibility();
      case LibrettoSpecPackage.IMPLEMENTATION_DIRECTIVE_RECORD_ITEM__REFERENCES:
        return getReferences();
      case LibrettoSpecPackage.IMPLEMENTATION_DIRECTIVE_RECORD_ITEM__RATIONALE:
        return getRationale();
      case LibrettoSpecPackage.IMPLEMENTATION_DIRECTIVE_RECORD_ITEM__CONTEXT:
        return getContext();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case LibrettoSpecPackage.IMPLEMENTATION_DIRECTIVE_RECORD_ITEM__SOURCE:
        setSource((SourceBlock)newValue);
        return;
      case LibrettoSpecPackage.IMPLEMENTATION_DIRECTIVE_RECORD_ITEM__APPLIES_TO:
        setAppliesTo((AppliesToField)newValue);
        return;
      case LibrettoSpecPackage.IMPLEMENTATION_DIRECTIVE_RECORD_ITEM__STRENGTH:
        setStrength((StrengthField)newValue);
        return;
      case LibrettoSpecPackage.IMPLEMENTATION_DIRECTIVE_RECORD_ITEM__DIRECTIVE:
        setDirective((DirectiveField)newValue);
        return;
      case LibrettoSpecPackage.IMPLEMENTATION_DIRECTIVE_RECORD_ITEM__CATEGORY:
        setCategory((CategoryField)newValue);
        return;
      case LibrettoSpecPackage.IMPLEMENTATION_DIRECTIVE_RECORD_ITEM__CONSTRAINTS:
        setConstraints((ConstraintsField)newValue);
        return;
      case LibrettoSpecPackage.IMPLEMENTATION_DIRECTIVE_RECORD_ITEM__ALLOWED_FLEXIBILITY:
        setAllowedFlexibility((AllowedFlexibilityField)newValue);
        return;
      case LibrettoSpecPackage.IMPLEMENTATION_DIRECTIVE_RECORD_ITEM__REFERENCES:
        setReferences((ReferencesField)newValue);
        return;
      case LibrettoSpecPackage.IMPLEMENTATION_DIRECTIVE_RECORD_ITEM__RATIONALE:
        setRationale((RationaleField)newValue);
        return;
      case LibrettoSpecPackage.IMPLEMENTATION_DIRECTIVE_RECORD_ITEM__CONTEXT:
        setContext((ContextField)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case LibrettoSpecPackage.IMPLEMENTATION_DIRECTIVE_RECORD_ITEM__SOURCE:
        setSource((SourceBlock)null);
        return;
      case LibrettoSpecPackage.IMPLEMENTATION_DIRECTIVE_RECORD_ITEM__APPLIES_TO:
        setAppliesTo((AppliesToField)null);
        return;
      case LibrettoSpecPackage.IMPLEMENTATION_DIRECTIVE_RECORD_ITEM__STRENGTH:
        setStrength((StrengthField)null);
        return;
      case LibrettoSpecPackage.IMPLEMENTATION_DIRECTIVE_RECORD_ITEM__DIRECTIVE:
        setDirective((DirectiveField)null);
        return;
      case LibrettoSpecPackage.IMPLEMENTATION_DIRECTIVE_RECORD_ITEM__CATEGORY:
        setCategory((CategoryField)null);
        return;
      case LibrettoSpecPackage.IMPLEMENTATION_DIRECTIVE_RECORD_ITEM__CONSTRAINTS:
        setConstraints((ConstraintsField)null);
        return;
      case LibrettoSpecPackage.IMPLEMENTATION_DIRECTIVE_RECORD_ITEM__ALLOWED_FLEXIBILITY:
        setAllowedFlexibility((AllowedFlexibilityField)null);
        return;
      case LibrettoSpecPackage.IMPLEMENTATION_DIRECTIVE_RECORD_ITEM__REFERENCES:
        setReferences((ReferencesField)null);
        return;
      case LibrettoSpecPackage.IMPLEMENTATION_DIRECTIVE_RECORD_ITEM__RATIONALE:
        setRationale((RationaleField)null);
        return;
      case LibrettoSpecPackage.IMPLEMENTATION_DIRECTIVE_RECORD_ITEM__CONTEXT:
        setContext((ContextField)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case LibrettoSpecPackage.IMPLEMENTATION_DIRECTIVE_RECORD_ITEM__SOURCE:
        return source != null;
      case LibrettoSpecPackage.IMPLEMENTATION_DIRECTIVE_RECORD_ITEM__APPLIES_TO:
        return appliesTo != null;
      case LibrettoSpecPackage.IMPLEMENTATION_DIRECTIVE_RECORD_ITEM__STRENGTH:
        return strength != null;
      case LibrettoSpecPackage.IMPLEMENTATION_DIRECTIVE_RECORD_ITEM__DIRECTIVE:
        return directive != null;
      case LibrettoSpecPackage.IMPLEMENTATION_DIRECTIVE_RECORD_ITEM__CATEGORY:
        return category != null;
      case LibrettoSpecPackage.IMPLEMENTATION_DIRECTIVE_RECORD_ITEM__CONSTRAINTS:
        return constraints != null;
      case LibrettoSpecPackage.IMPLEMENTATION_DIRECTIVE_RECORD_ITEM__ALLOWED_FLEXIBILITY:
        return allowedFlexibility != null;
      case LibrettoSpecPackage.IMPLEMENTATION_DIRECTIVE_RECORD_ITEM__REFERENCES:
        return references != null;
      case LibrettoSpecPackage.IMPLEMENTATION_DIRECTIVE_RECORD_ITEM__RATIONALE:
        return rationale != null;
      case LibrettoSpecPackage.IMPLEMENTATION_DIRECTIVE_RECORD_ITEM__CONTEXT:
        return context != null;
    }
    return super.eIsSet(featureID);
  }

} //ImplementationDirectiveRecordItemImpl
