/**
 * generated by Xtext 2.40.0
 */
package com.robenglander.libretto.spec.librettoSpec.impl;

import com.robenglander.libretto.spec.librettoSpec.LibrettoSpecPackage;
import com.robenglander.libretto.spec.librettoSpec.OperationExpressionField;
import com.robenglander.libretto.spec.librettoSpec.OperationSurfaceRecordItem;
import com.robenglander.libretto.spec.librettoSpec.OutcomeClassField;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Operation Surface Record Item</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link com.robenglander.libretto.spec.librettoSpec.impl.OperationSurfaceRecordItemImpl#getOperationExpression <em>Operation Expression</em>}</li>
 *   <li>{@link com.robenglander.libretto.spec.librettoSpec.impl.OperationSurfaceRecordItemImpl#getOutcomeClass <em>Outcome Class</em>}</li>
 * </ul>
 *
 * @generated
 */
public class OperationSurfaceRecordItemImpl extends MinimalEObjectImpl.Container implements OperationSurfaceRecordItem
{
  /**
   * The cached value of the '{@link #getOperationExpression() <em>Operation Expression</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getOperationExpression()
   * @generated
   * @ordered
   */
  protected OperationExpressionField operationExpression;

  /**
   * The cached value of the '{@link #getOutcomeClass() <em>Outcome Class</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getOutcomeClass()
   * @generated
   * @ordered
   */
  protected OutcomeClassField outcomeClass;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected OperationSurfaceRecordItemImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return LibrettoSpecPackage.Literals.OPERATION_SURFACE_RECORD_ITEM;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public OperationExpressionField getOperationExpression()
  {
    return operationExpression;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetOperationExpression(OperationExpressionField newOperationExpression, NotificationChain msgs)
  {
    OperationExpressionField oldOperationExpression = operationExpression;
    operationExpression = newOperationExpression;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, LibrettoSpecPackage.OPERATION_SURFACE_RECORD_ITEM__OPERATION_EXPRESSION, oldOperationExpression, newOperationExpression);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setOperationExpression(OperationExpressionField newOperationExpression)
  {
    if (newOperationExpression != operationExpression)
    {
      NotificationChain msgs = null;
      if (operationExpression != null)
        msgs = ((InternalEObject)operationExpression).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - LibrettoSpecPackage.OPERATION_SURFACE_RECORD_ITEM__OPERATION_EXPRESSION, null, msgs);
      if (newOperationExpression != null)
        msgs = ((InternalEObject)newOperationExpression).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - LibrettoSpecPackage.OPERATION_SURFACE_RECORD_ITEM__OPERATION_EXPRESSION, null, msgs);
      msgs = basicSetOperationExpression(newOperationExpression, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, LibrettoSpecPackage.OPERATION_SURFACE_RECORD_ITEM__OPERATION_EXPRESSION, newOperationExpression, newOperationExpression));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public OutcomeClassField getOutcomeClass()
  {
    return outcomeClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetOutcomeClass(OutcomeClassField newOutcomeClass, NotificationChain msgs)
  {
    OutcomeClassField oldOutcomeClass = outcomeClass;
    outcomeClass = newOutcomeClass;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, LibrettoSpecPackage.OPERATION_SURFACE_RECORD_ITEM__OUTCOME_CLASS, oldOutcomeClass, newOutcomeClass);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setOutcomeClass(OutcomeClassField newOutcomeClass)
  {
    if (newOutcomeClass != outcomeClass)
    {
      NotificationChain msgs = null;
      if (outcomeClass != null)
        msgs = ((InternalEObject)outcomeClass).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - LibrettoSpecPackage.OPERATION_SURFACE_RECORD_ITEM__OUTCOME_CLASS, null, msgs);
      if (newOutcomeClass != null)
        msgs = ((InternalEObject)newOutcomeClass).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - LibrettoSpecPackage.OPERATION_SURFACE_RECORD_ITEM__OUTCOME_CLASS, null, msgs);
      msgs = basicSetOutcomeClass(newOutcomeClass, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, LibrettoSpecPackage.OPERATION_SURFACE_RECORD_ITEM__OUTCOME_CLASS, newOutcomeClass, newOutcomeClass));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case LibrettoSpecPackage.OPERATION_SURFACE_RECORD_ITEM__OPERATION_EXPRESSION:
        return basicSetOperationExpression(null, msgs);
      case LibrettoSpecPackage.OPERATION_SURFACE_RECORD_ITEM__OUTCOME_CLASS:
        return basicSetOutcomeClass(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case LibrettoSpecPackage.OPERATION_SURFACE_RECORD_ITEM__OPERATION_EXPRESSION:
        return getOperationExpression();
      case LibrettoSpecPackage.OPERATION_SURFACE_RECORD_ITEM__OUTCOME_CLASS:
        return getOutcomeClass();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case LibrettoSpecPackage.OPERATION_SURFACE_RECORD_ITEM__OPERATION_EXPRESSION:
        setOperationExpression((OperationExpressionField)newValue);
        return;
      case LibrettoSpecPackage.OPERATION_SURFACE_RECORD_ITEM__OUTCOME_CLASS:
        setOutcomeClass((OutcomeClassField)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case LibrettoSpecPackage.OPERATION_SURFACE_RECORD_ITEM__OPERATION_EXPRESSION:
        setOperationExpression((OperationExpressionField)null);
        return;
      case LibrettoSpecPackage.OPERATION_SURFACE_RECORD_ITEM__OUTCOME_CLASS:
        setOutcomeClass((OutcomeClassField)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case LibrettoSpecPackage.OPERATION_SURFACE_RECORD_ITEM__OPERATION_EXPRESSION:
        return operationExpression != null;
      case LibrettoSpecPackage.OPERATION_SURFACE_RECORD_ITEM__OUTCOME_CLASS:
        return outcomeClass != null;
    }
    return super.eIsSet(featureID);
  }

} //OperationSurfaceRecordItemImpl
