/*
 * generated by Xtext 2.40.0
 */
package com.robenglander.libretto.spec.ide.contentassist.antlr;

import com.google.common.collect.ImmutableMap;
import com.google.inject.Inject;
import com.google.inject.Singleton;
import com.robenglander.libretto.spec.ide.contentassist.antlr.internal.InternalLibrettoSpecParser;
import com.robenglander.libretto.spec.services.LibrettoSpecGrammarAccess;
import java.util.Map;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;

public class LibrettoSpecParser extends AbstractContentAssistParser {

	@Singleton
	public static final class NameMappings {
		
		private final Map<AbstractElement, String> mappings;
		
		@Inject
		public NameMappings(LibrettoSpecGrammarAccess grammarAccess) {
			ImmutableMap.Builder<AbstractElement, String> builder = ImmutableMap.builder();
			init(builder, grammarAccess);
			this.mappings = builder.build();
		}
		
		public String getRuleName(AbstractElement element) {
			return mappings.get(element);
		}
		
		private static void init(ImmutableMap.Builder<AbstractElement, String> builder, LibrettoSpecGrammarAccess grammarAccess) {
			builder.put(grammarAccess.getSpecSectionAccess().getAlternatives(), "rule__SpecSection__Alternatives");
			builder.put(grammarAccess.getMetadataFieldAccess().getAlternatives(), "rule__MetadataField__Alternatives");
			builder.put(grammarAccess.getDependencyRecordItemAccess().getAlternatives(), "rule__DependencyRecordItem__Alternatives");
			builder.put(grammarAccess.getReferenceRecordItemAccess().getAlternatives(), "rule__ReferenceRecordItem__Alternatives");
			builder.put(grammarAccess.getProseRecordAccess().getAlternatives(), "rule__ProseRecord__Alternatives");
			builder.put(grammarAccess.getSectionContextRecordItemAccess().getAlternatives(), "rule__SectionContextRecordItem__Alternatives");
			builder.put(grammarAccess.getSubsectionContextRecordItemAccess().getAlternatives(), "rule__SubsectionContextRecordItem__Alternatives");
			builder.put(grammarAccess.getBehaviorRecordItemAccess().getAlternatives(), "rule__BehaviorRecordItem__Alternatives");
			builder.put(grammarAccess.getOperationSurfaceRecordItemAccess().getAlternatives(), "rule__OperationSurfaceRecordItem__Alternatives");
			builder.put(grammarAccess.getBoundaryRecordItemAccess().getAlternatives(), "rule__BoundaryRecordItem__Alternatives");
			builder.put(grammarAccess.getAcceptanceTestRecordItemAccess().getAlternatives(), "rule__AcceptanceTestRecordItem__Alternatives");
			builder.put(grammarAccess.getImplementationDirectiveRecordItemAccess().getAlternatives(), "rule__ImplementationDirectiveRecordItem__Alternatives");
			builder.put(grammarAccess.getSourceBlockItemAccess().getAlternatives(), "rule__SourceBlockItem__Alternatives");
			builder.put(grammarAccess.getTextValueAccess().getAlternatives(), "rule__TextValue__Alternatives");
			builder.put(grammarAccess.getIdentifierValueAccess().getAlternatives(), "rule__IdentifierValue__Alternatives");
			builder.put(grammarAccess.getOutcomeClassValueAccess().getAlternatives(), "rule__OutcomeClassValue__Alternatives");
			builder.put(grammarAccess.getStrengthValueAccess().getAlternatives(), "rule__StrengthValue__Alternatives");
			builder.put(grammarAccess.getSpecAccess().getGroup(), "rule__Spec__Group__0");
			builder.put(grammarAccess.getMetadataSectionAccess().getGroup(), "rule__MetadataSection__Group__0");
			builder.put(grammarAccess.getDependenciesSectionAccess().getGroup(), "rule__DependenciesSection__Group__0");
			builder.put(grammarAccess.getReferencesSectionAccess().getGroup(), "rule__ReferencesSection__Group__0");
			builder.put(grammarAccess.getProseSectionAccess().getGroup(), "rule__ProseSection__Group__0");
			builder.put(grammarAccess.getOutOfScopeSectionAccess().getGroup(), "rule__OutOfScopeSection__Group__0");
			builder.put(grammarAccess.getOperationSurfaceSectionAccess().getGroup(), "rule__OperationSurfaceSection__Group__0");
			builder.put(grammarAccess.getImplementsSurfaceSectionAccess().getGroup(), "rule__ImplementsSurfaceSection__Group__0");
			builder.put(grammarAccess.getBoundaryExportsSectionAccess().getGroup(), "rule__BoundaryExportsSection__Group__0");
			builder.put(grammarAccess.getBoundaryImportsSectionAccess().getGroup(), "rule__BoundaryImportsSection__Group__0");
			builder.put(grammarAccess.getBehaviorsSectionAccess().getGroup(), "rule__BehaviorsSection__Group__0");
			builder.put(grammarAccess.getAcceptanceTestsSectionAccess().getGroup(), "rule__AcceptanceTestsSection__Group__0");
			builder.put(grammarAccess.getImplementationDirectivesSectionAccess().getGroup(), "rule__ImplementationDirectivesSection__Group__0");
			builder.put(grammarAccess.getMetadataFieldAccess().getGroup_0(), "rule__MetadataField__Group_0__0");
			builder.put(grammarAccess.getMetadataFieldAccess().getGroup_1(), "rule__MetadataField__Group_1__0");
			builder.put(grammarAccess.getMetadataFieldAccess().getGroup_2(), "rule__MetadataField__Group_2__0");
			builder.put(grammarAccess.getMetadataFieldAccess().getGroup_3(), "rule__MetadataField__Group_3__0");
			builder.put(grammarAccess.getMetadataFieldAccess().getGroup_4(), "rule__MetadataField__Group_4__0");
			builder.put(grammarAccess.getMetadataFieldAccess().getGroup_5(), "rule__MetadataField__Group_5__0");
			builder.put(grammarAccess.getMetadataFieldAccess().getGroup_6(), "rule__MetadataField__Group_6__0");
			builder.put(grammarAccess.getMetadataFieldAccess().getGroup_7(), "rule__MetadataField__Group_7__0");
			builder.put(grammarAccess.getDependencyRecordAccess().getGroup(), "rule__DependencyRecord__Group__0");
			builder.put(grammarAccess.getTargetSpecFieldAccess().getGroup(), "rule__TargetSpecField__Group__0");
			builder.put(grammarAccess.getKindFieldAccess().getGroup(), "rule__KindField__Group__0");
			builder.put(grammarAccess.getReferenceRecordAccess().getGroup(), "rule__ReferenceRecord__Group__0");
			builder.put(grammarAccess.getTitleFieldAccess().getGroup(), "rule__TitleField__Group__0");
			builder.put(grammarAccess.getTypeFieldAccess().getGroup(), "rule__TypeField__Group__0");
			builder.put(grammarAccess.getCitationFieldAccess().getGroup(), "rule__CitationField__Group__0");
			builder.put(grammarAccess.getLocatorFieldAccess().getGroup(), "rule__LocatorField__Group__0");
			builder.put(grammarAccess.getAuthorityNotesFieldAccess().getGroup(), "rule__AuthorityNotesField__Group__0");
			builder.put(grammarAccess.getMetadataTextFieldAccess().getGroup(), "rule__MetadataTextField__Group__0");
			builder.put(grammarAccess.getSectionContextRecordAccess().getGroup(), "rule__SectionContextRecord__Group__0");
			builder.put(grammarAccess.getSubsectionContextRecordAccess().getGroup(), "rule__SubsectionContextRecord__Group__0");
			builder.put(grammarAccess.getOutOfScopeRecordAccess().getGroup(), "rule__OutOfScopeRecord__Group__0");
			builder.put(grammarAccess.getStatementFieldAccess().getGroup(), "rule__StatementField__Group__0");
			builder.put(grammarAccess.getBehaviorRecordAccess().getGroup(), "rule__BehaviorRecord__Group__0");
			builder.put(grammarAccess.getActorFieldAccess().getGroup(), "rule__ActorField__Group__0");
			builder.put(grammarAccess.getActionFieldAccess().getGroup(), "rule__ActionField__Group__0");
			builder.put(grammarAccess.getObjectsFieldAccess().getGroup(), "rule__ObjectsField__Group__0");
			builder.put(grammarAccess.getReadsFieldAccess().getGroup(), "rule__ReadsField__Group__0");
			builder.put(grammarAccess.getWritesFieldAccess().getGroup(), "rule__WritesField__Group__0");
			builder.put(grammarAccess.getConditionsFieldAccess().getGroup(), "rule__ConditionsField__Group__0");
			builder.put(grammarAccess.getOutcomesFieldAccess().getGroup(), "rule__OutcomesField__Group__0");
			builder.put(grammarAccess.getLabelFieldAccess().getGroup(), "rule__LabelField__Group__0");
			builder.put(grammarAccess.getReferencesFieldAccess().getGroup(), "rule__ReferencesField__Group__0");
			builder.put(grammarAccess.getDependenciesFieldAccess().getGroup(), "rule__DependenciesField__Group__0");
			builder.put(grammarAccess.getNotesFieldAccess().getGroup(), "rule__NotesField__Group__0");
			builder.put(grammarAccess.getContextFieldAccess().getGroup(), "rule__ContextField__Group__0");
			builder.put(grammarAccess.getOperationSurfaceRecordAccess().getGroup(), "rule__OperationSurfaceRecord__Group__0");
			builder.put(grammarAccess.getOperationExpressionFieldAccess().getGroup(), "rule__OperationExpressionField__Group__0");
			builder.put(grammarAccess.getOutcomeClassFieldAccess().getGroup(), "rule__OutcomeClassField__Group__0");
			builder.put(grammarAccess.getImplementsSurfaceRecordAccess().getGroup(), "rule__ImplementsSurfaceRecord__Group__0");
			builder.put(grammarAccess.getImplementsSurfaceTargetFieldAccess().getGroup(), "rule__ImplementsSurfaceTargetField__Group__0");
			builder.put(grammarAccess.getBoundaryRecordAccess().getGroup(), "rule__BoundaryRecord__Group__0");
			builder.put(grammarAccess.getBoundarySpecIdFieldAccess().getGroup(), "rule__BoundarySpecIdField__Group__0");
			builder.put(grammarAccess.getBoundaryOperationIdFieldAccess().getGroup(), "rule__BoundaryOperationIdField__Group__0");
			builder.put(grammarAccess.getBoundaryProfileIdFieldAccess().getGroup(), "rule__BoundaryProfileIdField__Group__0");
			builder.put(grammarAccess.getBoundaryRawFieldAccess().getGroup(), "rule__BoundaryRawField__Group__0");
			builder.put(grammarAccess.getAcceptanceTestRecordAccess().getGroup(), "rule__AcceptanceTestRecord__Group__0");
			builder.put(grammarAccess.getValidatesFieldAccess().getGroup(), "rule__ValidatesField__Group__0");
			builder.put(grammarAccess.getPreconditionsFieldAccess().getGroup(), "rule__PreconditionsField__Group__0");
			builder.put(grammarAccess.getActionsFieldAccess().getGroup(), "rule__ActionsField__Group__0");
			builder.put(grammarAccess.getAssertionsFieldAccess().getGroup(), "rule__AssertionsField__Group__0");
			builder.put(grammarAccess.getImplementationDirectiveRecordAccess().getGroup(), "rule__ImplementationDirectiveRecord__Group__0");
			builder.put(grammarAccess.getAppliesToFieldAccess().getGroup(), "rule__AppliesToField__Group__0");
			builder.put(grammarAccess.getStrengthFieldAccess().getGroup(), "rule__StrengthField__Group__0");
			builder.put(grammarAccess.getDirectiveFieldAccess().getGroup(), "rule__DirectiveField__Group__0");
			builder.put(grammarAccess.getCategoryFieldAccess().getGroup(), "rule__CategoryField__Group__0");
			builder.put(grammarAccess.getConstraintsFieldAccess().getGroup(), "rule__ConstraintsField__Group__0");
			builder.put(grammarAccess.getAllowedFlexibilityFieldAccess().getGroup(), "rule__AllowedFlexibilityField__Group__0");
			builder.put(grammarAccess.getRationaleFieldAccess().getGroup(), "rule__RationaleField__Group__0");
			builder.put(grammarAccess.getSourceBlockAccess().getGroup(), "rule__SourceBlock__Group__0");
			builder.put(grammarAccess.getSectionFieldAccess().getGroup(), "rule__SectionField__Group__0");
			builder.put(grammarAccess.getSubsectionFieldAccess().getGroup(), "rule__SubsectionField__Group__0");
			builder.put(grammarAccess.getTextFieldAccess().getGroup(), "rule__TextField__Group__0");
			builder.put(grammarAccess.getIdentifierListAccess().getGroup(), "rule__IdentifierList__Group__0");
			builder.put(grammarAccess.getIdentifierListAccess().getGroup_2(), "rule__IdentifierList__Group_2__0");
			builder.put(grammarAccess.getIdentifierListAccess().getGroup_2_1(), "rule__IdentifierList__Group_2_1__0");
			builder.put(grammarAccess.getBehaviorIdListAccess().getGroup(), "rule__BehaviorIdList__Group__0");
			builder.put(grammarAccess.getBehaviorIdListAccess().getGroup_2(), "rule__BehaviorIdList__Group_2__0");
			builder.put(grammarAccess.getBehaviorIdListAccess().getGroup_2_1(), "rule__BehaviorIdList__Group_2_1__0");
			builder.put(grammarAccess.getReferenceIdListAccess().getGroup(), "rule__ReferenceIdList__Group__0");
			builder.put(grammarAccess.getReferenceIdListAccess().getGroup_2(), "rule__ReferenceIdList__Group_2__0");
			builder.put(grammarAccess.getReferenceIdListAccess().getGroup_2_1(), "rule__ReferenceIdList__Group_2_1__0");
			builder.put(grammarAccess.getTextListAccess().getGroup(), "rule__TextList__Group__0");
			builder.put(grammarAccess.getTextListAccess().getGroup_2(), "rule__TextList__Group_2__0");
			builder.put(grammarAccess.getTextListAccess().getGroup_2_1(), "rule__TextList__Group_2_1__0");
			builder.put(grammarAccess.getDottedIdentifierAccess().getGroup(), "rule__DottedIdentifier__Group__0");
			builder.put(grammarAccess.getDottedIdentifierAccess().getGroup_1(), "rule__DottedIdentifier__Group_1__0");
			builder.put(grammarAccess.getSpecAccess().getSpecIdAssignment_1(), "rule__Spec__SpecIdAssignment_1");
			builder.put(grammarAccess.getSpecAccess().getSectionsAssignment_3(), "rule__Spec__SectionsAssignment_3");
			builder.put(grammarAccess.getMetadataSectionAccess().getFieldsAssignment_3(), "rule__MetadataSection__FieldsAssignment_3");
			builder.put(grammarAccess.getDependenciesSectionAccess().getRecordsAssignment_3(), "rule__DependenciesSection__RecordsAssignment_3");
			builder.put(grammarAccess.getReferencesSectionAccess().getRecordsAssignment_3(), "rule__ReferencesSection__RecordsAssignment_3");
			builder.put(grammarAccess.getProseSectionAccess().getRecordsAssignment_3(), "rule__ProseSection__RecordsAssignment_3");
			builder.put(grammarAccess.getOutOfScopeSectionAccess().getRecordsAssignment_3(), "rule__OutOfScopeSection__RecordsAssignment_3");
			builder.put(grammarAccess.getOperationSurfaceSectionAccess().getRecordsAssignment_3(), "rule__OperationSurfaceSection__RecordsAssignment_3");
			builder.put(grammarAccess.getImplementsSurfaceSectionAccess().getRecordsAssignment_3(), "rule__ImplementsSurfaceSection__RecordsAssignment_3");
			builder.put(grammarAccess.getBoundaryExportsSectionAccess().getRecordsAssignment_3(), "rule__BoundaryExportsSection__RecordsAssignment_3");
			builder.put(grammarAccess.getBoundaryImportsSectionAccess().getRecordsAssignment_3(), "rule__BoundaryImportsSection__RecordsAssignment_3");
			builder.put(grammarAccess.getBehaviorsSectionAccess().getRecordsAssignment_3(), "rule__BehaviorsSection__RecordsAssignment_3");
			builder.put(grammarAccess.getAcceptanceTestsSectionAccess().getRecordsAssignment_3(), "rule__AcceptanceTestsSection__RecordsAssignment_3");
			builder.put(grammarAccess.getImplementationDirectivesSectionAccess().getRecordsAssignment_3(), "rule__ImplementationDirectivesSection__RecordsAssignment_3");
			builder.put(grammarAccess.getMetadataFieldAccess().getSpecIdAssignment_0_2(), "rule__MetadataField__SpecIdAssignment_0_2");
			builder.put(grammarAccess.getMetadataFieldAccess().getTitleAssignment_1_2(), "rule__MetadataField__TitleAssignment_1_2");
			builder.put(grammarAccess.getMetadataFieldAccess().getVersionAssignment_2_2(), "rule__MetadataField__VersionAssignment_2_2");
			builder.put(grammarAccess.getMetadataFieldAccess().getStatusAssignment_3_2(), "rule__MetadataField__StatusAssignment_3_2");
			builder.put(grammarAccess.getMetadataFieldAccess().getAuthoredSourceAssignment_4_2(), "rule__MetadataField__AuthoredSourceAssignment_4_2");
			builder.put(grammarAccess.getMetadataFieldAccess().getCompiledAtAssignment_5_2(), "rule__MetadataField__CompiledAtAssignment_5_2");
			builder.put(grammarAccess.getMetadataFieldAccess().getCompilerVersionAssignment_6_2(), "rule__MetadataField__CompilerVersionAssignment_6_2");
			builder.put(grammarAccess.getMetadataFieldAccess().getModelMetadataAssignment_7_2(), "rule__MetadataField__ModelMetadataAssignment_7_2");
			builder.put(grammarAccess.getDependencyRecordAccess().getIdAssignment_1(), "rule__DependencyRecord__IdAssignment_1");
			builder.put(grammarAccess.getDependencyRecordAccess().getItemsAssignment_3(), "rule__DependencyRecord__ItemsAssignment_3");
			builder.put(grammarAccess.getDependencyTargetSpecItemAccess().getTargetSpecAssignment(), "rule__DependencyTargetSpecItem__TargetSpecAssignment");
			builder.put(grammarAccess.getDependencyKindItemAccess().getKindAssignment(), "rule__DependencyKindItem__KindAssignment");
			builder.put(grammarAccess.getDependencyNotesItemAccess().getNotesAssignment(), "rule__DependencyNotesItem__NotesAssignment");
			builder.put(grammarAccess.getDependencyContextItemAccess().getContextAssignment(), "rule__DependencyContextItem__ContextAssignment");
			builder.put(grammarAccess.getTargetSpecFieldAccess().getValueAssignment_2(), "rule__TargetSpecField__ValueAssignment_2");
			builder.put(grammarAccess.getKindFieldAccess().getValueAssignment_2(), "rule__KindField__ValueAssignment_2");
			builder.put(grammarAccess.getReferenceRecordAccess().getIdAssignment_1(), "rule__ReferenceRecord__IdAssignment_1");
			builder.put(grammarAccess.getReferenceRecordAccess().getItemsAssignment_3(), "rule__ReferenceRecord__ItemsAssignment_3");
			builder.put(grammarAccess.getReferenceTitleItemAccess().getTitleAssignment(), "rule__ReferenceTitleItem__TitleAssignment");
			builder.put(grammarAccess.getReferenceTypeItemAccess().getTypeAssignment(), "rule__ReferenceTypeItem__TypeAssignment");
			builder.put(grammarAccess.getReferenceCitationItemAccess().getCitationAssignment(), "rule__ReferenceCitationItem__CitationAssignment");
			builder.put(grammarAccess.getReferenceLocatorItemAccess().getLocatorAssignment(), "rule__ReferenceLocatorItem__LocatorAssignment");
			builder.put(grammarAccess.getReferenceAuthorityNotesItemAccess().getAuthorityNotesAssignment(), "rule__ReferenceAuthorityNotesItem__AuthorityNotesAssignment");
			builder.put(grammarAccess.getReferenceMetadataTextItemAccess().getMetadataTextAssignment(), "rule__ReferenceMetadataTextItem__MetadataTextAssignment");
			builder.put(grammarAccess.getReferenceContextItemAccess().getContextAssignment(), "rule__ReferenceContextItem__ContextAssignment");
			builder.put(grammarAccess.getTitleFieldAccess().getValueAssignment_2(), "rule__TitleField__ValueAssignment_2");
			builder.put(grammarAccess.getTypeFieldAccess().getValueAssignment_2(), "rule__TypeField__ValueAssignment_2");
			builder.put(grammarAccess.getCitationFieldAccess().getValueAssignment_2(), "rule__CitationField__ValueAssignment_2");
			builder.put(grammarAccess.getLocatorFieldAccess().getValueAssignment_2(), "rule__LocatorField__ValueAssignment_2");
			builder.put(grammarAccess.getAuthorityNotesFieldAccess().getValueAssignment_2(), "rule__AuthorityNotesField__ValueAssignment_2");
			builder.put(grammarAccess.getMetadataTextFieldAccess().getValueAssignment_2(), "rule__MetadataTextField__ValueAssignment_2");
			builder.put(grammarAccess.getSectionContextRecordAccess().getItemsAssignment_2(), "rule__SectionContextRecord__ItemsAssignment_2");
			builder.put(grammarAccess.getSectionContextSectionItemAccess().getSectionAssignment(), "rule__SectionContextSectionItem__SectionAssignment");
			builder.put(grammarAccess.getSectionContextTextItemAccess().getTextAssignment(), "rule__SectionContextTextItem__TextAssignment");
			builder.put(grammarAccess.getSubsectionContextRecordAccess().getItemsAssignment_2(), "rule__SubsectionContextRecord__ItemsAssignment_2");
			builder.put(grammarAccess.getSubsectionContextSectionItemAccess().getSectionAssignment(), "rule__SubsectionContextSectionItem__SectionAssignment");
			builder.put(grammarAccess.getSubsectionContextSubsectionItemAccess().getSubsectionAssignment(), "rule__SubsectionContextSubsectionItem__SubsectionAssignment");
			builder.put(grammarAccess.getSubsectionContextTextItemAccess().getTextAssignment(), "rule__SubsectionContextTextItem__TextAssignment");
			builder.put(grammarAccess.getOutOfScopeRecordAccess().getIdAssignment_1(), "rule__OutOfScopeRecord__IdAssignment_1");
			builder.put(grammarAccess.getOutOfScopeRecordAccess().getItemsAssignment_3(), "rule__OutOfScopeRecord__ItemsAssignment_3");
			builder.put(grammarAccess.getOutOfScopeStatementItemAccess().getStatementAssignment(), "rule__OutOfScopeStatementItem__StatementAssignment");
			builder.put(grammarAccess.getStatementFieldAccess().getValueAssignment_2(), "rule__StatementField__ValueAssignment_2");
			builder.put(grammarAccess.getBehaviorRecordAccess().getIdAssignment_1(), "rule__BehaviorRecord__IdAssignment_1");
			builder.put(grammarAccess.getBehaviorRecordAccess().getItemsAssignment_3(), "rule__BehaviorRecord__ItemsAssignment_3");
			builder.put(grammarAccess.getBehaviorSourceItemAccess().getSourceAssignment(), "rule__BehaviorSourceItem__SourceAssignment");
			builder.put(grammarAccess.getBehaviorActorItemAccess().getActorAssignment(), "rule__BehaviorActorItem__ActorAssignment");
			builder.put(grammarAccess.getBehaviorActionItemAccess().getActionAssignment(), "rule__BehaviorActionItem__ActionAssignment");
			builder.put(grammarAccess.getBehaviorObjectsItemAccess().getObjectsAssignment(), "rule__BehaviorObjectsItem__ObjectsAssignment");
			builder.put(grammarAccess.getBehaviorReadsItemAccess().getReadsAssignment(), "rule__BehaviorReadsItem__ReadsAssignment");
			builder.put(grammarAccess.getBehaviorWritesItemAccess().getWritesAssignment(), "rule__BehaviorWritesItem__WritesAssignment");
			builder.put(grammarAccess.getBehaviorConditionsItemAccess().getConditionsAssignment(), "rule__BehaviorConditionsItem__ConditionsAssignment");
			builder.put(grammarAccess.getBehaviorOutcomesItemAccess().getOutcomesAssignment(), "rule__BehaviorOutcomesItem__OutcomesAssignment");
			builder.put(grammarAccess.getBehaviorLabelItemAccess().getLabelAssignment(), "rule__BehaviorLabelItem__LabelAssignment");
			builder.put(grammarAccess.getBehaviorReferencesItemAccess().getReferencesAssignment(), "rule__BehaviorReferencesItem__ReferencesAssignment");
			builder.put(grammarAccess.getBehaviorNotesItemAccess().getNotesAssignment(), "rule__BehaviorNotesItem__NotesAssignment");
			builder.put(grammarAccess.getBehaviorContextItemAccess().getContextAssignment(), "rule__BehaviorContextItem__ContextAssignment");
			builder.put(grammarAccess.getBehaviorDependenciesItemAccess().getDependenciesAssignment(), "rule__BehaviorDependenciesItem__DependenciesAssignment");
			builder.put(grammarAccess.getActorFieldAccess().getValueAssignment_2(), "rule__ActorField__ValueAssignment_2");
			builder.put(grammarAccess.getActionFieldAccess().getValueAssignment_2(), "rule__ActionField__ValueAssignment_2");
			builder.put(grammarAccess.getObjectsFieldAccess().getValueAssignment_2(), "rule__ObjectsField__ValueAssignment_2");
			builder.put(grammarAccess.getReadsFieldAccess().getValueAssignment_2(), "rule__ReadsField__ValueAssignment_2");
			builder.put(grammarAccess.getWritesFieldAccess().getValueAssignment_2(), "rule__WritesField__ValueAssignment_2");
			builder.put(grammarAccess.getConditionsFieldAccess().getValueAssignment_2(), "rule__ConditionsField__ValueAssignment_2");
			builder.put(grammarAccess.getOutcomesFieldAccess().getValueAssignment_2(), "rule__OutcomesField__ValueAssignment_2");
			builder.put(grammarAccess.getLabelFieldAccess().getValueAssignment_2(), "rule__LabelField__ValueAssignment_2");
			builder.put(grammarAccess.getReferencesFieldAccess().getValueAssignment_2(), "rule__ReferencesField__ValueAssignment_2");
			builder.put(grammarAccess.getDependenciesFieldAccess().getValueAssignment_2(), "rule__DependenciesField__ValueAssignment_2");
			builder.put(grammarAccess.getNotesFieldAccess().getValueAssignment_2(), "rule__NotesField__ValueAssignment_2");
			builder.put(grammarAccess.getContextFieldAccess().getValueAssignment_2(), "rule__ContextField__ValueAssignment_2");
			builder.put(grammarAccess.getOperationSurfaceRecordAccess().getIdAssignment_1(), "rule__OperationSurfaceRecord__IdAssignment_1");
			builder.put(grammarAccess.getOperationSurfaceRecordAccess().getItemsAssignment_3(), "rule__OperationSurfaceRecord__ItemsAssignment_3");
			builder.put(grammarAccess.getOperationSurfaceExpressionItemAccess().getOperationExpressionAssignment(), "rule__OperationSurfaceExpressionItem__OperationExpressionAssignment");
			builder.put(grammarAccess.getOperationSurfaceOutcomeItemAccess().getOutcomeClassAssignment(), "rule__OperationSurfaceOutcomeItem__OutcomeClassAssignment");
			builder.put(grammarAccess.getOperationExpressionFieldAccess().getValueAssignment_2(), "rule__OperationExpressionField__ValueAssignment_2");
			builder.put(grammarAccess.getOutcomeClassFieldAccess().getValueAssignment_2(), "rule__OutcomeClassField__ValueAssignment_2");
			builder.put(grammarAccess.getImplementsSurfaceRecordAccess().getItemsAssignment_1(), "rule__ImplementsSurfaceRecord__ItemsAssignment_1");
			builder.put(grammarAccess.getImplementsSurfaceTargetItemAccess().getTargetSpecAssignment(), "rule__ImplementsSurfaceTargetItem__TargetSpecAssignment");
			builder.put(grammarAccess.getImplementsSurfaceTargetFieldAccess().getValueAssignment_2(), "rule__ImplementsSurfaceTargetField__ValueAssignment_2");
			builder.put(grammarAccess.getBoundaryRecordAccess().getItemsAssignment_2(), "rule__BoundaryRecord__ItemsAssignment_2");
			builder.put(grammarAccess.getBoundarySpecIdElementAccess().getSpecIdFieldAssignment(), "rule__BoundarySpecIdElement__SpecIdFieldAssignment");
			builder.put(grammarAccess.getBoundaryOperationIdElementAccess().getOperationIdFieldAssignment(), "rule__BoundaryOperationIdElement__OperationIdFieldAssignment");
			builder.put(grammarAccess.getBoundaryProfileIdElementAccess().getProfileIdFieldAssignment(), "rule__BoundaryProfileIdElement__ProfileIdFieldAssignment");
			builder.put(grammarAccess.getBoundaryRawElementAccess().getRawFieldAssignment(), "rule__BoundaryRawElement__RawFieldAssignment");
			builder.put(grammarAccess.getBoundarySpecIdFieldAccess().getValueAssignment_2(), "rule__BoundarySpecIdField__ValueAssignment_2");
			builder.put(grammarAccess.getBoundaryOperationIdFieldAccess().getValueAssignment_2(), "rule__BoundaryOperationIdField__ValueAssignment_2");
			builder.put(grammarAccess.getBoundaryProfileIdFieldAccess().getValueAssignment_2(), "rule__BoundaryProfileIdField__ValueAssignment_2");
			builder.put(grammarAccess.getBoundaryRawFieldAccess().getValueAssignment_2(), "rule__BoundaryRawField__ValueAssignment_2");
			builder.put(grammarAccess.getAcceptanceTestRecordAccess().getIdAssignment_1(), "rule__AcceptanceTestRecord__IdAssignment_1");
			builder.put(grammarAccess.getAcceptanceTestRecordAccess().getItemsAssignment_3(), "rule__AcceptanceTestRecord__ItemsAssignment_3");
			builder.put(grammarAccess.getAcceptanceTestSourceItemAccess().getSourceAssignment(), "rule__AcceptanceTestSourceItem__SourceAssignment");
			builder.put(grammarAccess.getAcceptanceTestValidatesItemAccess().getValidatesAssignment(), "rule__AcceptanceTestValidatesItem__ValidatesAssignment");
			builder.put(grammarAccess.getAcceptanceTestPreconditionsItemAccess().getPreconditionsAssignment(), "rule__AcceptanceTestPreconditionsItem__PreconditionsAssignment");
			builder.put(grammarAccess.getAcceptanceTestActionsItemAccess().getActionsAssignment(), "rule__AcceptanceTestActionsItem__ActionsAssignment");
			builder.put(grammarAccess.getAcceptanceTestAssertionsItemAccess().getAssertionsAssignment(), "rule__AcceptanceTestAssertionsItem__AssertionsAssignment");
			builder.put(grammarAccess.getAcceptanceTestTitleItemAccess().getTitleAssignment(), "rule__AcceptanceTestTitleItem__TitleAssignment");
			builder.put(grammarAccess.getAcceptanceTestReferencesItemAccess().getReferencesAssignment(), "rule__AcceptanceTestReferencesItem__ReferencesAssignment");
			builder.put(grammarAccess.getAcceptanceTestNotesItemAccess().getNotesAssignment(), "rule__AcceptanceTestNotesItem__NotesAssignment");
			builder.put(grammarAccess.getAcceptanceTestContextItemAccess().getContextAssignment(), "rule__AcceptanceTestContextItem__ContextAssignment");
			builder.put(grammarAccess.getValidatesFieldAccess().getValueAssignment_2(), "rule__ValidatesField__ValueAssignment_2");
			builder.put(grammarAccess.getPreconditionsFieldAccess().getValueAssignment_2(), "rule__PreconditionsField__ValueAssignment_2");
			builder.put(grammarAccess.getActionsFieldAccess().getValueAssignment_2(), "rule__ActionsField__ValueAssignment_2");
			builder.put(grammarAccess.getAssertionsFieldAccess().getValueAssignment_2(), "rule__AssertionsField__ValueAssignment_2");
			builder.put(grammarAccess.getImplementationDirectiveRecordAccess().getIdAssignment_1(), "rule__ImplementationDirectiveRecord__IdAssignment_1");
			builder.put(grammarAccess.getImplementationDirectiveRecordAccess().getItemsAssignment_3(), "rule__ImplementationDirectiveRecord__ItemsAssignment_3");
			builder.put(grammarAccess.getImplementationDirectiveSourceItemAccess().getSourceAssignment(), "rule__ImplementationDirectiveSourceItem__SourceAssignment");
			builder.put(grammarAccess.getImplementationDirectiveAppliesToItemAccess().getAppliesToAssignment(), "rule__ImplementationDirectiveAppliesToItem__AppliesToAssignment");
			builder.put(grammarAccess.getImplementationDirectiveStrengthItemAccess().getStrengthAssignment(), "rule__ImplementationDirectiveStrengthItem__StrengthAssignment");
			builder.put(grammarAccess.getImplementationDirectiveDirectiveItemAccess().getDirectiveAssignment(), "rule__ImplementationDirectiveDirectiveItem__DirectiveAssignment");
			builder.put(grammarAccess.getImplementationDirectiveCategoryItemAccess().getCategoryAssignment(), "rule__ImplementationDirectiveCategoryItem__CategoryAssignment");
			builder.put(grammarAccess.getImplementationDirectiveConstraintsItemAccess().getConstraintsAssignment(), "rule__ImplementationDirectiveConstraintsItem__ConstraintsAssignment");
			builder.put(grammarAccess.getImplementationDirectiveAllowedFlexibilityItemAccess().getAllowedFlexibilityAssignment(), "rule__ImplementationDirectiveAllowedFlexibilityItem__AllowedFlexibilityAssignment");
			builder.put(grammarAccess.getImplementationDirectiveReferencesItemAccess().getReferencesAssignment(), "rule__ImplementationDirectiveReferencesItem__ReferencesAssignment");
			builder.put(grammarAccess.getImplementationDirectiveRationaleItemAccess().getRationaleAssignment(), "rule__ImplementationDirectiveRationaleItem__RationaleAssignment");
			builder.put(grammarAccess.getImplementationDirectiveContextItemAccess().getContextAssignment(), "rule__ImplementationDirectiveContextItem__ContextAssignment");
			builder.put(grammarAccess.getAppliesToFieldAccess().getValueAssignment_2(), "rule__AppliesToField__ValueAssignment_2");
			builder.put(grammarAccess.getStrengthFieldAccess().getValueAssignment_2(), "rule__StrengthField__ValueAssignment_2");
			builder.put(grammarAccess.getDirectiveFieldAccess().getValueAssignment_2(), "rule__DirectiveField__ValueAssignment_2");
			builder.put(grammarAccess.getCategoryFieldAccess().getValueAssignment_2(), "rule__CategoryField__ValueAssignment_2");
			builder.put(grammarAccess.getConstraintsFieldAccess().getValueAssignment_2(), "rule__ConstraintsField__ValueAssignment_2");
			builder.put(grammarAccess.getAllowedFlexibilityFieldAccess().getValueAssignment_2(), "rule__AllowedFlexibilityField__ValueAssignment_2");
			builder.put(grammarAccess.getRationaleFieldAccess().getValueAssignment_2(), "rule__RationaleField__ValueAssignment_2");
			builder.put(grammarAccess.getSourceBlockAccess().getItemsAssignment_2(), "rule__SourceBlock__ItemsAssignment_2");
			builder.put(grammarAccess.getSourceBlockSectionItemAccess().getSectionAssignment(), "rule__SourceBlockSectionItem__SectionAssignment");
			builder.put(grammarAccess.getSourceBlockSubsectionItemAccess().getSubsectionAssignment(), "rule__SourceBlockSubsectionItem__SubsectionAssignment");
			builder.put(grammarAccess.getSectionFieldAccess().getValueAssignment_2(), "rule__SectionField__ValueAssignment_2");
			builder.put(grammarAccess.getSubsectionFieldAccess().getValueAssignment_2(), "rule__SubsectionField__ValueAssignment_2");
			builder.put(grammarAccess.getTextFieldAccess().getValueAssignment_2(), "rule__TextField__ValueAssignment_2");
			builder.put(grammarAccess.getIdentifierListAccess().getValuesAssignment_2_0(), "rule__IdentifierList__ValuesAssignment_2_0");
			builder.put(grammarAccess.getIdentifierListAccess().getValuesAssignment_2_1_1(), "rule__IdentifierList__ValuesAssignment_2_1_1");
			builder.put(grammarAccess.getBehaviorIdListAccess().getValuesAssignment_2_0(), "rule__BehaviorIdList__ValuesAssignment_2_0");
			builder.put(grammarAccess.getBehaviorIdListAccess().getValuesAssignment_2_1_1(), "rule__BehaviorIdList__ValuesAssignment_2_1_1");
			builder.put(grammarAccess.getReferenceIdListAccess().getValuesAssignment_2_0(), "rule__ReferenceIdList__ValuesAssignment_2_0");
			builder.put(grammarAccess.getReferenceIdListAccess().getValuesAssignment_2_1_1(), "rule__ReferenceIdList__ValuesAssignment_2_1_1");
			builder.put(grammarAccess.getTextListAccess().getValuesAssignment_2_0(), "rule__TextList__ValuesAssignment_2_0");
			builder.put(grammarAccess.getTextListAccess().getValuesAssignment_2_1_1(), "rule__TextList__ValuesAssignment_2_1_1");
			builder.put(grammarAccess.getDottedIdentifierAccess().getHeadAssignment_0(), "rule__DottedIdentifier__HeadAssignment_0");
			builder.put(grammarAccess.getDottedIdentifierAccess().getTailAssignment_1_1(), "rule__DottedIdentifier__TailAssignment_1_1");
		}
	}
	
	@Inject
	private NameMappings nameMappings;

	@Inject
	private LibrettoSpecGrammarAccess grammarAccess;

	@Override
	protected InternalLibrettoSpecParser createParser() {
		InternalLibrettoSpecParser result = new InternalLibrettoSpecParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		return nameMappings.getRuleName(element);
	}

	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public LibrettoSpecGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(LibrettoSpecGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
	public NameMappings getNameMappings() {
		return nameMappings;
	}
	
	public void setNameMappings(NameMappings nameMappings) {
		this.nameMappings = nameMappings;
	}
}
