/*
 * generated by Xtext 2.40.0
 */
package com.robenglander.libretto.spec;

import com.google.inject.Guice;
import com.google.inject.Injector;
import com.robenglander.libretto.spec.librettoProjectProfile.LibrettoProjectProfilePackage;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.resource.Resource;
import org.eclipse.xtext.ISetup;
import org.eclipse.xtext.common.TerminalsStandaloneSetup;
import org.eclipse.xtext.resource.IResourceFactory;
import org.eclipse.xtext.resource.IResourceServiceProvider;

@SuppressWarnings("all")
public class LibrettoProjectProfileStandaloneSetupGenerated implements ISetup {

	@Override
	public Injector createInjectorAndDoEMFRegistration() {
		TerminalsStandaloneSetup.doSetup();

		Injector injector = createInjector();
		register(injector);
		return injector;
	}
	
	public Injector createInjector() {
		return Guice.createInjector(new LibrettoProjectProfileRuntimeModule());
	}
	
	public void register(Injector injector) {
		if (!EPackage.Registry.INSTANCE.containsKey("http://www.robenglander.com/libretto/spec/LibrettoProjectProfile")) {
			EPackage.Registry.INSTANCE.put("http://www.robenglander.com/libretto/spec/LibrettoProjectProfile", LibrettoProjectProfilePackage.eINSTANCE);
		}
		IResourceFactory resourceFactory = injector.getInstance(IResourceFactory.class);
		IResourceServiceProvider serviceProvider = injector.getInstance(IResourceServiceProvider.class);
		
		Resource.Factory.Registry.INSTANCE.getExtensionToFactoryMap().put("lpp", resourceFactory);
		IResourceServiceProvider.Registry.INSTANCE.getExtensionToFactoryMap().put("lpp", serviceProvider);
	}
}
