/**
 * generated by Xtext 2.40.0
 */
package com.robenglander.libretto.spec.librettoProjectProfile.impl;

import com.robenglander.libretto.spec.librettoProjectProfile.AtRetry;
import com.robenglander.libretto.spec.librettoProjectProfile.AtRetryKeyword;
import com.robenglander.libretto.spec.librettoProjectProfile.LibrettoProjectProfilePackage;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>At Retry</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link com.robenglander.libretto.spec.librettoProjectProfile.impl.AtRetryImpl#getKeyword <em>Keyword</em>}</li>
 *   <li>{@link com.robenglander.libretto.spec.librettoProjectProfile.impl.AtRetryImpl#getValue <em>Value</em>}</li>
 * </ul>
 *
 * @generated
 */
public class AtRetryImpl extends MinimalEObjectImpl.Container implements AtRetry
{
  /**
   * The cached value of the '{@link #getKeyword() <em>Keyword</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getKeyword()
   * @generated
   * @ordered
   */
  protected AtRetryKeyword keyword;

  /**
   * The default value of the '{@link #getValue() <em>Value</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getValue()
   * @generated
   * @ordered
   */
  protected static final int VALUE_EDEFAULT = 0;

  /**
   * The cached value of the '{@link #getValue() <em>Value</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getValue()
   * @generated
   * @ordered
   */
  protected int value = VALUE_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected AtRetryImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return LibrettoProjectProfilePackage.Literals.AT_RETRY;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public AtRetryKeyword getKeyword()
  {
    return keyword;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetKeyword(AtRetryKeyword newKeyword, NotificationChain msgs)
  {
    AtRetryKeyword oldKeyword = keyword;
    keyword = newKeyword;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, LibrettoProjectProfilePackage.AT_RETRY__KEYWORD, oldKeyword, newKeyword);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setKeyword(AtRetryKeyword newKeyword)
  {
    if (newKeyword != keyword)
    {
      NotificationChain msgs = null;
      if (keyword != null)
        msgs = ((InternalEObject)keyword).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - LibrettoProjectProfilePackage.AT_RETRY__KEYWORD, null, msgs);
      if (newKeyword != null)
        msgs = ((InternalEObject)newKeyword).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - LibrettoProjectProfilePackage.AT_RETRY__KEYWORD, null, msgs);
      msgs = basicSetKeyword(newKeyword, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, LibrettoProjectProfilePackage.AT_RETRY__KEYWORD, newKeyword, newKeyword));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public int getValue()
  {
    return value;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setValue(int newValue)
  {
    int oldValue = value;
    value = newValue;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, LibrettoProjectProfilePackage.AT_RETRY__VALUE, oldValue, value));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case LibrettoProjectProfilePackage.AT_RETRY__KEYWORD:
        return basicSetKeyword(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case LibrettoProjectProfilePackage.AT_RETRY__KEYWORD:
        return getKeyword();
      case LibrettoProjectProfilePackage.AT_RETRY__VALUE:
        return getValue();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case LibrettoProjectProfilePackage.AT_RETRY__KEYWORD:
        setKeyword((AtRetryKeyword)newValue);
        return;
      case LibrettoProjectProfilePackage.AT_RETRY__VALUE:
        setValue((Integer)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case LibrettoProjectProfilePackage.AT_RETRY__KEYWORD:
        setKeyword((AtRetryKeyword)null);
        return;
      case LibrettoProjectProfilePackage.AT_RETRY__VALUE:
        setValue(VALUE_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case LibrettoProjectProfilePackage.AT_RETRY__KEYWORD:
        return keyword != null;
      case LibrettoProjectProfilePackage.AT_RETRY__VALUE:
        return value != VALUE_EDEFAULT;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (value: ");
    result.append(value);
    result.append(')');
    return result.toString();
  }

} //AtRetryImpl
