/**
 * generated by Xtext 2.40.0
 */
package com.robenglander.libretto.spec.librettoProjectProfile.impl;

import com.robenglander.libretto.spec.librettoProjectProfile.DefaultCorrection;
import com.robenglander.libretto.spec.librettoProjectProfile.DefaultCorrectionKeyword;
import com.robenglander.libretto.spec.librettoProjectProfile.LibrettoProjectProfilePackage;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Default Correction</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link com.robenglander.libretto.spec.librettoProjectProfile.impl.DefaultCorrectionImpl#getKeyword <em>Keyword</em>}</li>
 *   <li>{@link com.robenglander.libretto.spec.librettoProjectProfile.impl.DefaultCorrectionImpl#getCorrection <em>Correction</em>}</li>
 * </ul>
 *
 * @generated
 */
public class DefaultCorrectionImpl extends MinimalEObjectImpl.Container implements DefaultCorrection
{
  /**
   * The cached value of the '{@link #getKeyword() <em>Keyword</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getKeyword()
   * @generated
   * @ordered
   */
  protected DefaultCorrectionKeyword keyword;

  /**
   * The default value of the '{@link #getCorrection() <em>Correction</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getCorrection()
   * @generated
   * @ordered
   */
  protected static final String CORRECTION_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getCorrection() <em>Correction</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getCorrection()
   * @generated
   * @ordered
   */
  protected String correction = CORRECTION_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected DefaultCorrectionImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return LibrettoProjectProfilePackage.Literals.DEFAULT_CORRECTION;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public DefaultCorrectionKeyword getKeyword()
  {
    return keyword;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetKeyword(DefaultCorrectionKeyword newKeyword, NotificationChain msgs)
  {
    DefaultCorrectionKeyword oldKeyword = keyword;
    keyword = newKeyword;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, LibrettoProjectProfilePackage.DEFAULT_CORRECTION__KEYWORD, oldKeyword, newKeyword);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setKeyword(DefaultCorrectionKeyword newKeyword)
  {
    if (newKeyword != keyword)
    {
      NotificationChain msgs = null;
      if (keyword != null)
        msgs = ((InternalEObject)keyword).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - LibrettoProjectProfilePackage.DEFAULT_CORRECTION__KEYWORD, null, msgs);
      if (newKeyword != null)
        msgs = ((InternalEObject)newKeyword).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - LibrettoProjectProfilePackage.DEFAULT_CORRECTION__KEYWORD, null, msgs);
      msgs = basicSetKeyword(newKeyword, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, LibrettoProjectProfilePackage.DEFAULT_CORRECTION__KEYWORD, newKeyword, newKeyword));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getCorrection()
  {
    return correction;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setCorrection(String newCorrection)
  {
    String oldCorrection = correction;
    correction = newCorrection;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, LibrettoProjectProfilePackage.DEFAULT_CORRECTION__CORRECTION, oldCorrection, correction));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case LibrettoProjectProfilePackage.DEFAULT_CORRECTION__KEYWORD:
        return basicSetKeyword(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case LibrettoProjectProfilePackage.DEFAULT_CORRECTION__KEYWORD:
        return getKeyword();
      case LibrettoProjectProfilePackage.DEFAULT_CORRECTION__CORRECTION:
        return getCorrection();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case LibrettoProjectProfilePackage.DEFAULT_CORRECTION__KEYWORD:
        setKeyword((DefaultCorrectionKeyword)newValue);
        return;
      case LibrettoProjectProfilePackage.DEFAULT_CORRECTION__CORRECTION:
        setCorrection((String)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case LibrettoProjectProfilePackage.DEFAULT_CORRECTION__KEYWORD:
        setKeyword((DefaultCorrectionKeyword)null);
        return;
      case LibrettoProjectProfilePackage.DEFAULT_CORRECTION__CORRECTION:
        setCorrection(CORRECTION_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case LibrettoProjectProfilePackage.DEFAULT_CORRECTION__KEYWORD:
        return keyword != null;
      case LibrettoProjectProfilePackage.DEFAULT_CORRECTION__CORRECTION:
        return CORRECTION_EDEFAULT == null ? correction != null : !CORRECTION_EDEFAULT.equals(correction);
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (correction: ");
    result.append(correction);
    result.append(')');
    return result.toString();
  }

} //DefaultCorrectionImpl
