/**
 * generated by Xtext 2.40.0
 */
package com.robenglander.libretto.spec.librettoProjectProfile.impl;

import com.robenglander.libretto.spec.librettoProjectProfile.LibrettoProjectProfilePackage;
import com.robenglander.libretto.spec.librettoProjectProfile.RootDirKeyword;
import com.robenglander.libretto.spec.librettoProjectProfile.RootDirectory;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Root Directory</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link com.robenglander.libretto.spec.librettoProjectProfile.impl.RootDirectoryImpl#getKeyword <em>Keyword</em>}</li>
 *   <li>{@link com.robenglander.libretto.spec.librettoProjectProfile.impl.RootDirectoryImpl#getDir <em>Dir</em>}</li>
 * </ul>
 *
 * @generated
 */
public class RootDirectoryImpl extends MinimalEObjectImpl.Container implements RootDirectory
{
  /**
   * The cached value of the '{@link #getKeyword() <em>Keyword</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getKeyword()
   * @generated
   * @ordered
   */
  protected RootDirKeyword keyword;

  /**
   * The default value of the '{@link #getDir() <em>Dir</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDir()
   * @generated
   * @ordered
   */
  protected static final String DIR_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getDir() <em>Dir</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDir()
   * @generated
   * @ordered
   */
  protected String dir = DIR_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected RootDirectoryImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return LibrettoProjectProfilePackage.Literals.ROOT_DIRECTORY;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public RootDirKeyword getKeyword()
  {
    return keyword;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetKeyword(RootDirKeyword newKeyword, NotificationChain msgs)
  {
    RootDirKeyword oldKeyword = keyword;
    keyword = newKeyword;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, LibrettoProjectProfilePackage.ROOT_DIRECTORY__KEYWORD, oldKeyword, newKeyword);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setKeyword(RootDirKeyword newKeyword)
  {
    if (newKeyword != keyword)
    {
      NotificationChain msgs = null;
      if (keyword != null)
        msgs = ((InternalEObject)keyword).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - LibrettoProjectProfilePackage.ROOT_DIRECTORY__KEYWORD, null, msgs);
      if (newKeyword != null)
        msgs = ((InternalEObject)newKeyword).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - LibrettoProjectProfilePackage.ROOT_DIRECTORY__KEYWORD, null, msgs);
      msgs = basicSetKeyword(newKeyword, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, LibrettoProjectProfilePackage.ROOT_DIRECTORY__KEYWORD, newKeyword, newKeyword));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getDir()
  {
    return dir;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setDir(String newDir)
  {
    String oldDir = dir;
    dir = newDir;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, LibrettoProjectProfilePackage.ROOT_DIRECTORY__DIR, oldDir, dir));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case LibrettoProjectProfilePackage.ROOT_DIRECTORY__KEYWORD:
        return basicSetKeyword(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case LibrettoProjectProfilePackage.ROOT_DIRECTORY__KEYWORD:
        return getKeyword();
      case LibrettoProjectProfilePackage.ROOT_DIRECTORY__DIR:
        return getDir();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case LibrettoProjectProfilePackage.ROOT_DIRECTORY__KEYWORD:
        setKeyword((RootDirKeyword)newValue);
        return;
      case LibrettoProjectProfilePackage.ROOT_DIRECTORY__DIR:
        setDir((String)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case LibrettoProjectProfilePackage.ROOT_DIRECTORY__KEYWORD:
        setKeyword((RootDirKeyword)null);
        return;
      case LibrettoProjectProfilePackage.ROOT_DIRECTORY__DIR:
        setDir(DIR_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case LibrettoProjectProfilePackage.ROOT_DIRECTORY__KEYWORD:
        return keyword != null;
      case LibrettoProjectProfilePackage.ROOT_DIRECTORY__DIR:
        return DIR_EDEFAULT == null ? dir != null : !DIR_EDEFAULT.equals(dir);
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (dir: ");
    result.append(dir);
    result.append(')');
    return result.toString();
  }

} //RootDirectoryImpl
