/**
 * generated by Xtext 2.40.0
 */
package com.robenglander.libretto.spec.librettoProjectProfile.impl;

import com.robenglander.libretto.spec.librettoProjectProfile.LibrettoProjectProfilePackage;
import com.robenglander.libretto.spec.librettoProjectProfile.SurfaceElement;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Surface Element</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class SurfaceElementImpl extends MinimalEObjectImpl.Container implements SurfaceElement
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected SurfaceElementImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return LibrettoProjectProfilePackage.Literals.SURFACE_ELEMENT;
  }

} //SurfaceElementImpl
