/**
 * generated by Xtext 2.40.0
 */
package com.robenglander.libretto.spec.librettoProjectProfile.impl;

import com.robenglander.libretto.spec.librettoProjectProfile.LibrettoProjectProfilePackage;
import com.robenglander.libretto.spec.librettoProjectProfile.TestGenBlock;
import com.robenglander.libretto.spec.librettoProjectProfile.TestGenLegacyRemediationRulesBlock;
import com.robenglander.libretto.spec.librettoProjectProfile.TestGenModulePolicy;
import com.robenglander.libretto.spec.librettoProjectProfile.TestGenRemediationsBlock;
import com.robenglander.libretto.spec.librettoProjectProfile.TestGenUsageBlock;

import java.util.Collection;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EDataTypeEList;
import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Test Gen Block</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link com.robenglander.libretto.spec.librettoProjectProfile.impl.TestGenBlockImpl#getInitialInstruction <em>Initial Instruction</em>}</li>
 *   <li>{@link com.robenglander.libretto.spec.librettoProjectProfile.impl.TestGenBlockImpl#getForbiddenPatterns <em>Forbidden Patterns</em>}</li>
 *   <li>{@link com.robenglander.libretto.spec.librettoProjectProfile.impl.TestGenBlockImpl#getMaxRetries <em>Max Retries</em>}</li>
 *   <li>{@link com.robenglander.libretto.spec.librettoProjectProfile.impl.TestGenBlockImpl#getParseCheck <em>Parse Check</em>}</li>
 *   <li>{@link com.robenglander.libretto.spec.librettoProjectProfile.impl.TestGenBlockImpl#getRemediations <em>Remediations</em>}</li>
 *   <li>{@link com.robenglander.libretto.spec.librettoProjectProfile.impl.TestGenBlockImpl#getLegacyRemediationRules <em>Legacy Remediation Rules</em>}</li>
 *   <li>{@link com.robenglander.libretto.spec.librettoProjectProfile.impl.TestGenBlockImpl#getUsage <em>Usage</em>}</li>
 *   <li>{@link com.robenglander.libretto.spec.librettoProjectProfile.impl.TestGenBlockImpl#getModulePolicies <em>Module Policies</em>}</li>
 * </ul>
 *
 * @generated
 */
public class TestGenBlockImpl extends MinimalEObjectImpl.Container implements TestGenBlock
{
  /**
   * The default value of the '{@link #getInitialInstruction() <em>Initial Instruction</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getInitialInstruction()
   * @generated
   * @ordered
   */
  protected static final String INITIAL_INSTRUCTION_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getInitialInstruction() <em>Initial Instruction</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getInitialInstruction()
   * @generated
   * @ordered
   */
  protected String initialInstruction = INITIAL_INSTRUCTION_EDEFAULT;

  /**
   * The cached value of the '{@link #getForbiddenPatterns() <em>Forbidden Patterns</em>}' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getForbiddenPatterns()
   * @generated
   * @ordered
   */
  protected EList<String> forbiddenPatterns;

  /**
   * The default value of the '{@link #getMaxRetries() <em>Max Retries</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getMaxRetries()
   * @generated
   * @ordered
   */
  protected static final int MAX_RETRIES_EDEFAULT = 0;

  /**
   * The cached value of the '{@link #getMaxRetries() <em>Max Retries</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getMaxRetries()
   * @generated
   * @ordered
   */
  protected int maxRetries = MAX_RETRIES_EDEFAULT;

  /**
   * The default value of the '{@link #getParseCheck() <em>Parse Check</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getParseCheck()
   * @generated
   * @ordered
   */
  protected static final String PARSE_CHECK_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getParseCheck() <em>Parse Check</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getParseCheck()
   * @generated
   * @ordered
   */
  protected String parseCheck = PARSE_CHECK_EDEFAULT;

  /**
   * The cached value of the '{@link #getRemediations() <em>Remediations</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getRemediations()
   * @generated
   * @ordered
   */
  protected TestGenRemediationsBlock remediations;

  /**
   * The cached value of the '{@link #getLegacyRemediationRules() <em>Legacy Remediation Rules</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getLegacyRemediationRules()
   * @generated
   * @ordered
   */
  protected TestGenLegacyRemediationRulesBlock legacyRemediationRules;

  /**
   * The cached value of the '{@link #getUsage() <em>Usage</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getUsage()
   * @generated
   * @ordered
   */
  protected TestGenUsageBlock usage;

  /**
   * The cached value of the '{@link #getModulePolicies() <em>Module Policies</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getModulePolicies()
   * @generated
   * @ordered
   */
  protected EList<TestGenModulePolicy> modulePolicies;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected TestGenBlockImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return LibrettoProjectProfilePackage.Literals.TEST_GEN_BLOCK;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getInitialInstruction()
  {
    return initialInstruction;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setInitialInstruction(String newInitialInstruction)
  {
    String oldInitialInstruction = initialInstruction;
    initialInstruction = newInitialInstruction;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, LibrettoProjectProfilePackage.TEST_GEN_BLOCK__INITIAL_INSTRUCTION, oldInitialInstruction, initialInstruction));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<String> getForbiddenPatterns()
  {
    if (forbiddenPatterns == null)
    {
      forbiddenPatterns = new EDataTypeEList<String>(String.class, this, LibrettoProjectProfilePackage.TEST_GEN_BLOCK__FORBIDDEN_PATTERNS);
    }
    return forbiddenPatterns;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public int getMaxRetries()
  {
    return maxRetries;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setMaxRetries(int newMaxRetries)
  {
    int oldMaxRetries = maxRetries;
    maxRetries = newMaxRetries;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, LibrettoProjectProfilePackage.TEST_GEN_BLOCK__MAX_RETRIES, oldMaxRetries, maxRetries));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getParseCheck()
  {
    return parseCheck;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setParseCheck(String newParseCheck)
  {
    String oldParseCheck = parseCheck;
    parseCheck = newParseCheck;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, LibrettoProjectProfilePackage.TEST_GEN_BLOCK__PARSE_CHECK, oldParseCheck, parseCheck));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public TestGenRemediationsBlock getRemediations()
  {
    return remediations;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetRemediations(TestGenRemediationsBlock newRemediations, NotificationChain msgs)
  {
    TestGenRemediationsBlock oldRemediations = remediations;
    remediations = newRemediations;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, LibrettoProjectProfilePackage.TEST_GEN_BLOCK__REMEDIATIONS, oldRemediations, newRemediations);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setRemediations(TestGenRemediationsBlock newRemediations)
  {
    if (newRemediations != remediations)
    {
      NotificationChain msgs = null;
      if (remediations != null)
        msgs = ((InternalEObject)remediations).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - LibrettoProjectProfilePackage.TEST_GEN_BLOCK__REMEDIATIONS, null, msgs);
      if (newRemediations != null)
        msgs = ((InternalEObject)newRemediations).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - LibrettoProjectProfilePackage.TEST_GEN_BLOCK__REMEDIATIONS, null, msgs);
      msgs = basicSetRemediations(newRemediations, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, LibrettoProjectProfilePackage.TEST_GEN_BLOCK__REMEDIATIONS, newRemediations, newRemediations));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public TestGenLegacyRemediationRulesBlock getLegacyRemediationRules()
  {
    return legacyRemediationRules;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetLegacyRemediationRules(TestGenLegacyRemediationRulesBlock newLegacyRemediationRules, NotificationChain msgs)
  {
    TestGenLegacyRemediationRulesBlock oldLegacyRemediationRules = legacyRemediationRules;
    legacyRemediationRules = newLegacyRemediationRules;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, LibrettoProjectProfilePackage.TEST_GEN_BLOCK__LEGACY_REMEDIATION_RULES, oldLegacyRemediationRules, newLegacyRemediationRules);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setLegacyRemediationRules(TestGenLegacyRemediationRulesBlock newLegacyRemediationRules)
  {
    if (newLegacyRemediationRules != legacyRemediationRules)
    {
      NotificationChain msgs = null;
      if (legacyRemediationRules != null)
        msgs = ((InternalEObject)legacyRemediationRules).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - LibrettoProjectProfilePackage.TEST_GEN_BLOCK__LEGACY_REMEDIATION_RULES, null, msgs);
      if (newLegacyRemediationRules != null)
        msgs = ((InternalEObject)newLegacyRemediationRules).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - LibrettoProjectProfilePackage.TEST_GEN_BLOCK__LEGACY_REMEDIATION_RULES, null, msgs);
      msgs = basicSetLegacyRemediationRules(newLegacyRemediationRules, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, LibrettoProjectProfilePackage.TEST_GEN_BLOCK__LEGACY_REMEDIATION_RULES, newLegacyRemediationRules, newLegacyRemediationRules));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public TestGenUsageBlock getUsage()
  {
    return usage;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetUsage(TestGenUsageBlock newUsage, NotificationChain msgs)
  {
    TestGenUsageBlock oldUsage = usage;
    usage = newUsage;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, LibrettoProjectProfilePackage.TEST_GEN_BLOCK__USAGE, oldUsage, newUsage);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setUsage(TestGenUsageBlock newUsage)
  {
    if (newUsage != usage)
    {
      NotificationChain msgs = null;
      if (usage != null)
        msgs = ((InternalEObject)usage).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - LibrettoProjectProfilePackage.TEST_GEN_BLOCK__USAGE, null, msgs);
      if (newUsage != null)
        msgs = ((InternalEObject)newUsage).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - LibrettoProjectProfilePackage.TEST_GEN_BLOCK__USAGE, null, msgs);
      msgs = basicSetUsage(newUsage, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, LibrettoProjectProfilePackage.TEST_GEN_BLOCK__USAGE, newUsage, newUsage));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<TestGenModulePolicy> getModulePolicies()
  {
    if (modulePolicies == null)
    {
      modulePolicies = new EObjectContainmentEList<TestGenModulePolicy>(TestGenModulePolicy.class, this, LibrettoProjectProfilePackage.TEST_GEN_BLOCK__MODULE_POLICIES);
    }
    return modulePolicies;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case LibrettoProjectProfilePackage.TEST_GEN_BLOCK__REMEDIATIONS:
        return basicSetRemediations(null, msgs);
      case LibrettoProjectProfilePackage.TEST_GEN_BLOCK__LEGACY_REMEDIATION_RULES:
        return basicSetLegacyRemediationRules(null, msgs);
      case LibrettoProjectProfilePackage.TEST_GEN_BLOCK__USAGE:
        return basicSetUsage(null, msgs);
      case LibrettoProjectProfilePackage.TEST_GEN_BLOCK__MODULE_POLICIES:
        return ((InternalEList<?>)getModulePolicies()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case LibrettoProjectProfilePackage.TEST_GEN_BLOCK__INITIAL_INSTRUCTION:
        return getInitialInstruction();
      case LibrettoProjectProfilePackage.TEST_GEN_BLOCK__FORBIDDEN_PATTERNS:
        return getForbiddenPatterns();
      case LibrettoProjectProfilePackage.TEST_GEN_BLOCK__MAX_RETRIES:
        return getMaxRetries();
      case LibrettoProjectProfilePackage.TEST_GEN_BLOCK__PARSE_CHECK:
        return getParseCheck();
      case LibrettoProjectProfilePackage.TEST_GEN_BLOCK__REMEDIATIONS:
        return getRemediations();
      case LibrettoProjectProfilePackage.TEST_GEN_BLOCK__LEGACY_REMEDIATION_RULES:
        return getLegacyRemediationRules();
      case LibrettoProjectProfilePackage.TEST_GEN_BLOCK__USAGE:
        return getUsage();
      case LibrettoProjectProfilePackage.TEST_GEN_BLOCK__MODULE_POLICIES:
        return getModulePolicies();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case LibrettoProjectProfilePackage.TEST_GEN_BLOCK__INITIAL_INSTRUCTION:
        setInitialInstruction((String)newValue);
        return;
      case LibrettoProjectProfilePackage.TEST_GEN_BLOCK__FORBIDDEN_PATTERNS:
        getForbiddenPatterns().clear();
        getForbiddenPatterns().addAll((Collection<? extends String>)newValue);
        return;
      case LibrettoProjectProfilePackage.TEST_GEN_BLOCK__MAX_RETRIES:
        setMaxRetries((Integer)newValue);
        return;
      case LibrettoProjectProfilePackage.TEST_GEN_BLOCK__PARSE_CHECK:
        setParseCheck((String)newValue);
        return;
      case LibrettoProjectProfilePackage.TEST_GEN_BLOCK__REMEDIATIONS:
        setRemediations((TestGenRemediationsBlock)newValue);
        return;
      case LibrettoProjectProfilePackage.TEST_GEN_BLOCK__LEGACY_REMEDIATION_RULES:
        setLegacyRemediationRules((TestGenLegacyRemediationRulesBlock)newValue);
        return;
      case LibrettoProjectProfilePackage.TEST_GEN_BLOCK__USAGE:
        setUsage((TestGenUsageBlock)newValue);
        return;
      case LibrettoProjectProfilePackage.TEST_GEN_BLOCK__MODULE_POLICIES:
        getModulePolicies().clear();
        getModulePolicies().addAll((Collection<? extends TestGenModulePolicy>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case LibrettoProjectProfilePackage.TEST_GEN_BLOCK__INITIAL_INSTRUCTION:
        setInitialInstruction(INITIAL_INSTRUCTION_EDEFAULT);
        return;
      case LibrettoProjectProfilePackage.TEST_GEN_BLOCK__FORBIDDEN_PATTERNS:
        getForbiddenPatterns().clear();
        return;
      case LibrettoProjectProfilePackage.TEST_GEN_BLOCK__MAX_RETRIES:
        setMaxRetries(MAX_RETRIES_EDEFAULT);
        return;
      case LibrettoProjectProfilePackage.TEST_GEN_BLOCK__PARSE_CHECK:
        setParseCheck(PARSE_CHECK_EDEFAULT);
        return;
      case LibrettoProjectProfilePackage.TEST_GEN_BLOCK__REMEDIATIONS:
        setRemediations((TestGenRemediationsBlock)null);
        return;
      case LibrettoProjectProfilePackage.TEST_GEN_BLOCK__LEGACY_REMEDIATION_RULES:
        setLegacyRemediationRules((TestGenLegacyRemediationRulesBlock)null);
        return;
      case LibrettoProjectProfilePackage.TEST_GEN_BLOCK__USAGE:
        setUsage((TestGenUsageBlock)null);
        return;
      case LibrettoProjectProfilePackage.TEST_GEN_BLOCK__MODULE_POLICIES:
        getModulePolicies().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case LibrettoProjectProfilePackage.TEST_GEN_BLOCK__INITIAL_INSTRUCTION:
        return INITIAL_INSTRUCTION_EDEFAULT == null ? initialInstruction != null : !INITIAL_INSTRUCTION_EDEFAULT.equals(initialInstruction);
      case LibrettoProjectProfilePackage.TEST_GEN_BLOCK__FORBIDDEN_PATTERNS:
        return forbiddenPatterns != null && !forbiddenPatterns.isEmpty();
      case LibrettoProjectProfilePackage.TEST_GEN_BLOCK__MAX_RETRIES:
        return maxRetries != MAX_RETRIES_EDEFAULT;
      case LibrettoProjectProfilePackage.TEST_GEN_BLOCK__PARSE_CHECK:
        return PARSE_CHECK_EDEFAULT == null ? parseCheck != null : !PARSE_CHECK_EDEFAULT.equals(parseCheck);
      case LibrettoProjectProfilePackage.TEST_GEN_BLOCK__REMEDIATIONS:
        return remediations != null;
      case LibrettoProjectProfilePackage.TEST_GEN_BLOCK__LEGACY_REMEDIATION_RULES:
        return legacyRemediationRules != null;
      case LibrettoProjectProfilePackage.TEST_GEN_BLOCK__USAGE:
        return usage != null;
      case LibrettoProjectProfilePackage.TEST_GEN_BLOCK__MODULE_POLICIES:
        return modulePolicies != null && !modulePolicies.isEmpty();
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (initialInstruction: ");
    result.append(initialInstruction);
    result.append(", forbiddenPatterns: ");
    result.append(forbiddenPatterns);
    result.append(", maxRetries: ");
    result.append(maxRetries);
    result.append(", parseCheck: ");
    result.append(parseCheck);
    result.append(')');
    return result.toString();
  }

} //TestGenBlockImpl
