/**
 * generated by Xtext 2.40.0
 */
package com.robenglander.libretto.spec.librettoProjectProfile.impl;

import com.robenglander.libretto.spec.librettoProjectProfile.LibrettoProjectProfilePackage;
import com.robenglander.libretto.spec.librettoProjectProfile.TrueFalseKeyword;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>True False Keyword</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class TrueFalseKeywordImpl extends MinimalEObjectImpl.Container implements TrueFalseKeyword
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected TrueFalseKeywordImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return LibrettoProjectProfilePackage.Literals.TRUE_FALSE_KEYWORD;
  }

} //TrueFalseKeywordImpl
