/**
 * generated by Xtext 2.40.0
 */
package com.robenglander.libretto.spec.librettoSpec;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Acceptance Test Record Item</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.robenglander.libretto.spec.librettoSpec.AcceptanceTestRecordItem#getSource <em>Source</em>}</li>
 *   <li>{@link com.robenglander.libretto.spec.librettoSpec.AcceptanceTestRecordItem#getValidates <em>Validates</em>}</li>
 *   <li>{@link com.robenglander.libretto.spec.librettoSpec.AcceptanceTestRecordItem#getPreconditions <em>Preconditions</em>}</li>
 *   <li>{@link com.robenglander.libretto.spec.librettoSpec.AcceptanceTestRecordItem#getActions <em>Actions</em>}</li>
 *   <li>{@link com.robenglander.libretto.spec.librettoSpec.AcceptanceTestRecordItem#getAssertions <em>Assertions</em>}</li>
 *   <li>{@link com.robenglander.libretto.spec.librettoSpec.AcceptanceTestRecordItem#getTitle <em>Title</em>}</li>
 *   <li>{@link com.robenglander.libretto.spec.librettoSpec.AcceptanceTestRecordItem#getReferences <em>References</em>}</li>
 *   <li>{@link com.robenglander.libretto.spec.librettoSpec.AcceptanceTestRecordItem#getNotes <em>Notes</em>}</li>
 *   <li>{@link com.robenglander.libretto.spec.librettoSpec.AcceptanceTestRecordItem#getContext <em>Context</em>}</li>
 * </ul>
 *
 * @see com.robenglander.libretto.spec.librettoSpec.LibrettoSpecPackage#getAcceptanceTestRecordItem()
 * @model
 * @generated
 */
public interface AcceptanceTestRecordItem extends EObject
{
  /**
   * Returns the value of the '<em><b>Source</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Source</em>' containment reference.
   * @see #setSource(SourceBlock)
   * @see com.robenglander.libretto.spec.librettoSpec.LibrettoSpecPackage#getAcceptanceTestRecordItem_Source()
   * @model containment="true"
   * @generated
   */
  SourceBlock getSource();

  /**
   * Sets the value of the '{@link com.robenglander.libretto.spec.librettoSpec.AcceptanceTestRecordItem#getSource <em>Source</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Source</em>' containment reference.
   * @see #getSource()
   * @generated
   */
  void setSource(SourceBlock value);

  /**
   * Returns the value of the '<em><b>Validates</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Validates</em>' containment reference.
   * @see #setValidates(ValidatesField)
   * @see com.robenglander.libretto.spec.librettoSpec.LibrettoSpecPackage#getAcceptanceTestRecordItem_Validates()
   * @model containment="true"
   * @generated
   */
  ValidatesField getValidates();

  /**
   * Sets the value of the '{@link com.robenglander.libretto.spec.librettoSpec.AcceptanceTestRecordItem#getValidates <em>Validates</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Validates</em>' containment reference.
   * @see #getValidates()
   * @generated
   */
  void setValidates(ValidatesField value);

  /**
   * Returns the value of the '<em><b>Preconditions</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Preconditions</em>' containment reference.
   * @see #setPreconditions(PreconditionsField)
   * @see com.robenglander.libretto.spec.librettoSpec.LibrettoSpecPackage#getAcceptanceTestRecordItem_Preconditions()
   * @model containment="true"
   * @generated
   */
  PreconditionsField getPreconditions();

  /**
   * Sets the value of the '{@link com.robenglander.libretto.spec.librettoSpec.AcceptanceTestRecordItem#getPreconditions <em>Preconditions</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Preconditions</em>' containment reference.
   * @see #getPreconditions()
   * @generated
   */
  void setPreconditions(PreconditionsField value);

  /**
   * Returns the value of the '<em><b>Actions</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Actions</em>' containment reference.
   * @see #setActions(ActionsField)
   * @see com.robenglander.libretto.spec.librettoSpec.LibrettoSpecPackage#getAcceptanceTestRecordItem_Actions()
   * @model containment="true"
   * @generated
   */
  ActionsField getActions();

  /**
   * Sets the value of the '{@link com.robenglander.libretto.spec.librettoSpec.AcceptanceTestRecordItem#getActions <em>Actions</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Actions</em>' containment reference.
   * @see #getActions()
   * @generated
   */
  void setActions(ActionsField value);

  /**
   * Returns the value of the '<em><b>Assertions</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Assertions</em>' containment reference.
   * @see #setAssertions(AssertionsField)
   * @see com.robenglander.libretto.spec.librettoSpec.LibrettoSpecPackage#getAcceptanceTestRecordItem_Assertions()
   * @model containment="true"
   * @generated
   */
  AssertionsField getAssertions();

  /**
   * Sets the value of the '{@link com.robenglander.libretto.spec.librettoSpec.AcceptanceTestRecordItem#getAssertions <em>Assertions</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Assertions</em>' containment reference.
   * @see #getAssertions()
   * @generated
   */
  void setAssertions(AssertionsField value);

  /**
   * Returns the value of the '<em><b>Title</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Title</em>' containment reference.
   * @see #setTitle(TitleField)
   * @see com.robenglander.libretto.spec.librettoSpec.LibrettoSpecPackage#getAcceptanceTestRecordItem_Title()
   * @model containment="true"
   * @generated
   */
  TitleField getTitle();

  /**
   * Sets the value of the '{@link com.robenglander.libretto.spec.librettoSpec.AcceptanceTestRecordItem#getTitle <em>Title</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Title</em>' containment reference.
   * @see #getTitle()
   * @generated
   */
  void setTitle(TitleField value);

  /**
   * Returns the value of the '<em><b>References</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>References</em>' containment reference.
   * @see #setReferences(ReferencesField)
   * @see com.robenglander.libretto.spec.librettoSpec.LibrettoSpecPackage#getAcceptanceTestRecordItem_References()
   * @model containment="true"
   * @generated
   */
  ReferencesField getReferences();

  /**
   * Sets the value of the '{@link com.robenglander.libretto.spec.librettoSpec.AcceptanceTestRecordItem#getReferences <em>References</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>References</em>' containment reference.
   * @see #getReferences()
   * @generated
   */
  void setReferences(ReferencesField value);

  /**
   * Returns the value of the '<em><b>Notes</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Notes</em>' containment reference.
   * @see #setNotes(NotesField)
   * @see com.robenglander.libretto.spec.librettoSpec.LibrettoSpecPackage#getAcceptanceTestRecordItem_Notes()
   * @model containment="true"
   * @generated
   */
  NotesField getNotes();

  /**
   * Sets the value of the '{@link com.robenglander.libretto.spec.librettoSpec.AcceptanceTestRecordItem#getNotes <em>Notes</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Notes</em>' containment reference.
   * @see #getNotes()
   * @generated
   */
  void setNotes(NotesField value);

  /**
   * Returns the value of the '<em><b>Context</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Context</em>' containment reference.
   * @see #setContext(ContextField)
   * @see com.robenglander.libretto.spec.librettoSpec.LibrettoSpecPackage#getAcceptanceTestRecordItem_Context()
   * @model containment="true"
   * @generated
   */
  ContextField getContext();

  /**
   * Sets the value of the '{@link com.robenglander.libretto.spec.librettoSpec.AcceptanceTestRecordItem#getContext <em>Context</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Context</em>' containment reference.
   * @see #getContext()
   * @generated
   */
  void setContext(ContextField value);

} // AcceptanceTestRecordItem
