/**
 * generated by Xtext 2.40.0
 */
package com.robenglander.libretto.spec.librettoSpec;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Behavior Record</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.robenglander.libretto.spec.librettoSpec.BehaviorRecord#getId <em>Id</em>}</li>
 *   <li>{@link com.robenglander.libretto.spec.librettoSpec.BehaviorRecord#getItems <em>Items</em>}</li>
 * </ul>
 *
 * @see com.robenglander.libretto.spec.librettoSpec.LibrettoSpecPackage#getBehaviorRecord()
 * @model
 * @generated
 */
public interface BehaviorRecord extends EObject
{
  /**
   * Returns the value of the '<em><b>Id</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Id</em>' attribute.
   * @see #setId(String)
   * @see com.robenglander.libretto.spec.librettoSpec.LibrettoSpecPackage#getBehaviorRecord_Id()
   * @model
   * @generated
   */
  String getId();

  /**
   * Sets the value of the '{@link com.robenglander.libretto.spec.librettoSpec.BehaviorRecord#getId <em>Id</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Id</em>' attribute.
   * @see #getId()
   * @generated
   */
  void setId(String value);

  /**
   * Returns the value of the '<em><b>Items</b></em>' containment reference list.
   * The list contents are of type {@link com.robenglander.libretto.spec.librettoSpec.BehaviorRecordItem}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Items</em>' containment reference list.
   * @see com.robenglander.libretto.spec.librettoSpec.LibrettoSpecPackage#getBehaviorRecord_Items()
   * @model containment="true"
   * @generated
   */
  EList<BehaviorRecordItem> getItems();

} // BehaviorRecord
