/**
 * generated by Xtext 2.40.0
 */
package com.robenglander.libretto.spec.librettoSpec;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Metadata Compiler Version Field</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.robenglander.libretto.spec.librettoSpec.MetadataCompilerVersionField#getCompilerVersion <em>Compiler Version</em>}</li>
 * </ul>
 *
 * @see com.robenglander.libretto.spec.librettoSpec.LibrettoSpecPackage#getMetadataCompilerVersionField()
 * @model
 * @generated
 */
public interface MetadataCompilerVersionField extends MetadataField
{
  /**
   * Returns the value of the '<em><b>Compiler Version</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Compiler Version</em>' containment reference.
   * @see #setCompilerVersion(TextValue)
   * @see com.robenglander.libretto.spec.librettoSpec.LibrettoSpecPackage#getMetadataCompilerVersionField_CompilerVersion()
   * @model containment="true"
   * @generated
   */
  TextValue getCompilerVersion();

  /**
   * Sets the value of the '{@link com.robenglander.libretto.spec.librettoSpec.MetadataCompilerVersionField#getCompilerVersion <em>Compiler Version</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Compiler Version</em>' containment reference.
   * @see #getCompilerVersion()
   * @generated
   */
  void setCompilerVersion(TextValue value);

} // MetadataCompilerVersionField
