/**
 * generated by Xtext 2.40.0
 */
package com.robenglander.libretto.spec.librettoSpec;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Metadata Field</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.robenglander.libretto.spec.librettoSpec.MetadataField#getSpecId <em>Spec Id</em>}</li>
 *   <li>{@link com.robenglander.libretto.spec.librettoSpec.MetadataField#getTitle <em>Title</em>}</li>
 *   <li>{@link com.robenglander.libretto.spec.librettoSpec.MetadataField#getVersion <em>Version</em>}</li>
 *   <li>{@link com.robenglander.libretto.spec.librettoSpec.MetadataField#getStatus <em>Status</em>}</li>
 *   <li>{@link com.robenglander.libretto.spec.librettoSpec.MetadataField#getAuthoredSource <em>Authored Source</em>}</li>
 *   <li>{@link com.robenglander.libretto.spec.librettoSpec.MetadataField#getCompiledAt <em>Compiled At</em>}</li>
 *   <li>{@link com.robenglander.libretto.spec.librettoSpec.MetadataField#getCompilerVersion <em>Compiler Version</em>}</li>
 *   <li>{@link com.robenglander.libretto.spec.librettoSpec.MetadataField#getModelMetadata <em>Model Metadata</em>}</li>
 * </ul>
 *
 * @see com.robenglander.libretto.spec.librettoSpec.LibrettoSpecPackage#getMetadataField()
 * @model
 * @generated
 */
public interface MetadataField extends EObject
{
  /**
   * Returns the value of the '<em><b>Spec Id</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Spec Id</em>' attribute.
   * @see #setSpecId(String)
   * @see com.robenglander.libretto.spec.librettoSpec.LibrettoSpecPackage#getMetadataField_SpecId()
   * @model
   * @generated
   */
  String getSpecId();

  /**
   * Sets the value of the '{@link com.robenglander.libretto.spec.librettoSpec.MetadataField#getSpecId <em>Spec Id</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Spec Id</em>' attribute.
   * @see #getSpecId()
   * @generated
   */
  void setSpecId(String value);

  /**
   * Returns the value of the '<em><b>Title</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Title</em>' attribute.
   * @see #setTitle(String)
   * @see com.robenglander.libretto.spec.librettoSpec.LibrettoSpecPackage#getMetadataField_Title()
   * @model
   * @generated
   */
  String getTitle();

  /**
   * Sets the value of the '{@link com.robenglander.libretto.spec.librettoSpec.MetadataField#getTitle <em>Title</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Title</em>' attribute.
   * @see #getTitle()
   * @generated
   */
  void setTitle(String value);

  /**
   * Returns the value of the '<em><b>Version</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Version</em>' attribute.
   * @see #setVersion(String)
   * @see com.robenglander.libretto.spec.librettoSpec.LibrettoSpecPackage#getMetadataField_Version()
   * @model
   * @generated
   */
  String getVersion();

  /**
   * Sets the value of the '{@link com.robenglander.libretto.spec.librettoSpec.MetadataField#getVersion <em>Version</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Version</em>' attribute.
   * @see #getVersion()
   * @generated
   */
  void setVersion(String value);

  /**
   * Returns the value of the '<em><b>Status</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Status</em>' containment reference.
   * @see #setStatus(IdentifierValue)
   * @see com.robenglander.libretto.spec.librettoSpec.LibrettoSpecPackage#getMetadataField_Status()
   * @model containment="true"
   * @generated
   */
  IdentifierValue getStatus();

  /**
   * Sets the value of the '{@link com.robenglander.libretto.spec.librettoSpec.MetadataField#getStatus <em>Status</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Status</em>' containment reference.
   * @see #getStatus()
   * @generated
   */
  void setStatus(IdentifierValue value);

  /**
   * Returns the value of the '<em><b>Authored Source</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Authored Source</em>' attribute.
   * @see #setAuthoredSource(String)
   * @see com.robenglander.libretto.spec.librettoSpec.LibrettoSpecPackage#getMetadataField_AuthoredSource()
   * @model
   * @generated
   */
  String getAuthoredSource();

  /**
   * Sets the value of the '{@link com.robenglander.libretto.spec.librettoSpec.MetadataField#getAuthoredSource <em>Authored Source</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Authored Source</em>' attribute.
   * @see #getAuthoredSource()
   * @generated
   */
  void setAuthoredSource(String value);

  /**
   * Returns the value of the '<em><b>Compiled At</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Compiled At</em>' attribute.
   * @see #setCompiledAt(String)
   * @see com.robenglander.libretto.spec.librettoSpec.LibrettoSpecPackage#getMetadataField_CompiledAt()
   * @model
   * @generated
   */
  String getCompiledAt();

  /**
   * Sets the value of the '{@link com.robenglander.libretto.spec.librettoSpec.MetadataField#getCompiledAt <em>Compiled At</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Compiled At</em>' attribute.
   * @see #getCompiledAt()
   * @generated
   */
  void setCompiledAt(String value);

  /**
   * Returns the value of the '<em><b>Compiler Version</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Compiler Version</em>' attribute.
   * @see #setCompilerVersion(String)
   * @see com.robenglander.libretto.spec.librettoSpec.LibrettoSpecPackage#getMetadataField_CompilerVersion()
   * @model
   * @generated
   */
  String getCompilerVersion();

  /**
   * Sets the value of the '{@link com.robenglander.libretto.spec.librettoSpec.MetadataField#getCompilerVersion <em>Compiler Version</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Compiler Version</em>' attribute.
   * @see #getCompilerVersion()
   * @generated
   */
  void setCompilerVersion(String value);

  /**
   * Returns the value of the '<em><b>Model Metadata</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Model Metadata</em>' attribute.
   * @see #setModelMetadata(String)
   * @see com.robenglander.libretto.spec.librettoSpec.LibrettoSpecPackage#getMetadataField_ModelMetadata()
   * @model
   * @generated
   */
  String getModelMetadata();

  /**
   * Sets the value of the '{@link com.robenglander.libretto.spec.librettoSpec.MetadataField#getModelMetadata <em>Model Metadata</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Model Metadata</em>' attribute.
   * @see #getModelMetadata()
   * @generated
   */
  void setModelMetadata(String value);

} // MetadataField
