/**
 * generated by Xtext 2.40.0
 */
package com.robenglander.libretto.spec.librettoSpec;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Prose Section</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.robenglander.libretto.spec.librettoSpec.ProseSection#getRecords <em>Records</em>}</li>
 * </ul>
 *
 * @see com.robenglander.libretto.spec.librettoSpec.LibrettoSpecPackage#getProseSection()
 * @model
 * @generated
 */
public interface ProseSection extends SpecSection
{
  /**
   * Returns the value of the '<em><b>Records</b></em>' containment reference list.
   * The list contents are of type {@link com.robenglander.libretto.spec.librettoSpec.ProseRecord}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Records</em>' containment reference list.
   * @see com.robenglander.libretto.spec.librettoSpec.LibrettoSpecPackage#getProseSection_Records()
   * @model containment="true"
   * @generated
   */
  EList<ProseRecord> getRecords();

} // ProseSection
