/**
 * generated by Xtext 2.40.0
 */
package com.robenglander.libretto.spec.librettoSpec;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Type Field</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.robenglander.libretto.spec.librettoSpec.TypeField#getValue <em>Value</em>}</li>
 * </ul>
 *
 * @see com.robenglander.libretto.spec.librettoSpec.LibrettoSpecPackage#getTypeField()
 * @model
 * @generated
 */
public interface TypeField extends EObject
{
  /**
   * Returns the value of the '<em><b>Value</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Value</em>' containment reference.
   * @see #setValue(IdentifierValue)
   * @see com.robenglander.libretto.spec.librettoSpec.LibrettoSpecPackage#getTypeField_Value()
   * @model containment="true"
   * @generated
   */
  IdentifierValue getValue();

  /**
   * Sets the value of the '{@link com.robenglander.libretto.spec.librettoSpec.TypeField#getValue <em>Value</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Value</em>' containment reference.
   * @see #getValue()
   * @generated
   */
  void setValue(IdentifierValue value);

} // TypeField
