/*
 * generated by Xtext 2.40.0
 */
package com.robenglander.libretto.spec.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class LibrettoSpecUiModule extends AbstractLibrettoSpecUiModule {

	public LibrettoSpecUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
