/*
 * generated by Xtext 2.40.0
 */
package com.robenglander.libretto.spec.tests

import com.google.inject.Inject
import com.robenglander.libretto.spec.librettoProjectProfile.ProjectProfile
import org.eclipse.xtext.testing.InjectWith
import org.eclipse.xtext.testing.extensions.InjectionExtension
import org.eclipse.xtext.testing.util.ParseHelper
import org.junit.jupiter.api.Assertions
import org.junit.jupiter.api.Test
import org.junit.jupiter.api.^extension.ExtendWith

@ExtendWith(InjectionExtension)
@InjectWith(LibrettoProjectProfileInjectorProvider)
class LibrettoProjectProfileParsingTest {
	@Inject
	ParseHelper<ProjectProfile> parseHelper
	
	@Test
	def void loadMinimalProfile() {
		val result = parseHelper.parse('''
			profile "1" {
			  surface {
			    returnType method getJoint as boolean;
			    for module "account" {
			      paramType name simulationPeriod as java.time.YearMonth;
			      recordSelfReturn plus, minus, times, abs;
			      methodOverride tax() returns com.example.TaxBehaviorOperations;
			    }
			  }
			}
		''')
		Assertions.assertNotNull(result)
		val errors = result.eResource.errors
		Assertions.assertTrue(errors.isEmpty, '''Unexpected errors: «errors.join(", ")»''')
	}

	@Test
	def void loadProfileWithName() {
		val result = parseHelper.parse('''
			profile "lumiscape" {
			  surface {
			  }
			}
		''')
		Assertions.assertNotNull(result)
		Assertions.assertTrue(result.eResource.errors.isEmpty)
	}

	@Test
	def void loadProfileWithProjectModules() {
		val result = parseHelper.parse('''
			profile "lumiscape" {
			  project {
			    rootDir "."
			    modules {
			      module "common" {
			        dir "common"
			        specsDir "src/spec/public"
			        testsDir "src/test/java"
			        mainJavaDir "src/main/java"
			        basePackage "com.lumiscape.common"
			      }
			    }
			    testgen {
			      forbiddenPatterns ["...", "TODO", "implement later"]
			      maxRetries 1
			      parseCheck true
			      remediationRules {
			        rule "FORBIDDEN_PATTERN" instruction "Replace placeholders with executable statements."
			        rule "UNPARSEABLE_SYNTHESIS" instruction "Return method body statements only with valid Java syntax."
			      }
			      usage {
			        primary "local-default"
			        secondary "openai-fast"
			        escalation {
			          enabled true
			          escalateAtRetry 2
			          target secondary
			        }
			      }
			      forModule "account" {
			        maxRetries 2
			        parseCheck false
			        remediationRules {
			          rule "FORBIDDEN_PATTERN:TODO" instruction "Eliminate TODO and provide concrete setup/assertions."
			        }
			        usage {
			          primary "ollama-qwen"
			          secondary "openai-fast"
			          escalation {
			            enabled true
			            escalateAtRetry 1
			            target secondary
			          }
			        }
			      }
			    }
			  }
			  llmProviders {
			    provider "local-default" {
			      kind local
			      localModelPath "/models/local.bin"
			    }
			    provider "openai-fast" {
			      kind openai
			      model "gpt-5.4-mini"
			    }
			    provider "ollama-qwen" {
			      kind ollama
			      model "qwen2.5-coder:14b"
			      endpoint "http://localhost:11434"
			    }
			  }
			  surface {
			  }
			}
		''')
		Assertions.assertNotNull(result)
		val errors = result.eResource.errors
		Assertions.assertTrue(errors.isEmpty, '''Unexpected errors: «errors.join(", ")»''')
	}

	@Test
	def void loadProfileWithStructuredRemediations() {
		val result = parseHelper.parse('''
			profile "lumiscape" {
			  project {
			    rootDir "."
			    modules {
			      module "common" {
			        dir "common"
			        specsDir "src/spec/public"
			        testsDir "src/test/java"
			        mainJavaDir "src/main/java"
			        basePackage "com.lumiscape.common"
			      }
			    }
			    testgen {
			      initialInstruction "Never use placeholders."
			      remediations {
			        maxRetries 2
			        parseCheck true
			        defaultCorrection "Generic retry."
			        rules {
			          rule {
			            pattern "TODO"
			            code "FORBIDDEN_PATTERN"
			            correction "Remove TODO markers."
			          }
			          default {
			            code "UNPARSEABLE_SYNTHESIS"
			            correction "Fix Java syntax."
			          }
			        }
			      }
			      usage {
			        primary "local-default"
			      }
			    }
			  }
			  llmProviders {
			    provider "local-default" {
			      kind local
			      localModelPath "/models/local.bin"
			    }
			  }
			  surface {
			  }
			}
		''')
		Assertions.assertNotNull(result)
		val errors = result.eResource.errors
		Assertions.assertTrue(errors.isEmpty, '''Unexpected errors: «errors.join(", ")»''')
	}

	@Test
	def void rejectsMissingProjectSection() {
		val result = parseHelper.parse('''
			profile "lumiscape" {
			  surface {
			  }
			}
		''')
		Assertions.assertNotNull(result)
		val issues = result.eResource.errors.map[it.message]
		Assertions.assertTrue(issues.exists[it.contains("project { ... } is required exactly once.")], '''Unexpected errors: «issues.join(", ")»''')
	}

	@Test
	def void rejectsMissingRootDir() {
		val result = parseHelper.parse('''
			profile "lumiscape" {
			  project {
			    modules {
			      module "common" {
			        dir "common";
			      }
			    }
			  }
			  surface {
			  }
			}
		''')
		Assertions.assertNotNull(result)
		val issues = result.eResource.errors.map[it.message]
		Assertions.assertTrue(issues.exists[it.contains("project.rootDir is required exactly once.")], '''Unexpected errors: «issues.join(", ")»''')
	}

	@Test
	def void rejectsMissingModulesSection() {
		val result = parseHelper.parse('''
			profile "lumiscape" {
			  project {
			    rootDir ".";
			  }
			  surface {
			  }
			}
		''')
		Assertions.assertNotNull(result)
		val issues = result.eResource.errors.map[it.message]
		Assertions.assertTrue(issues.exists[it.contains("project.modules { ... } is required exactly once.")], '''Unexpected errors: «issues.join(", ")»''')
	}

	@Test
	def void rejectsEmptyModulesSection() {
		val result = parseHelper.parse('''
			profile "lumiscape" {
			  project {
			    rootDir ".";
			    modules {
			    }
			  }
			  surface {
			  }
			}
		''')
		Assertions.assertNotNull(result)
		val issues = result.eResource.errors.map[it.message]
		Assertions.assertTrue(issues.exists[it.contains("project.modules must contain at least one module.")], '''Unexpected errors: «issues.join(", ")»''')
	}
}
