/*
 * generated by Xtext 2.40.0
 */
package com.robenglander.libretto.spec.tests

import com.google.inject.Inject
import com.robenglander.libretto.spec.librettoProjectProfile.ProjectProfile
import org.eclipse.xtext.testing.InjectWith
import org.eclipse.xtext.testing.extensions.InjectionExtension
import org.eclipse.xtext.testing.util.ParseHelper
import org.junit.jupiter.api.Assertions
import org.junit.jupiter.api.Test
import org.junit.jupiter.api.^extension.ExtendWith

@ExtendWith(InjectionExtension)
@InjectWith(LibrettoProjectProfileInjectorProvider)
class LibrettoProjectProfileParsingTest {
	@Inject
	ParseHelper<ProjectProfile> parseHelper
	
	@Test
	def void loadMinimalProfile() {
		val result = parseHelper.parse('''
			profile "1" {
			  surface {
			    returnType method getJoint as boolean;
			    for module "account" {
			      paramType name simulationPeriod as java.time.YearMonth;
			      recordSelfReturn plus, minus, times, abs;
			      methodOverride tax() returns com.example.TaxBehaviorOperations;
			    }
			  }
			}
		''')
		Assertions.assertNotNull(result)
		val errors = result.eResource.errors
		Assertions.assertTrue(errors.isEmpty, '''Unexpected errors: «errors.join(", ")»''')
	}

	@Test
	def void loadProfileWithName() {
		val result = parseHelper.parse('''
			profile "lumiscape" {
			  surface {
			  }
			}
		''')
		Assertions.assertNotNull(result)
		Assertions.assertTrue(result.eResource.errors.isEmpty)
	}

	@Test
	def void loadProfileWithProjectModules() {
		val result = parseHelper.parse('''
			profile "lumiscape" {
			  project {
			    rootDir ".";
			    modules {
			      module "common" {
			        dir "common";
			        specsDir "src/spec/public";
			        testsDir "src/test/java";
			        mainJavaDir "src/main/java";
			        basePackage "com.lumiscape.common";
			      }
			    }
			  }
			  surface {
			  }
			}
		''')
		Assertions.assertNotNull(result)
		val errors = result.eResource.errors
		Assertions.assertTrue(errors.isEmpty, '''Unexpected errors: «errors.join(", ")»''')
	}

	@Test
	def void rejectsMissingProjectSection() {
		val result = parseHelper.parse('''
			profile "lumiscape" {
			  surface {
			  }
			}
		''')
		Assertions.assertNotNull(result)
		val issues = result.eResource.errors.map[it.message]
		Assertions.assertTrue(issues.exists[it.contains("project { ... } is required exactly once.")], '''Unexpected errors: «issues.join(", ")»''')
	}

	@Test
	def void rejectsMissingRootDir() {
		val result = parseHelper.parse('''
			profile "lumiscape" {
			  project {
			    modules {
			      module "common" {
			        dir "common";
			      }
			    }
			  }
			  surface {
			  }
			}
		''')
		Assertions.assertNotNull(result)
		val issues = result.eResource.errors.map[it.message]
		Assertions.assertTrue(issues.exists[it.contains("project.rootDir is required exactly once.")], '''Unexpected errors: «issues.join(", ")»''')
	}

	@Test
	def void rejectsMissingModulesSection() {
		val result = parseHelper.parse('''
			profile "lumiscape" {
			  project {
			    rootDir ".";
			  }
			  surface {
			  }
			}
		''')
		Assertions.assertNotNull(result)
		val issues = result.eResource.errors.map[it.message]
		Assertions.assertTrue(issues.exists[it.contains("project.modules { ... } is required exactly once.")], '''Unexpected errors: «issues.join(", ")»''')
	}

	@Test
	def void rejectsEmptyModulesSection() {
		val result = parseHelper.parse('''
			profile "lumiscape" {
			  project {
			    rootDir ".";
			    modules {
			    }
			  }
			  surface {
			  }
			}
		''')
		Assertions.assertNotNull(result)
		val issues = result.eResource.errors.map[it.message]
		Assertions.assertTrue(issues.exists[it.contains("project.modules must contain at least one module.")], '''Unexpected errors: «issues.join(", ")»''')
	}
}
