/**
 * generated by Xtext 2.40.0
 */
package com.robenglander.libretto.spec.librettoProjectProfile;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Correction</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.robenglander.libretto.spec.librettoProjectProfile.Correction#getKeyword <em>Keyword</em>}</li>
 *   <li>{@link com.robenglander.libretto.spec.librettoProjectProfile.Correction#getCorrection <em>Correction</em>}</li>
 * </ul>
 *
 * @see com.robenglander.libretto.spec.librettoProjectProfile.LibrettoProjectProfilePackage#getCorrection()
 * @model
 * @generated
 */
public interface Correction extends EObject
{
  /**
   * Returns the value of the '<em><b>Keyword</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Keyword</em>' containment reference.
   * @see #setKeyword(CorrectionKeyword)
   * @see com.robenglander.libretto.spec.librettoProjectProfile.LibrettoProjectProfilePackage#getCorrection_Keyword()
   * @model containment="true"
   * @generated
   */
  CorrectionKeyword getKeyword();

  /**
   * Sets the value of the '{@link com.robenglander.libretto.spec.librettoProjectProfile.Correction#getKeyword <em>Keyword</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Keyword</em>' containment reference.
   * @see #getKeyword()
   * @generated
   */
  void setKeyword(CorrectionKeyword value);

  /**
   * Returns the value of the '<em><b>Correction</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Correction</em>' attribute.
   * @see #setCorrection(String)
   * @see com.robenglander.libretto.spec.librettoProjectProfile.LibrettoProjectProfilePackage#getCorrection_Correction()
   * @model
   * @generated
   */
  String getCorrection();

  /**
   * Sets the value of the '{@link com.robenglander.libretto.spec.librettoProjectProfile.Correction#getCorrection <em>Correction</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Correction</em>' attribute.
   * @see #getCorrection()
   * @generated
   */
  void setCorrection(String value);

} // Correction
