/**
 * generated by Xtext 2.40.0
 */
package com.robenglander.libretto.spec.librettoProjectProfile;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Gen Pattern Remediation Rule</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.robenglander.libretto.spec.librettoProjectProfile.GenPatternRemediationRule#getKeyword <em>Keyword</em>}</li>
 *   <li>{@link com.robenglander.libretto.spec.librettoProjectProfile.GenPatternRemediationRule#getPatterns <em>Patterns</em>}</li>
 *   <li>{@link com.robenglander.libretto.spec.librettoProjectProfile.GenPatternRemediationRule#getCodes <em>Codes</em>}</li>
 *   <li>{@link com.robenglander.libretto.spec.librettoProjectProfile.GenPatternRemediationRule#getCorrections <em>Corrections</em>}</li>
 * </ul>
 *
 * @see com.robenglander.libretto.spec.librettoProjectProfile.LibrettoProjectProfilePackage#getGenPatternRemediationRule()
 * @model
 * @generated
 */
public interface GenPatternRemediationRule extends EObject
{
  /**
   * Returns the value of the '<em><b>Keyword</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Keyword</em>' containment reference.
   * @see #setKeyword(RuleKeyword)
   * @see com.robenglander.libretto.spec.librettoProjectProfile.LibrettoProjectProfilePackage#getGenPatternRemediationRule_Keyword()
   * @model containment="true"
   * @generated
   */
  RuleKeyword getKeyword();

  /**
   * Sets the value of the '{@link com.robenglander.libretto.spec.librettoProjectProfile.GenPatternRemediationRule#getKeyword <em>Keyword</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Keyword</em>' containment reference.
   * @see #getKeyword()
   * @generated
   */
  void setKeyword(RuleKeyword value);

  /**
   * Returns the value of the '<em><b>Patterns</b></em>' containment reference list.
   * The list contents are of type {@link com.robenglander.libretto.spec.librettoProjectProfile.Pattern}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Patterns</em>' containment reference list.
   * @see com.robenglander.libretto.spec.librettoProjectProfile.LibrettoProjectProfilePackage#getGenPatternRemediationRule_Patterns()
   * @model containment="true"
   * @generated
   */
  EList<Pattern> getPatterns();

  /**
   * Returns the value of the '<em><b>Codes</b></em>' containment reference list.
   * The list contents are of type {@link com.robenglander.libretto.spec.librettoProjectProfile.Code}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Codes</em>' containment reference list.
   * @see com.robenglander.libretto.spec.librettoProjectProfile.LibrettoProjectProfilePackage#getGenPatternRemediationRule_Codes()
   * @model containment="true"
   * @generated
   */
  EList<Code> getCodes();

  /**
   * Returns the value of the '<em><b>Corrections</b></em>' containment reference list.
   * The list contents are of type {@link com.robenglander.libretto.spec.librettoProjectProfile.Correction}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Corrections</em>' containment reference list.
   * @see com.robenglander.libretto.spec.librettoProjectProfile.LibrettoProjectProfilePackage#getGenPatternRemediationRule_Corrections()
   * @model containment="true"
   * @generated
   */
  EList<Correction> getCorrections();

} // GenPatternRemediationRule
