/**
 * generated by Xtext 2.40.0
 */
package com.robenglander.libretto.spec.librettoProjectProfile;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Gen Usage Block</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.robenglander.libretto.spec.librettoProjectProfile.GenUsageBlock#getKeyword <em>Keyword</em>}</li>
 *   <li>{@link com.robenglander.libretto.spec.librettoProjectProfile.GenUsageBlock#getPrimaryProviders <em>Primary Providers</em>}</li>
 *   <li>{@link com.robenglander.libretto.spec.librettoProjectProfile.GenUsageBlock#getSecondaryProviders <em>Secondary Providers</em>}</li>
 *   <li>{@link com.robenglander.libretto.spec.librettoProjectProfile.GenUsageBlock#getEscalations <em>Escalations</em>}</li>
 * </ul>
 *
 * @see com.robenglander.libretto.spec.librettoProjectProfile.LibrettoProjectProfilePackage#getGenUsageBlock()
 * @model
 * @generated
 */
public interface GenUsageBlock extends EObject
{
  /**
   * Returns the value of the '<em><b>Keyword</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Keyword</em>' containment reference.
   * @see #setKeyword(ModelUsageKeyword)
   * @see com.robenglander.libretto.spec.librettoProjectProfile.LibrettoProjectProfilePackage#getGenUsageBlock_Keyword()
   * @model containment="true"
   * @generated
   */
  ModelUsageKeyword getKeyword();

  /**
   * Sets the value of the '{@link com.robenglander.libretto.spec.librettoProjectProfile.GenUsageBlock#getKeyword <em>Keyword</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Keyword</em>' containment reference.
   * @see #getKeyword()
   * @generated
   */
  void setKeyword(ModelUsageKeyword value);

  /**
   * Returns the value of the '<em><b>Primary Providers</b></em>' containment reference list.
   * The list contents are of type {@link com.robenglander.libretto.spec.librettoProjectProfile.PrimaryProvider}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Primary Providers</em>' containment reference list.
   * @see com.robenglander.libretto.spec.librettoProjectProfile.LibrettoProjectProfilePackage#getGenUsageBlock_PrimaryProviders()
   * @model containment="true"
   * @generated
   */
  EList<PrimaryProvider> getPrimaryProviders();

  /**
   * Returns the value of the '<em><b>Secondary Providers</b></em>' containment reference list.
   * The list contents are of type {@link com.robenglander.libretto.spec.librettoProjectProfile.SecondaryProvider}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Secondary Providers</em>' containment reference list.
   * @see com.robenglander.libretto.spec.librettoProjectProfile.LibrettoProjectProfilePackage#getGenUsageBlock_SecondaryProviders()
   * @model containment="true"
   * @generated
   */
  EList<SecondaryProvider> getSecondaryProviders();

  /**
   * Returns the value of the '<em><b>Escalations</b></em>' containment reference list.
   * The list contents are of type {@link com.robenglander.libretto.spec.librettoProjectProfile.GenEscalationBlock}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Escalations</em>' containment reference list.
   * @see com.robenglander.libretto.spec.librettoProjectProfile.LibrettoProjectProfilePackage#getGenUsageBlock_Escalations()
   * @model containment="true"
   * @generated
   */
  EList<GenEscalationBlock> getEscalations();

} // GenUsageBlock
