/**
 * generated by Xtext 2.40.0
 */
package com.robenglander.libretto.spec.librettoProjectProfile;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see com.robenglander.libretto.spec.librettoProjectProfile.LibrettoProjectProfileFactory
 * @model kind="package"
 * @generated
 */
public interface LibrettoProjectProfilePackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "librettoProjectProfile";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.robenglander.com/libretto/spec/LibrettoProjectProfile";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "librettoProjectProfile";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  LibrettoProjectProfilePackage eINSTANCE = com.robenglander.libretto.spec.librettoProjectProfile.impl.LibrettoProjectProfilePackageImpl.init();

  /**
   * The meta object id for the '{@link com.robenglander.libretto.spec.librettoProjectProfile.impl.ProjectProfileImpl <em>Project Profile</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.robenglander.libretto.spec.librettoProjectProfile.impl.ProjectProfileImpl
   * @see com.robenglander.libretto.spec.librettoProjectProfile.impl.LibrettoProjectProfilePackageImpl#getProjectProfile()
   * @generated
   */
  int PROJECT_PROFILE = 0;

  /**
   * The feature id for the '<em><b>Profile Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROJECT_PROFILE__PROFILE_NAME = 0;

  /**
   * The feature id for the '<em><b>Project</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROJECT_PROFILE__PROJECT = 1;

  /**
   * The feature id for the '<em><b>Surface</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROJECT_PROFILE__SURFACE = 2;

  /**
   * The number of structural features of the '<em>Project Profile</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROJECT_PROFILE_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link com.robenglander.libretto.spec.librettoProjectProfile.impl.ProjectBlockImpl <em>Project Block</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.robenglander.libretto.spec.librettoProjectProfile.impl.ProjectBlockImpl
   * @see com.robenglander.libretto.spec.librettoProjectProfile.impl.LibrettoProjectProfilePackageImpl#getProjectBlock()
   * @generated
   */
  int PROJECT_BLOCK = 1;

  /**
   * The feature id for the '<em><b>Root Dir</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROJECT_BLOCK__ROOT_DIR = 0;

  /**
   * The feature id for the '<em><b>Modules</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROJECT_BLOCK__MODULES = 1;

  /**
   * The number of structural features of the '<em>Project Block</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROJECT_BLOCK_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link com.robenglander.libretto.spec.librettoProjectProfile.impl.ModulesBlockImpl <em>Modules Block</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.robenglander.libretto.spec.librettoProjectProfile.impl.ModulesBlockImpl
   * @see com.robenglander.libretto.spec.librettoProjectProfile.impl.LibrettoProjectProfilePackageImpl#getModulesBlock()
   * @generated
   */
  int MODULES_BLOCK = 2;

  /**
   * The feature id for the '<em><b>Modules</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODULES_BLOCK__MODULES = 0;

  /**
   * The number of structural features of the '<em>Modules Block</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODULES_BLOCK_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link com.robenglander.libretto.spec.librettoProjectProfile.impl.ProjectModuleImpl <em>Project Module</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.robenglander.libretto.spec.librettoProjectProfile.impl.ProjectModuleImpl
   * @see com.robenglander.libretto.spec.librettoProjectProfile.impl.LibrettoProjectProfilePackageImpl#getProjectModule()
   * @generated
   */
  int PROJECT_MODULE = 3;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROJECT_MODULE__NAME = 0;

  /**
   * The feature id for the '<em><b>Dir</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROJECT_MODULE__DIR = 1;

  /**
   * The feature id for the '<em><b>Specs Dir</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROJECT_MODULE__SPECS_DIR = 2;

  /**
   * The feature id for the '<em><b>Tests Dir</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROJECT_MODULE__TESTS_DIR = 3;

  /**
   * The feature id for the '<em><b>Main Java Dir</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROJECT_MODULE__MAIN_JAVA_DIR = 4;

  /**
   * The feature id for the '<em><b>Base Package</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROJECT_MODULE__BASE_PACKAGE = 5;

  /**
   * The number of structural features of the '<em>Project Module</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROJECT_MODULE_FEATURE_COUNT = 6;

  /**
   * The meta object id for the '{@link com.robenglander.libretto.spec.librettoProjectProfile.impl.SurfaceBlockImpl <em>Surface Block</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.robenglander.libretto.spec.librettoProjectProfile.impl.SurfaceBlockImpl
   * @see com.robenglander.libretto.spec.librettoProjectProfile.impl.LibrettoProjectProfilePackageImpl#getSurfaceBlock()
   * @generated
   */
  int SURFACE_BLOCK = 4;

  /**
   * The feature id for the '<em><b>Elements</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SURFACE_BLOCK__ELEMENTS = 0;

  /**
   * The number of structural features of the '<em>Surface Block</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SURFACE_BLOCK_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link com.robenglander.libretto.spec.librettoProjectProfile.impl.SurfaceElementImpl <em>Surface Element</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.robenglander.libretto.spec.librettoProjectProfile.impl.SurfaceElementImpl
   * @see com.robenglander.libretto.spec.librettoProjectProfile.impl.LibrettoProjectProfilePackageImpl#getSurfaceElement()
   * @generated
   */
  int SURFACE_ELEMENT = 5;

  /**
   * The number of structural features of the '<em>Surface Element</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SURFACE_ELEMENT_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link com.robenglander.libretto.spec.librettoProjectProfile.impl.ScopedSurfaceImpl <em>Scoped Surface</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.robenglander.libretto.spec.librettoProjectProfile.impl.ScopedSurfaceImpl
   * @see com.robenglander.libretto.spec.librettoProjectProfile.impl.LibrettoProjectProfilePackageImpl#getScopedSurface()
   * @generated
   */
  int SCOPED_SURFACE = 6;

  /**
   * The feature id for the '<em><b>Module Id</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SCOPED_SURFACE__MODULE_ID = SURFACE_ELEMENT_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Spec Id</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SCOPED_SURFACE__SPEC_ID = SURFACE_ELEMENT_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Rules</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SCOPED_SURFACE__RULES = SURFACE_ELEMENT_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>Scoped Surface</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SCOPED_SURFACE_FEATURE_COUNT = SURFACE_ELEMENT_FEATURE_COUNT + 3;

  /**
   * The meta object id for the '{@link com.robenglander.libretto.spec.librettoProjectProfile.impl.SurfaceRuleImpl <em>Surface Rule</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.robenglander.libretto.spec.librettoProjectProfile.impl.SurfaceRuleImpl
   * @see com.robenglander.libretto.spec.librettoProjectProfile.impl.LibrettoProjectProfilePackageImpl#getSurfaceRule()
   * @generated
   */
  int SURFACE_RULE = 7;

  /**
   * The number of structural features of the '<em>Surface Rule</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SURFACE_RULE_FEATURE_COUNT = SURFACE_ELEMENT_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link com.robenglander.libretto.spec.librettoProjectProfile.impl.ReturnTypeRuleImpl <em>Return Type Rule</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.robenglander.libretto.spec.librettoProjectProfile.impl.ReturnTypeRuleImpl
   * @see com.robenglander.libretto.spec.librettoProjectProfile.impl.LibrettoProjectProfilePackageImpl#getReturnTypeRule()
   * @generated
   */
  int RETURN_TYPE_RULE = 8;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RETURN_TYPE_RULE__NAME = SURFACE_RULE_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Java Type</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RETURN_TYPE_RULE__JAVA_TYPE = SURFACE_RULE_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Return Type Rule</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RETURN_TYPE_RULE_FEATURE_COUNT = SURFACE_RULE_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link com.robenglander.libretto.spec.librettoProjectProfile.impl.ParamTypeRuleImpl <em>Param Type Rule</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.robenglander.libretto.spec.librettoProjectProfile.impl.ParamTypeRuleImpl
   * @see com.robenglander.libretto.spec.librettoProjectProfile.impl.LibrettoProjectProfilePackageImpl#getParamTypeRule()
   * @generated
   */
  int PARAM_TYPE_RULE = 9;

  /**
   * The feature id for the '<em><b>Param Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARAM_TYPE_RULE__PARAM_NAME = SURFACE_RULE_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Java Type</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARAM_TYPE_RULE__JAVA_TYPE = SURFACE_RULE_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Param Type Rule</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARAM_TYPE_RULE_FEATURE_COUNT = SURFACE_RULE_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link com.robenglander.libretto.spec.librettoProjectProfile.impl.RecordSelfReturnRuleImpl <em>Record Self Return Rule</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.robenglander.libretto.spec.librettoProjectProfile.impl.RecordSelfReturnRuleImpl
   * @see com.robenglander.libretto.spec.librettoProjectProfile.impl.LibrettoProjectProfilePackageImpl#getRecordSelfReturnRule()
   * @generated
   */
  int RECORD_SELF_RETURN_RULE = 10;

  /**
   * The feature id for the '<em><b>Methods</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RECORD_SELF_RETURN_RULE__METHODS = SURFACE_RULE_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Record Self Return Rule</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RECORD_SELF_RETURN_RULE_FEATURE_COUNT = SURFACE_RULE_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link com.robenglander.libretto.spec.librettoProjectProfile.impl.MethodOverrideRuleImpl <em>Method Override Rule</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.robenglander.libretto.spec.librettoProjectProfile.impl.MethodOverrideRuleImpl
   * @see com.robenglander.libretto.spec.librettoProjectProfile.impl.LibrettoProjectProfilePackageImpl#getMethodOverrideRule()
   * @generated
   */
  int METHOD_OVERRIDE_RULE = 11;

  /**
   * The feature id for the '<em><b>Signature</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int METHOD_OVERRIDE_RULE__SIGNATURE = SURFACE_RULE_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Java Type</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int METHOD_OVERRIDE_RULE__JAVA_TYPE = SURFACE_RULE_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Method Override Rule</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int METHOD_OVERRIDE_RULE_FEATURE_COUNT = SURFACE_RULE_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link com.robenglander.libretto.spec.librettoProjectProfile.impl.JavaTypeImpl <em>Java Type</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.robenglander.libretto.spec.librettoProjectProfile.impl.JavaTypeImpl
   * @see com.robenglander.libretto.spec.librettoProjectProfile.impl.LibrettoProjectProfilePackageImpl#getJavaType()
   * @generated
   */
  int JAVA_TYPE = 12;

  /**
   * The number of structural features of the '<em>Java Type</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int JAVA_TYPE_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link com.robenglander.libretto.spec.librettoProjectProfile.impl.QualifiedNameImpl <em>Qualified Name</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.robenglander.libretto.spec.librettoProjectProfile.impl.QualifiedNameImpl
   * @see com.robenglander.libretto.spec.librettoProjectProfile.impl.LibrettoProjectProfilePackageImpl#getQualifiedName()
   * @generated
   */
  int QUALIFIED_NAME = 13;

  /**
   * The feature id for the '<em><b>Segments</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int QUALIFIED_NAME__SEGMENTS = JAVA_TYPE_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Qualified Name</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int QUALIFIED_NAME_FEATURE_COUNT = JAVA_TYPE_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link com.robenglander.libretto.spec.librettoProjectProfile.impl.PrimitiveTypeImpl <em>Primitive Type</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.robenglander.libretto.spec.librettoProjectProfile.impl.PrimitiveTypeImpl
   * @see com.robenglander.libretto.spec.librettoProjectProfile.impl.LibrettoProjectProfilePackageImpl#getPrimitiveType()
   * @generated
   */
  int PRIMITIVE_TYPE = 14;

  /**
   * The feature id for the '<em><b>Kind</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PRIMITIVE_TYPE__KIND = JAVA_TYPE_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Primitive Type</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PRIMITIVE_TYPE_FEATURE_COUNT = JAVA_TYPE_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link com.robenglander.libretto.spec.librettoProjectProfile.impl.OperationSignatureImpl <em>Operation Signature</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.robenglander.libretto.spec.librettoProjectProfile.impl.OperationSignatureImpl
   * @see com.robenglander.libretto.spec.librettoProjectProfile.impl.LibrettoProjectProfilePackageImpl#getOperationSignature()
   * @generated
   */
  int OPERATION_SIGNATURE = 15;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OPERATION_SIGNATURE__NAME = 0;

  /**
   * The feature id for the '<em><b>Params</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OPERATION_SIGNATURE__PARAMS = 1;

  /**
   * The number of structural features of the '<em>Operation Signature</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OPERATION_SIGNATURE_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link com.robenglander.libretto.spec.librettoProjectProfile.impl.TypedParamImpl <em>Typed Param</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.robenglander.libretto.spec.librettoProjectProfile.impl.TypedParamImpl
   * @see com.robenglander.libretto.spec.librettoProjectProfile.impl.LibrettoProjectProfilePackageImpl#getTypedParam()
   * @generated
   */
  int TYPED_PARAM = 16;

  /**
   * The feature id for the '<em><b>Type</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TYPED_PARAM__TYPE = 0;

  /**
   * The feature id for the '<em><b>Param Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TYPED_PARAM__PARAM_NAME = 1;

  /**
   * The number of structural features of the '<em>Typed Param</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TYPED_PARAM_FEATURE_COUNT = 2;


  /**
   * Returns the meta object for class '{@link com.robenglander.libretto.spec.librettoProjectProfile.ProjectProfile <em>Project Profile</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Project Profile</em>'.
   * @see com.robenglander.libretto.spec.librettoProjectProfile.ProjectProfile
   * @generated
   */
  EClass getProjectProfile();

  /**
   * Returns the meta object for the attribute '{@link com.robenglander.libretto.spec.librettoProjectProfile.ProjectProfile#getProfileName <em>Profile Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Profile Name</em>'.
   * @see com.robenglander.libretto.spec.librettoProjectProfile.ProjectProfile#getProfileName()
   * @see #getProjectProfile()
   * @generated
   */
  EAttribute getProjectProfile_ProfileName();

  /**
   * Returns the meta object for the containment reference '{@link com.robenglander.libretto.spec.librettoProjectProfile.ProjectProfile#getProject <em>Project</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Project</em>'.
   * @see com.robenglander.libretto.spec.librettoProjectProfile.ProjectProfile#getProject()
   * @see #getProjectProfile()
   * @generated
   */
  EReference getProjectProfile_Project();

  /**
   * Returns the meta object for the containment reference '{@link com.robenglander.libretto.spec.librettoProjectProfile.ProjectProfile#getSurface <em>Surface</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Surface</em>'.
   * @see com.robenglander.libretto.spec.librettoProjectProfile.ProjectProfile#getSurface()
   * @see #getProjectProfile()
   * @generated
   */
  EReference getProjectProfile_Surface();

  /**
   * Returns the meta object for class '{@link com.robenglander.libretto.spec.librettoProjectProfile.ProjectBlock <em>Project Block</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Project Block</em>'.
   * @see com.robenglander.libretto.spec.librettoProjectProfile.ProjectBlock
   * @generated
   */
  EClass getProjectBlock();

  /**
   * Returns the meta object for the attribute '{@link com.robenglander.libretto.spec.librettoProjectProfile.ProjectBlock#getRootDir <em>Root Dir</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Root Dir</em>'.
   * @see com.robenglander.libretto.spec.librettoProjectProfile.ProjectBlock#getRootDir()
   * @see #getProjectBlock()
   * @generated
   */
  EAttribute getProjectBlock_RootDir();

  /**
   * Returns the meta object for the containment reference '{@link com.robenglander.libretto.spec.librettoProjectProfile.ProjectBlock#getModules <em>Modules</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Modules</em>'.
   * @see com.robenglander.libretto.spec.librettoProjectProfile.ProjectBlock#getModules()
   * @see #getProjectBlock()
   * @generated
   */
  EReference getProjectBlock_Modules();

  /**
   * Returns the meta object for class '{@link com.robenglander.libretto.spec.librettoProjectProfile.ModulesBlock <em>Modules Block</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Modules Block</em>'.
   * @see com.robenglander.libretto.spec.librettoProjectProfile.ModulesBlock
   * @generated
   */
  EClass getModulesBlock();

  /**
   * Returns the meta object for the containment reference list '{@link com.robenglander.libretto.spec.librettoProjectProfile.ModulesBlock#getModules <em>Modules</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Modules</em>'.
   * @see com.robenglander.libretto.spec.librettoProjectProfile.ModulesBlock#getModules()
   * @see #getModulesBlock()
   * @generated
   */
  EReference getModulesBlock_Modules();

  /**
   * Returns the meta object for class '{@link com.robenglander.libretto.spec.librettoProjectProfile.ProjectModule <em>Project Module</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Project Module</em>'.
   * @see com.robenglander.libretto.spec.librettoProjectProfile.ProjectModule
   * @generated
   */
  EClass getProjectModule();

  /**
   * Returns the meta object for the attribute '{@link com.robenglander.libretto.spec.librettoProjectProfile.ProjectModule#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see com.robenglander.libretto.spec.librettoProjectProfile.ProjectModule#getName()
   * @see #getProjectModule()
   * @generated
   */
  EAttribute getProjectModule_Name();

  /**
   * Returns the meta object for the attribute '{@link com.robenglander.libretto.spec.librettoProjectProfile.ProjectModule#getDir <em>Dir</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Dir</em>'.
   * @see com.robenglander.libretto.spec.librettoProjectProfile.ProjectModule#getDir()
   * @see #getProjectModule()
   * @generated
   */
  EAttribute getProjectModule_Dir();

  /**
   * Returns the meta object for the attribute '{@link com.robenglander.libretto.spec.librettoProjectProfile.ProjectModule#getSpecsDir <em>Specs Dir</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Specs Dir</em>'.
   * @see com.robenglander.libretto.spec.librettoProjectProfile.ProjectModule#getSpecsDir()
   * @see #getProjectModule()
   * @generated
   */
  EAttribute getProjectModule_SpecsDir();

  /**
   * Returns the meta object for the attribute '{@link com.robenglander.libretto.spec.librettoProjectProfile.ProjectModule#getTestsDir <em>Tests Dir</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Tests Dir</em>'.
   * @see com.robenglander.libretto.spec.librettoProjectProfile.ProjectModule#getTestsDir()
   * @see #getProjectModule()
   * @generated
   */
  EAttribute getProjectModule_TestsDir();

  /**
   * Returns the meta object for the attribute '{@link com.robenglander.libretto.spec.librettoProjectProfile.ProjectModule#getMainJavaDir <em>Main Java Dir</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Main Java Dir</em>'.
   * @see com.robenglander.libretto.spec.librettoProjectProfile.ProjectModule#getMainJavaDir()
   * @see #getProjectModule()
   * @generated
   */
  EAttribute getProjectModule_MainJavaDir();

  /**
   * Returns the meta object for the attribute '{@link com.robenglander.libretto.spec.librettoProjectProfile.ProjectModule#getBasePackage <em>Base Package</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Base Package</em>'.
   * @see com.robenglander.libretto.spec.librettoProjectProfile.ProjectModule#getBasePackage()
   * @see #getProjectModule()
   * @generated
   */
  EAttribute getProjectModule_BasePackage();

  /**
   * Returns the meta object for class '{@link com.robenglander.libretto.spec.librettoProjectProfile.SurfaceBlock <em>Surface Block</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Surface Block</em>'.
   * @see com.robenglander.libretto.spec.librettoProjectProfile.SurfaceBlock
   * @generated
   */
  EClass getSurfaceBlock();

  /**
   * Returns the meta object for the containment reference list '{@link com.robenglander.libretto.spec.librettoProjectProfile.SurfaceBlock#getElements <em>Elements</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Elements</em>'.
   * @see com.robenglander.libretto.spec.librettoProjectProfile.SurfaceBlock#getElements()
   * @see #getSurfaceBlock()
   * @generated
   */
  EReference getSurfaceBlock_Elements();

  /**
   * Returns the meta object for class '{@link com.robenglander.libretto.spec.librettoProjectProfile.SurfaceElement <em>Surface Element</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Surface Element</em>'.
   * @see com.robenglander.libretto.spec.librettoProjectProfile.SurfaceElement
   * @generated
   */
  EClass getSurfaceElement();

  /**
   * Returns the meta object for class '{@link com.robenglander.libretto.spec.librettoProjectProfile.ScopedSurface <em>Scoped Surface</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Scoped Surface</em>'.
   * @see com.robenglander.libretto.spec.librettoProjectProfile.ScopedSurface
   * @generated
   */
  EClass getScopedSurface();

  /**
   * Returns the meta object for the attribute '{@link com.robenglander.libretto.spec.librettoProjectProfile.ScopedSurface#getModuleId <em>Module Id</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Module Id</em>'.
   * @see com.robenglander.libretto.spec.librettoProjectProfile.ScopedSurface#getModuleId()
   * @see #getScopedSurface()
   * @generated
   */
  EAttribute getScopedSurface_ModuleId();

  /**
   * Returns the meta object for the attribute '{@link com.robenglander.libretto.spec.librettoProjectProfile.ScopedSurface#getSpecId <em>Spec Id</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Spec Id</em>'.
   * @see com.robenglander.libretto.spec.librettoProjectProfile.ScopedSurface#getSpecId()
   * @see #getScopedSurface()
   * @generated
   */
  EAttribute getScopedSurface_SpecId();

  /**
   * Returns the meta object for the containment reference list '{@link com.robenglander.libretto.spec.librettoProjectProfile.ScopedSurface#getRules <em>Rules</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Rules</em>'.
   * @see com.robenglander.libretto.spec.librettoProjectProfile.ScopedSurface#getRules()
   * @see #getScopedSurface()
   * @generated
   */
  EReference getScopedSurface_Rules();

  /**
   * Returns the meta object for class '{@link com.robenglander.libretto.spec.librettoProjectProfile.SurfaceRule <em>Surface Rule</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Surface Rule</em>'.
   * @see com.robenglander.libretto.spec.librettoProjectProfile.SurfaceRule
   * @generated
   */
  EClass getSurfaceRule();

  /**
   * Returns the meta object for class '{@link com.robenglander.libretto.spec.librettoProjectProfile.ReturnTypeRule <em>Return Type Rule</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Return Type Rule</em>'.
   * @see com.robenglander.libretto.spec.librettoProjectProfile.ReturnTypeRule
   * @generated
   */
  EClass getReturnTypeRule();

  /**
   * Returns the meta object for the attribute '{@link com.robenglander.libretto.spec.librettoProjectProfile.ReturnTypeRule#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see com.robenglander.libretto.spec.librettoProjectProfile.ReturnTypeRule#getName()
   * @see #getReturnTypeRule()
   * @generated
   */
  EAttribute getReturnTypeRule_Name();

  /**
   * Returns the meta object for the containment reference '{@link com.robenglander.libretto.spec.librettoProjectProfile.ReturnTypeRule#getJavaType <em>Java Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Java Type</em>'.
   * @see com.robenglander.libretto.spec.librettoProjectProfile.ReturnTypeRule#getJavaType()
   * @see #getReturnTypeRule()
   * @generated
   */
  EReference getReturnTypeRule_JavaType();

  /**
   * Returns the meta object for class '{@link com.robenglander.libretto.spec.librettoProjectProfile.ParamTypeRule <em>Param Type Rule</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Param Type Rule</em>'.
   * @see com.robenglander.libretto.spec.librettoProjectProfile.ParamTypeRule
   * @generated
   */
  EClass getParamTypeRule();

  /**
   * Returns the meta object for the attribute '{@link com.robenglander.libretto.spec.librettoProjectProfile.ParamTypeRule#getParamName <em>Param Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Param Name</em>'.
   * @see com.robenglander.libretto.spec.librettoProjectProfile.ParamTypeRule#getParamName()
   * @see #getParamTypeRule()
   * @generated
   */
  EAttribute getParamTypeRule_ParamName();

  /**
   * Returns the meta object for the containment reference '{@link com.robenglander.libretto.spec.librettoProjectProfile.ParamTypeRule#getJavaType <em>Java Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Java Type</em>'.
   * @see com.robenglander.libretto.spec.librettoProjectProfile.ParamTypeRule#getJavaType()
   * @see #getParamTypeRule()
   * @generated
   */
  EReference getParamTypeRule_JavaType();

  /**
   * Returns the meta object for class '{@link com.robenglander.libretto.spec.librettoProjectProfile.RecordSelfReturnRule <em>Record Self Return Rule</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Record Self Return Rule</em>'.
   * @see com.robenglander.libretto.spec.librettoProjectProfile.RecordSelfReturnRule
   * @generated
   */
  EClass getRecordSelfReturnRule();

  /**
   * Returns the meta object for the attribute list '{@link com.robenglander.libretto.spec.librettoProjectProfile.RecordSelfReturnRule#getMethods <em>Methods</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Methods</em>'.
   * @see com.robenglander.libretto.spec.librettoProjectProfile.RecordSelfReturnRule#getMethods()
   * @see #getRecordSelfReturnRule()
   * @generated
   */
  EAttribute getRecordSelfReturnRule_Methods();

  /**
   * Returns the meta object for class '{@link com.robenglander.libretto.spec.librettoProjectProfile.MethodOverrideRule <em>Method Override Rule</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Method Override Rule</em>'.
   * @see com.robenglander.libretto.spec.librettoProjectProfile.MethodOverrideRule
   * @generated
   */
  EClass getMethodOverrideRule();

  /**
   * Returns the meta object for the containment reference '{@link com.robenglander.libretto.spec.librettoProjectProfile.MethodOverrideRule#getSignature <em>Signature</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Signature</em>'.
   * @see com.robenglander.libretto.spec.librettoProjectProfile.MethodOverrideRule#getSignature()
   * @see #getMethodOverrideRule()
   * @generated
   */
  EReference getMethodOverrideRule_Signature();

  /**
   * Returns the meta object for the containment reference '{@link com.robenglander.libretto.spec.librettoProjectProfile.MethodOverrideRule#getJavaType <em>Java Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Java Type</em>'.
   * @see com.robenglander.libretto.spec.librettoProjectProfile.MethodOverrideRule#getJavaType()
   * @see #getMethodOverrideRule()
   * @generated
   */
  EReference getMethodOverrideRule_JavaType();

  /**
   * Returns the meta object for class '{@link com.robenglander.libretto.spec.librettoProjectProfile.JavaType <em>Java Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Java Type</em>'.
   * @see com.robenglander.libretto.spec.librettoProjectProfile.JavaType
   * @generated
   */
  EClass getJavaType();

  /**
   * Returns the meta object for class '{@link com.robenglander.libretto.spec.librettoProjectProfile.QualifiedName <em>Qualified Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Qualified Name</em>'.
   * @see com.robenglander.libretto.spec.librettoProjectProfile.QualifiedName
   * @generated
   */
  EClass getQualifiedName();

  /**
   * Returns the meta object for the attribute list '{@link com.robenglander.libretto.spec.librettoProjectProfile.QualifiedName#getSegments <em>Segments</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Segments</em>'.
   * @see com.robenglander.libretto.spec.librettoProjectProfile.QualifiedName#getSegments()
   * @see #getQualifiedName()
   * @generated
   */
  EAttribute getQualifiedName_Segments();

  /**
   * Returns the meta object for class '{@link com.robenglander.libretto.spec.librettoProjectProfile.PrimitiveType <em>Primitive Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Primitive Type</em>'.
   * @see com.robenglander.libretto.spec.librettoProjectProfile.PrimitiveType
   * @generated
   */
  EClass getPrimitiveType();

  /**
   * Returns the meta object for the attribute '{@link com.robenglander.libretto.spec.librettoProjectProfile.PrimitiveType#getKind <em>Kind</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Kind</em>'.
   * @see com.robenglander.libretto.spec.librettoProjectProfile.PrimitiveType#getKind()
   * @see #getPrimitiveType()
   * @generated
   */
  EAttribute getPrimitiveType_Kind();

  /**
   * Returns the meta object for class '{@link com.robenglander.libretto.spec.librettoProjectProfile.OperationSignature <em>Operation Signature</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Operation Signature</em>'.
   * @see com.robenglander.libretto.spec.librettoProjectProfile.OperationSignature
   * @generated
   */
  EClass getOperationSignature();

  /**
   * Returns the meta object for the attribute '{@link com.robenglander.libretto.spec.librettoProjectProfile.OperationSignature#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see com.robenglander.libretto.spec.librettoProjectProfile.OperationSignature#getName()
   * @see #getOperationSignature()
   * @generated
   */
  EAttribute getOperationSignature_Name();

  /**
   * Returns the meta object for the containment reference list '{@link com.robenglander.libretto.spec.librettoProjectProfile.OperationSignature#getParams <em>Params</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Params</em>'.
   * @see com.robenglander.libretto.spec.librettoProjectProfile.OperationSignature#getParams()
   * @see #getOperationSignature()
   * @generated
   */
  EReference getOperationSignature_Params();

  /**
   * Returns the meta object for class '{@link com.robenglander.libretto.spec.librettoProjectProfile.TypedParam <em>Typed Param</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Typed Param</em>'.
   * @see com.robenglander.libretto.spec.librettoProjectProfile.TypedParam
   * @generated
   */
  EClass getTypedParam();

  /**
   * Returns the meta object for the containment reference '{@link com.robenglander.libretto.spec.librettoProjectProfile.TypedParam#getType <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Type</em>'.
   * @see com.robenglander.libretto.spec.librettoProjectProfile.TypedParam#getType()
   * @see #getTypedParam()
   * @generated
   */
  EReference getTypedParam_Type();

  /**
   * Returns the meta object for the attribute '{@link com.robenglander.libretto.spec.librettoProjectProfile.TypedParam#getParamName <em>Param Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Param Name</em>'.
   * @see com.robenglander.libretto.spec.librettoProjectProfile.TypedParam#getParamName()
   * @see #getTypedParam()
   * @generated
   */
  EAttribute getTypedParam_ParamName();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  LibrettoProjectProfileFactory getLibrettoProjectProfileFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link com.robenglander.libretto.spec.librettoProjectProfile.impl.ProjectProfileImpl <em>Project Profile</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.robenglander.libretto.spec.librettoProjectProfile.impl.ProjectProfileImpl
     * @see com.robenglander.libretto.spec.librettoProjectProfile.impl.LibrettoProjectProfilePackageImpl#getProjectProfile()
     * @generated
     */
    EClass PROJECT_PROFILE = eINSTANCE.getProjectProfile();

    /**
     * The meta object literal for the '<em><b>Profile Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PROJECT_PROFILE__PROFILE_NAME = eINSTANCE.getProjectProfile_ProfileName();

    /**
     * The meta object literal for the '<em><b>Project</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PROJECT_PROFILE__PROJECT = eINSTANCE.getProjectProfile_Project();

    /**
     * The meta object literal for the '<em><b>Surface</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PROJECT_PROFILE__SURFACE = eINSTANCE.getProjectProfile_Surface();

    /**
     * The meta object literal for the '{@link com.robenglander.libretto.spec.librettoProjectProfile.impl.ProjectBlockImpl <em>Project Block</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.robenglander.libretto.spec.librettoProjectProfile.impl.ProjectBlockImpl
     * @see com.robenglander.libretto.spec.librettoProjectProfile.impl.LibrettoProjectProfilePackageImpl#getProjectBlock()
     * @generated
     */
    EClass PROJECT_BLOCK = eINSTANCE.getProjectBlock();

    /**
     * The meta object literal for the '<em><b>Root Dir</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PROJECT_BLOCK__ROOT_DIR = eINSTANCE.getProjectBlock_RootDir();

    /**
     * The meta object literal for the '<em><b>Modules</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PROJECT_BLOCK__MODULES = eINSTANCE.getProjectBlock_Modules();

    /**
     * The meta object literal for the '{@link com.robenglander.libretto.spec.librettoProjectProfile.impl.ModulesBlockImpl <em>Modules Block</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.robenglander.libretto.spec.librettoProjectProfile.impl.ModulesBlockImpl
     * @see com.robenglander.libretto.spec.librettoProjectProfile.impl.LibrettoProjectProfilePackageImpl#getModulesBlock()
     * @generated
     */
    EClass MODULES_BLOCK = eINSTANCE.getModulesBlock();

    /**
     * The meta object literal for the '<em><b>Modules</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MODULES_BLOCK__MODULES = eINSTANCE.getModulesBlock_Modules();

    /**
     * The meta object literal for the '{@link com.robenglander.libretto.spec.librettoProjectProfile.impl.ProjectModuleImpl <em>Project Module</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.robenglander.libretto.spec.librettoProjectProfile.impl.ProjectModuleImpl
     * @see com.robenglander.libretto.spec.librettoProjectProfile.impl.LibrettoProjectProfilePackageImpl#getProjectModule()
     * @generated
     */
    EClass PROJECT_MODULE = eINSTANCE.getProjectModule();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PROJECT_MODULE__NAME = eINSTANCE.getProjectModule_Name();

    /**
     * The meta object literal for the '<em><b>Dir</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PROJECT_MODULE__DIR = eINSTANCE.getProjectModule_Dir();

    /**
     * The meta object literal for the '<em><b>Specs Dir</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PROJECT_MODULE__SPECS_DIR = eINSTANCE.getProjectModule_SpecsDir();

    /**
     * The meta object literal for the '<em><b>Tests Dir</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PROJECT_MODULE__TESTS_DIR = eINSTANCE.getProjectModule_TestsDir();

    /**
     * The meta object literal for the '<em><b>Main Java Dir</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PROJECT_MODULE__MAIN_JAVA_DIR = eINSTANCE.getProjectModule_MainJavaDir();

    /**
     * The meta object literal for the '<em><b>Base Package</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PROJECT_MODULE__BASE_PACKAGE = eINSTANCE.getProjectModule_BasePackage();

    /**
     * The meta object literal for the '{@link com.robenglander.libretto.spec.librettoProjectProfile.impl.SurfaceBlockImpl <em>Surface Block</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.robenglander.libretto.spec.librettoProjectProfile.impl.SurfaceBlockImpl
     * @see com.robenglander.libretto.spec.librettoProjectProfile.impl.LibrettoProjectProfilePackageImpl#getSurfaceBlock()
     * @generated
     */
    EClass SURFACE_BLOCK = eINSTANCE.getSurfaceBlock();

    /**
     * The meta object literal for the '<em><b>Elements</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SURFACE_BLOCK__ELEMENTS = eINSTANCE.getSurfaceBlock_Elements();

    /**
     * The meta object literal for the '{@link com.robenglander.libretto.spec.librettoProjectProfile.impl.SurfaceElementImpl <em>Surface Element</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.robenglander.libretto.spec.librettoProjectProfile.impl.SurfaceElementImpl
     * @see com.robenglander.libretto.spec.librettoProjectProfile.impl.LibrettoProjectProfilePackageImpl#getSurfaceElement()
     * @generated
     */
    EClass SURFACE_ELEMENT = eINSTANCE.getSurfaceElement();

    /**
     * The meta object literal for the '{@link com.robenglander.libretto.spec.librettoProjectProfile.impl.ScopedSurfaceImpl <em>Scoped Surface</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.robenglander.libretto.spec.librettoProjectProfile.impl.ScopedSurfaceImpl
     * @see com.robenglander.libretto.spec.librettoProjectProfile.impl.LibrettoProjectProfilePackageImpl#getScopedSurface()
     * @generated
     */
    EClass SCOPED_SURFACE = eINSTANCE.getScopedSurface();

    /**
     * The meta object literal for the '<em><b>Module Id</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SCOPED_SURFACE__MODULE_ID = eINSTANCE.getScopedSurface_ModuleId();

    /**
     * The meta object literal for the '<em><b>Spec Id</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SCOPED_SURFACE__SPEC_ID = eINSTANCE.getScopedSurface_SpecId();

    /**
     * The meta object literal for the '<em><b>Rules</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SCOPED_SURFACE__RULES = eINSTANCE.getScopedSurface_Rules();

    /**
     * The meta object literal for the '{@link com.robenglander.libretto.spec.librettoProjectProfile.impl.SurfaceRuleImpl <em>Surface Rule</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.robenglander.libretto.spec.librettoProjectProfile.impl.SurfaceRuleImpl
     * @see com.robenglander.libretto.spec.librettoProjectProfile.impl.LibrettoProjectProfilePackageImpl#getSurfaceRule()
     * @generated
     */
    EClass SURFACE_RULE = eINSTANCE.getSurfaceRule();

    /**
     * The meta object literal for the '{@link com.robenglander.libretto.spec.librettoProjectProfile.impl.ReturnTypeRuleImpl <em>Return Type Rule</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.robenglander.libretto.spec.librettoProjectProfile.impl.ReturnTypeRuleImpl
     * @see com.robenglander.libretto.spec.librettoProjectProfile.impl.LibrettoProjectProfilePackageImpl#getReturnTypeRule()
     * @generated
     */
    EClass RETURN_TYPE_RULE = eINSTANCE.getReturnTypeRule();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute RETURN_TYPE_RULE__NAME = eINSTANCE.getReturnTypeRule_Name();

    /**
     * The meta object literal for the '<em><b>Java Type</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference RETURN_TYPE_RULE__JAVA_TYPE = eINSTANCE.getReturnTypeRule_JavaType();

    /**
     * The meta object literal for the '{@link com.robenglander.libretto.spec.librettoProjectProfile.impl.ParamTypeRuleImpl <em>Param Type Rule</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.robenglander.libretto.spec.librettoProjectProfile.impl.ParamTypeRuleImpl
     * @see com.robenglander.libretto.spec.librettoProjectProfile.impl.LibrettoProjectProfilePackageImpl#getParamTypeRule()
     * @generated
     */
    EClass PARAM_TYPE_RULE = eINSTANCE.getParamTypeRule();

    /**
     * The meta object literal for the '<em><b>Param Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PARAM_TYPE_RULE__PARAM_NAME = eINSTANCE.getParamTypeRule_ParamName();

    /**
     * The meta object literal for the '<em><b>Java Type</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PARAM_TYPE_RULE__JAVA_TYPE = eINSTANCE.getParamTypeRule_JavaType();

    /**
     * The meta object literal for the '{@link com.robenglander.libretto.spec.librettoProjectProfile.impl.RecordSelfReturnRuleImpl <em>Record Self Return Rule</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.robenglander.libretto.spec.librettoProjectProfile.impl.RecordSelfReturnRuleImpl
     * @see com.robenglander.libretto.spec.librettoProjectProfile.impl.LibrettoProjectProfilePackageImpl#getRecordSelfReturnRule()
     * @generated
     */
    EClass RECORD_SELF_RETURN_RULE = eINSTANCE.getRecordSelfReturnRule();

    /**
     * The meta object literal for the '<em><b>Methods</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute RECORD_SELF_RETURN_RULE__METHODS = eINSTANCE.getRecordSelfReturnRule_Methods();

    /**
     * The meta object literal for the '{@link com.robenglander.libretto.spec.librettoProjectProfile.impl.MethodOverrideRuleImpl <em>Method Override Rule</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.robenglander.libretto.spec.librettoProjectProfile.impl.MethodOverrideRuleImpl
     * @see com.robenglander.libretto.spec.librettoProjectProfile.impl.LibrettoProjectProfilePackageImpl#getMethodOverrideRule()
     * @generated
     */
    EClass METHOD_OVERRIDE_RULE = eINSTANCE.getMethodOverrideRule();

    /**
     * The meta object literal for the '<em><b>Signature</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference METHOD_OVERRIDE_RULE__SIGNATURE = eINSTANCE.getMethodOverrideRule_Signature();

    /**
     * The meta object literal for the '<em><b>Java Type</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference METHOD_OVERRIDE_RULE__JAVA_TYPE = eINSTANCE.getMethodOverrideRule_JavaType();

    /**
     * The meta object literal for the '{@link com.robenglander.libretto.spec.librettoProjectProfile.impl.JavaTypeImpl <em>Java Type</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.robenglander.libretto.spec.librettoProjectProfile.impl.JavaTypeImpl
     * @see com.robenglander.libretto.spec.librettoProjectProfile.impl.LibrettoProjectProfilePackageImpl#getJavaType()
     * @generated
     */
    EClass JAVA_TYPE = eINSTANCE.getJavaType();

    /**
     * The meta object literal for the '{@link com.robenglander.libretto.spec.librettoProjectProfile.impl.QualifiedNameImpl <em>Qualified Name</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.robenglander.libretto.spec.librettoProjectProfile.impl.QualifiedNameImpl
     * @see com.robenglander.libretto.spec.librettoProjectProfile.impl.LibrettoProjectProfilePackageImpl#getQualifiedName()
     * @generated
     */
    EClass QUALIFIED_NAME = eINSTANCE.getQualifiedName();

    /**
     * The meta object literal for the '<em><b>Segments</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute QUALIFIED_NAME__SEGMENTS = eINSTANCE.getQualifiedName_Segments();

    /**
     * The meta object literal for the '{@link com.robenglander.libretto.spec.librettoProjectProfile.impl.PrimitiveTypeImpl <em>Primitive Type</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.robenglander.libretto.spec.librettoProjectProfile.impl.PrimitiveTypeImpl
     * @see com.robenglander.libretto.spec.librettoProjectProfile.impl.LibrettoProjectProfilePackageImpl#getPrimitiveType()
     * @generated
     */
    EClass PRIMITIVE_TYPE = eINSTANCE.getPrimitiveType();

    /**
     * The meta object literal for the '<em><b>Kind</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PRIMITIVE_TYPE__KIND = eINSTANCE.getPrimitiveType_Kind();

    /**
     * The meta object literal for the '{@link com.robenglander.libretto.spec.librettoProjectProfile.impl.OperationSignatureImpl <em>Operation Signature</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.robenglander.libretto.spec.librettoProjectProfile.impl.OperationSignatureImpl
     * @see com.robenglander.libretto.spec.librettoProjectProfile.impl.LibrettoProjectProfilePackageImpl#getOperationSignature()
     * @generated
     */
    EClass OPERATION_SIGNATURE = eINSTANCE.getOperationSignature();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute OPERATION_SIGNATURE__NAME = eINSTANCE.getOperationSignature_Name();

    /**
     * The meta object literal for the '<em><b>Params</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference OPERATION_SIGNATURE__PARAMS = eINSTANCE.getOperationSignature_Params();

    /**
     * The meta object literal for the '{@link com.robenglander.libretto.spec.librettoProjectProfile.impl.TypedParamImpl <em>Typed Param</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.robenglander.libretto.spec.librettoProjectProfile.impl.TypedParamImpl
     * @see com.robenglander.libretto.spec.librettoProjectProfile.impl.LibrettoProjectProfilePackageImpl#getTypedParam()
     * @generated
     */
    EClass TYPED_PARAM = eINSTANCE.getTypedParam();

    /**
     * The meta object literal for the '<em><b>Type</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TYPED_PARAM__TYPE = eINSTANCE.getTypedParam_Type();

    /**
     * The meta object literal for the '<em><b>Param Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TYPED_PARAM__PARAM_NAME = eINSTANCE.getTypedParam_ParamName();

  }

} //LibrettoProjectProfilePackage
