/**
 * generated by Xtext 2.40.0
 */
package com.robenglander.libretto.spec.librettoProjectProfile;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>LLM Provider</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.robenglander.libretto.spec.librettoProjectProfile.LLMProvider#getKeyword <em>Keyword</em>}</li>
 *   <li>{@link com.robenglander.libretto.spec.librettoProjectProfile.LLMProvider#getName <em>Name</em>}</li>
 *   <li>{@link com.robenglander.libretto.spec.librettoProjectProfile.LLMProvider#getTypes <em>Types</em>}</li>
 *   <li>{@link com.robenglander.libretto.spec.librettoProjectProfile.LLMProvider#getLocalModelPaths <em>Local Model Paths</em>}</li>
 *   <li>{@link com.robenglander.libretto.spec.librettoProjectProfile.LLMProvider#getModels <em>Models</em>}</li>
 *   <li>{@link com.robenglander.libretto.spec.librettoProjectProfile.LLMProvider#getEndpoints <em>Endpoints</em>}</li>
 * </ul>
 *
 * @see com.robenglander.libretto.spec.librettoProjectProfile.LibrettoProjectProfilePackage#getLLMProvider()
 * @model
 * @generated
 */
public interface LLMProvider extends EObject
{
  /**
   * Returns the value of the '<em><b>Keyword</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Keyword</em>' containment reference.
   * @see #setKeyword(ProviderKeyword)
   * @see com.robenglander.libretto.spec.librettoProjectProfile.LibrettoProjectProfilePackage#getLLMProvider_Keyword()
   * @model containment="true"
   * @generated
   */
  ProviderKeyword getKeyword();

  /**
   * Sets the value of the '{@link com.robenglander.libretto.spec.librettoProjectProfile.LLMProvider#getKeyword <em>Keyword</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Keyword</em>' containment reference.
   * @see #getKeyword()
   * @generated
   */
  void setKeyword(ProviderKeyword value);

  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see com.robenglander.libretto.spec.librettoProjectProfile.LibrettoProjectProfilePackage#getLLMProvider_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link com.robenglander.libretto.spec.librettoProjectProfile.LLMProvider#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Types</b></em>' containment reference list.
   * The list contents are of type {@link com.robenglander.libretto.spec.librettoProjectProfile.ProviderType}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Types</em>' containment reference list.
   * @see com.robenglander.libretto.spec.librettoProjectProfile.LibrettoProjectProfilePackage#getLLMProvider_Types()
   * @model containment="true"
   * @generated
   */
  EList<ProviderType> getTypes();

  /**
   * Returns the value of the '<em><b>Local Model Paths</b></em>' containment reference list.
   * The list contents are of type {@link com.robenglander.libretto.spec.librettoProjectProfile.LocalModelPath}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Local Model Paths</em>' containment reference list.
   * @see com.robenglander.libretto.spec.librettoProjectProfile.LibrettoProjectProfilePackage#getLLMProvider_LocalModelPaths()
   * @model containment="true"
   * @generated
   */
  EList<LocalModelPath> getLocalModelPaths();

  /**
   * Returns the value of the '<em><b>Models</b></em>' containment reference list.
   * The list contents are of type {@link com.robenglander.libretto.spec.librettoProjectProfile.Model}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Models</em>' containment reference list.
   * @see com.robenglander.libretto.spec.librettoProjectProfile.LibrettoProjectProfilePackage#getLLMProvider_Models()
   * @model containment="true"
   * @generated
   */
  EList<Model> getModels();

  /**
   * Returns the value of the '<em><b>Endpoints</b></em>' containment reference list.
   * The list contents are of type {@link com.robenglander.libretto.spec.librettoProjectProfile.Endpoint}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Endpoints</em>' containment reference list.
   * @see com.robenglander.libretto.spec.librettoProjectProfile.LibrettoProjectProfilePackage#getLLMProvider_Endpoints()
   * @model containment="true"
   * @generated
   */
  EList<Endpoint> getEndpoints();

} // LLMProvider
