/**
 * generated by Xtext 2.40.0
 */
package com.robenglander.libretto.spec.librettoProjectProfile;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Method Override Rule</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.robenglander.libretto.spec.librettoProjectProfile.MethodOverrideRule#getSignature <em>Signature</em>}</li>
 *   <li>{@link com.robenglander.libretto.spec.librettoProjectProfile.MethodOverrideRule#getJavaType <em>Java Type</em>}</li>
 * </ul>
 *
 * @see com.robenglander.libretto.spec.librettoProjectProfile.LibrettoProjectProfilePackage#getMethodOverrideRule()
 * @model
 * @generated
 */
public interface MethodOverrideRule extends SurfaceRule
{
  /**
   * Returns the value of the '<em><b>Signature</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Signature</em>' containment reference.
   * @see #setSignature(OperationSignature)
   * @see com.robenglander.libretto.spec.librettoProjectProfile.LibrettoProjectProfilePackage#getMethodOverrideRule_Signature()
   * @model containment="true"
   * @generated
   */
  OperationSignature getSignature();

  /**
   * Sets the value of the '{@link com.robenglander.libretto.spec.librettoProjectProfile.MethodOverrideRule#getSignature <em>Signature</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Signature</em>' containment reference.
   * @see #getSignature()
   * @generated
   */
  void setSignature(OperationSignature value);

  /**
   * Returns the value of the '<em><b>Java Type</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Java Type</em>' containment reference.
   * @see #setJavaType(JavaType)
   * @see com.robenglander.libretto.spec.librettoProjectProfile.LibrettoProjectProfilePackage#getMethodOverrideRule_JavaType()
   * @model containment="true"
   * @generated
   */
  JavaType getJavaType();

  /**
   * Sets the value of the '{@link com.robenglander.libretto.spec.librettoProjectProfile.MethodOverrideRule#getJavaType <em>Java Type</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Java Type</em>' containment reference.
   * @see #getJavaType()
   * @generated
   */
  void setJavaType(JavaType value);

} // MethodOverrideRule
