/**
 * generated by Xtext 2.40.0
 */
package com.robenglander.libretto.spec.librettoProjectProfile;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Primitive Type</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.robenglander.libretto.spec.librettoProjectProfile.PrimitiveType#getKind <em>Kind</em>}</li>
 * </ul>
 *
 * @see com.robenglander.libretto.spec.librettoProjectProfile.LibrettoProjectProfilePackage#getPrimitiveType()
 * @model
 * @generated
 */
public interface PrimitiveType extends JavaType
{
  /**
   * Returns the value of the '<em><b>Kind</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Kind</em>' attribute.
   * @see #setKind(String)
   * @see com.robenglander.libretto.spec.librettoProjectProfile.LibrettoProjectProfilePackage#getPrimitiveType_Kind()
   * @model
   * @generated
   */
  String getKind();

  /**
   * Sets the value of the '{@link com.robenglander.libretto.spec.librettoProjectProfile.PrimitiveType#getKind <em>Kind</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Kind</em>' attribute.
   * @see #getKind()
   * @generated
   */
  void setKind(String value);

} // PrimitiveType
