/**
 * generated by Xtext 2.40.0
 */
package com.robenglander.libretto.spec.librettoProjectProfile;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Project Module</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.robenglander.libretto.spec.librettoProjectProfile.ProjectModule#getName <em>Name</em>}</li>
 *   <li>{@link com.robenglander.libretto.spec.librettoProjectProfile.ProjectModule#getDirs <em>Dirs</em>}</li>
 *   <li>{@link com.robenglander.libretto.spec.librettoProjectProfile.ProjectModule#getSpecDirs <em>Spec Dirs</em>}</li>
 *   <li>{@link com.robenglander.libretto.spec.librettoProjectProfile.ProjectModule#getTestDirs <em>Test Dirs</em>}</li>
 *   <li>{@link com.robenglander.libretto.spec.librettoProjectProfile.ProjectModule#getMainDirs <em>Main Dirs</em>}</li>
 *   <li>{@link com.robenglander.libretto.spec.librettoProjectProfile.ProjectModule#getBasePackages <em>Base Packages</em>}</li>
 * </ul>
 *
 * @see com.robenglander.libretto.spec.librettoProjectProfile.LibrettoProjectProfilePackage#getProjectModule()
 * @model
 * @generated
 */
public interface ProjectModule extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see com.robenglander.libretto.spec.librettoProjectProfile.LibrettoProjectProfilePackage#getProjectModule_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link com.robenglander.libretto.spec.librettoProjectProfile.ProjectModule#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Dirs</b></em>' attribute list.
   * The list contents are of type {@link java.lang.String}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Dirs</em>' attribute list.
   * @see com.robenglander.libretto.spec.librettoProjectProfile.LibrettoProjectProfilePackage#getProjectModule_Dirs()
   * @model unique="false"
   * @generated
   */
  EList<String> getDirs();

  /**
   * Returns the value of the '<em><b>Spec Dirs</b></em>' attribute list.
   * The list contents are of type {@link java.lang.String}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Spec Dirs</em>' attribute list.
   * @see com.robenglander.libretto.spec.librettoProjectProfile.LibrettoProjectProfilePackage#getProjectModule_SpecDirs()
   * @model unique="false"
   * @generated
   */
  EList<String> getSpecDirs();

  /**
   * Returns the value of the '<em><b>Test Dirs</b></em>' attribute list.
   * The list contents are of type {@link java.lang.String}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Test Dirs</em>' attribute list.
   * @see com.robenglander.libretto.spec.librettoProjectProfile.LibrettoProjectProfilePackage#getProjectModule_TestDirs()
   * @model unique="false"
   * @generated
   */
  EList<String> getTestDirs();

  /**
   * Returns the value of the '<em><b>Main Dirs</b></em>' attribute list.
   * The list contents are of type {@link java.lang.String}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Main Dirs</em>' attribute list.
   * @see com.robenglander.libretto.spec.librettoProjectProfile.LibrettoProjectProfilePackage#getProjectModule_MainDirs()
   * @model unique="false"
   * @generated
   */
  EList<String> getMainDirs();

  /**
   * Returns the value of the '<em><b>Base Packages</b></em>' attribute list.
   * The list contents are of type {@link java.lang.String}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Base Packages</em>' attribute list.
   * @see com.robenglander.libretto.spec.librettoProjectProfile.LibrettoProjectProfilePackage#getProjectModule_BasePackages()
   * @model unique="false"
   * @generated
   */
  EList<String> getBasePackages();

} // ProjectModule
