/**
 * generated by Xtext 2.40.0
 */
package com.robenglander.libretto.spec.librettoProjectProfile;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Provider Type</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.robenglander.libretto.spec.librettoProjectProfile.ProviderType#getKeyword <em>Keyword</em>}</li>
 *   <li>{@link com.robenglander.libretto.spec.librettoProjectProfile.ProviderType#getName <em>Name</em>}</li>
 * </ul>
 *
 * @see com.robenglander.libretto.spec.librettoProjectProfile.LibrettoProjectProfilePackage#getProviderType()
 * @model
 * @generated
 */
public interface ProviderType extends EObject
{
  /**
   * Returns the value of the '<em><b>Keyword</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Keyword</em>' containment reference.
   * @see #setKeyword(ProviderTypeKeyword)
   * @see com.robenglander.libretto.spec.librettoProjectProfile.LibrettoProjectProfilePackage#getProviderType_Keyword()
   * @model containment="true"
   * @generated
   */
  ProviderTypeKeyword getKeyword();

  /**
   * Sets the value of the '{@link com.robenglander.libretto.spec.librettoProjectProfile.ProviderType#getKeyword <em>Keyword</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Keyword</em>' containment reference.
   * @see #getKeyword()
   * @generated
   */
  void setKeyword(ProviderTypeKeyword value);

  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see com.robenglander.libretto.spec.librettoProjectProfile.LibrettoProjectProfilePackage#getProviderType_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link com.robenglander.libretto.spec.librettoProjectProfile.ProviderType#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

} // ProviderType
