/**
 * generated by Xtext 2.40.0
 */
package com.robenglander.libretto.spec.librettoProjectProfile;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Test Gen Legacy Remediation Rules Block</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.robenglander.libretto.spec.librettoProjectProfile.TestGenLegacyRemediationRulesBlock#getRules <em>Rules</em>}</li>
 * </ul>
 *
 * @see com.robenglander.libretto.spec.librettoProjectProfile.LibrettoProjectProfilePackage#getTestGenLegacyRemediationRulesBlock()
 * @model
 * @generated
 */
public interface TestGenLegacyRemediationRulesBlock extends EObject
{
  /**
   * Returns the value of the '<em><b>Rules</b></em>' containment reference list.
   * The list contents are of type {@link com.robenglander.libretto.spec.librettoProjectProfile.TestGenLegacyRemediationRule}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Rules</em>' containment reference list.
   * @see com.robenglander.libretto.spec.librettoProjectProfile.LibrettoProjectProfilePackage#getTestGenLegacyRemediationRulesBlock_Rules()
   * @model containment="true"
   * @generated
   */
  EList<TestGenLegacyRemediationRule> getRules();

} // TestGenLegacyRemediationRulesBlock
