/**
 * generated by Xtext 2.40.0
 */
package com.robenglander.libretto.spec.librettoProjectProfile;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Typed Param</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.robenglander.libretto.spec.librettoProjectProfile.TypedParam#getType <em>Type</em>}</li>
 *   <li>{@link com.robenglander.libretto.spec.librettoProjectProfile.TypedParam#getParamName <em>Param Name</em>}</li>
 * </ul>
 *
 * @see com.robenglander.libretto.spec.librettoProjectProfile.LibrettoProjectProfilePackage#getTypedParam()
 * @model
 * @generated
 */
public interface TypedParam extends EObject
{
  /**
   * Returns the value of the '<em><b>Type</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Type</em>' containment reference.
   * @see #setType(JavaType)
   * @see com.robenglander.libretto.spec.librettoProjectProfile.LibrettoProjectProfilePackage#getTypedParam_Type()
   * @model containment="true"
   * @generated
   */
  JavaType getType();

  /**
   * Sets the value of the '{@link com.robenglander.libretto.spec.librettoProjectProfile.TypedParam#getType <em>Type</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Type</em>' containment reference.
   * @see #getType()
   * @generated
   */
  void setType(JavaType value);

  /**
   * Returns the value of the '<em><b>Param Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Param Name</em>' attribute.
   * @see #setParamName(String)
   * @see com.robenglander.libretto.spec.librettoProjectProfile.LibrettoProjectProfilePackage#getTypedParam_ParamName()
   * @model
   * @generated
   */
  String getParamName();

  /**
   * Sets the value of the '{@link com.robenglander.libretto.spec.librettoProjectProfile.TypedParam#getParamName <em>Param Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Param Name</em>' attribute.
   * @see #getParamName()
   * @generated
   */
  void setParamName(String value);

} // TypedParam
