/*
 * generated by Xtext 2.40.0
 */
package com.robenglander.libretto.spec.parser.antlr;

import com.google.inject.Inject;
import com.robenglander.libretto.spec.parser.antlr.internal.InternalLibrettoSpecParser;
import com.robenglander.libretto.spec.services.LibrettoSpecGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class LibrettoSpecParser extends AbstractAntlrParser {

	@Inject
	private LibrettoSpecGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalLibrettoSpecParser createParser(XtextTokenStream stream) {
		return new InternalLibrettoSpecParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Spec";
	}

	public LibrettoSpecGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(LibrettoSpecGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
